DesignSafe-CI/portal

designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/data-browser.js
Think I deleted that method on the controller when removing all that other code.
=> fix select to work again

docker-compose-dev.yml, requirements.txt
All tests passed, no errors from search/data depot/dashboard queries
=> DES-252: elasticsearch upgrade to 5.x, not much to do

designsafe/apps/api/agave/filemanager/public_search_index.py, designsafe/apps/api/agave/filemanager/search_index.py, designsafe/apps/api/data/agave/elasticsearch/documents.py
@xirdneh might want to look at those queries
=> DES-276: Changed the filtered queries to bool

designsafe/apps/api/agave/views.py, designsafe/apps/api/notifications/views/webhooks.py, designsafe/apps/api/tasks.py, designsafe/apps/workspace/tasks.py
from present perfect progressive tense to simple past tense
=> Change notification tense 

designsafe/apps/api/agave/views.py, designsafe/apps/api/external_resources/googledrive/filemanager/manager.py, designsafe/apps/api/external_resources/googledrive/models/files.py, designsafe/apps/googledrive_integration/views.py, designsafe/common_settings.py, designsafe/context_processors.py, designsafe/static/scripts/data-depot/templates/data-depot-toolbar.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/templates/google_verification.html, designsafe/urls.py
-Adds google site verification
-Disables 'Preview Images' and 'Rename' buttons for external Data Depot resources (Box, Dropbox, Google Drive)
=> Google Site Verification and Data Depot Fixes

designsafe/apps/dashboard/static/designsafe/apps/dashboard/html/dashboard.html, designsafe/apps/workspace/static/designsafe/apps/workspace/html/application-form.html, designsafe/apps/workspace/static/designsafe/apps/workspace/html/application-tray.html, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-tray.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/simple-list-service.js, designsafe/apps/workspace/static/designsafe/apps/workspace/styles/workspace.css, designsafe/static/styles/main.css
- Adds functionality to close open tab by clicking on tab header
- Change 'Private' to 'My Apps' in apps tray
- Alphabetical order of apps
- Users can relaunch app by clicking app again
- Styling
=> Workspace Apps Tray Fixes

designsafe/apps/notifications/views.py, designsafe/apps/rapid/models.py, designsafe/apps/workspace/static/designsafe/apps/workspace/html/jobs-status.html, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/jobs-status.js
=> Changing webhooks and client side to handle apps like PotreeViewer

CHANGELOG.md, conf/docker/docker-compose-build.yml, designsafe/apps/api/projects/models.py, designsafe/apps/api/projects/urls.py, designsafe/apps/api/projects/views.py, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-tray.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/data-browser.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/simple-list-service.js, designsafe/apps/workspace/static/designsafe/apps/workspace/styles/workspace.css, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
Also suppresses unused 'metadata_list' call when listing workspace apps.
=> Task/des 288: Fix - Add 'My Projects' to Workspace browser

designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-tray.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/simple-list-service.js
- Removes redundant metadata call for html apps, improving html app load time
- Avoid error if label of app is null
- Filter apps listing on 'available': true in query
=> Bug/des 445: Workspace Efficiency Improvements

designsafe/apps/api/notifications/models.py, designsafe/apps/googledrive_integration/migrations/0002_auto_20180215_2239.py, designsafe/apps/googledrive_integration/views.py, designsafe/apps/licenses/templates/designsafe/apps/licenses/ls-dyna_details.html, designsafe/apps/notifications/views.py, designsafe/apps/workspace/static/designsafe/apps/workspace/html/application-form.html, designsafe/settings/common_settings.py, designsafe/settings/external_resource_settings.py
Also:
- Prevents multiple job submissions from workspace while a job is currently submitting
- Adds action link to "Your VNC session is ready" notification
=> Rework Google Auth client secrets method

designsafe/apps/cms_plugins/migrations/0001_initial.py, designsafe/apps/cms_plugins/models.py, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
Adding new aspect ratio for podcast imbed to CMS
=> DES-454 CMS aspect ratio

designsafe/apps/applications/static/designsafe/apps/applications/html/application-tray.html, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-add.js, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-edit.js, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-tray.js, designsafe/apps/applications/static/designsafe/apps/applications/scripts/services/apps-service.js, designsafe/apps/applications/views.py, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/jobs-service.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/simple-list-service.js, designsafe/static/scripts/ng-designsafe/ng-designsafe.js
And makes sure html app metadata only updates if one appId is returned
=> Applications fixes and app category name change to 'Partner Data Apps'

designsafe/static/scripts/ng-designsafe/html/directives/dd-listing.html, designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-categories.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/static/scripts/ng-designsafe/services/project-service.js
Made a few changes to the ui for consistency, and removed the integrated analysis/reports from the classification area of simulation project types.
=> task/DES-566: Removed integrated analysis/reports

designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/app.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/apps-service.js, designsafe/apps/workspace/utils.py, designsafe/apps/workspace/views.py
- creates the directory "SCEC_BPP_GMPortal", or whatever file_path is sent via the workspace app
- creates the file ".Identity" with the users username embedded in that directory
- launch the SCEC notebook from the community folder
=> Task/des 571: Rework SCEC notebook

designsafe/static/scripts/data-depot/templates/project-list.html
Show spinner in My Projects when searching/navigating to different tab.
=> DES-577: Show spinner in My Projects when searching/navigating to different tab

designsafe/apps/applications/static/designsafe/apps/applications/html/application-tray.html, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-edit.js, designsafe/apps/applications/static/designsafe/apps/applications/scripts/services/simple-list-service.js, designsafe/apps/workspace/static/designsafe/apps/workspace/html/application-tray.html, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/simple-list-service.js, designsafe/apps/workspace/views.py
- Sends a list of project ids via the `_userProjects` parameter to the wrapper script to include when mounting directories.
- Format is `["uuid,projectId", ...]` so projects will be mounted to directories with the Project ID, similar to how it is done in Jupyter notebooks
- Includes fixes to appIcon
=> Task/des 601: Send list of project ids to VNC applications

designsafe/static/scripts/data-depot/controllers/projects.js
Updated checkMetadata function and added hybrid sim checks.
=> Task/DES-581: Checks for Hybrid Sim

designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-preview.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
https://jira.tacc.utexas.edu/browse/DES-21
=> Task/des 21 - When opening Jupyter files from Data Depot, users should be prompted with an Open in Jupyter Notebooks button.

designsafe/apps/api/search/views.py
Somewhere along the line the `offset` and `limit` arguments got removed from this query (probably my fault tbh). I just added them back in.
=> task/DES-620: Fixed pagination for My Data in site search.

designsafe/apps/accounts/templates/designsafe/apps/accounts/password_reset.html
-Added button/link at https://designsafe.dev/account/password-reset/ that redirects user to request username on TACC Portal.
-Once this link is in production Joe Stubbs will add changes in Agave to the button on Login page, which will then say: Forgot Password or Username
=> added link to retrieve username - https://jira.tacc.utexas.edu/browse/DES-559

designsafe/static/scripts/ng-designsafe/html/directives/dd-listing.html, designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-categories.html, designsafe/static/scripts/ng-designsafe/html/modals/project-service-manage-hybrid-simulations.html
This should be all if not most of the wording changes required for hybrid sim
=> task/HybridAdjustments - Wording Fixes to Hybrid Sim

designsafe/static/scripts/data-depot/controllers/published.js, designsafe/static/scripts/data-depot/templates/published-data-listing.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
Display citations in Publication area as well as individual projects, experiments, simulations, hybrid simulations, and other.
=> bug/DES-567-Revised - Properly display citations for Projects area

designsafe/static/scripts/data-depot/templates/data-depot-toolbar.html, designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-preview.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
Removed buttons in data-depot toolbar
Removed buttons in preview modal toolbar
Reduced preview modal's size by ~8%
=> task/DES-652 - Preview Modal Changes

CHANGELOG.md, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/apps-service.js
nodeCount and processorsPerNode to be handled via inputs and evaluated in the wrapper.
=> Remove nodeCount parameter from front-end

designsafe/static/scripts/data-depot/templates/project-view.html
changed the publication message that displays in a project after a user publishes a project.
=> task/pubNotification - changed publication message

CHANGELOG.md, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/templates/view-citations.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
Changed some links in the Citation modal
Added Citation button in published area to the new ES6 style toobar/ctrl
=> task/DES-693 fixes to Citation modal

.eslintrc, CHANGELOG.md, designsafe/apps/applications/templates/designsafe/apps/applications/index.html, designsafe/apps/workspace/templates/designsafe/apps/workspace/index.html, designsafe/static/scripts/applications/html/application-tray.html
- Fix help link for workspace
- Allow eslint to accept doublequotes if singlequotes are inside
- Fix broken applications template
- Fix appIcon not showing in applications space
=> Task/des 526: Workspace & Apps Fixes

designsafe/static/scripts/data-depot/controllers/projects.js, designsafe/static/scripts/ng-designsafe/html/directives/dd-listing.html
fixed issue with "select/deselect all" not selecting all files
output data was being displayed in the metadata section even when it was not selected
removed requirements for simulation substructures and their outputs
some small bug fixes
=> fix/HybridSimReq: fix ui errors and remove specific requirements

.gitignore, designsafe/static/scripts/ng-designsafe/ng-designsafe.js, designsafe/templates/base.html, package-lock.json, package.json, webpack.config.js
Still a bit of hack to get the recon CSS bundled, but it works for now...
Also removed ngAnnotate plugin from webpack config, need to update packages.json
=> hotfix for recon portal, the css stuff got borked in one of those merges

designsafe/apps/geo/static/designsafe/apps/geo/html/map.html, designsafe/apps/geo/static/designsafe/apps/geo/scripts/index.js, designsafe/apps/geo/static/designsafe/apps/geo/scripts/services/geo-data-service.js, designsafe/apps/geo/static/designsafe/apps/geo/styles/icons/style.css
Hotfix, need to revisit this soon. Am going to move hazmapper into /static soon, will take a look then.
=> hotfix for saving things in hazmapper

designsafe/apps/api/search/views.py, designsafe/apps/search/templates/designsafe/apps/search/index.html, designsafe/static/scripts/navbar.js, designsafe/static/scripts/search/components/modals/search-help-modal/search-help-modal.component.html, designsafe/static/scripts/search/components/modals/search-help-modal/search-help-modal.component.js, designsafe/static/scripts/search/components/search/search.component.html, designsafe/static/scripts/search/components/search/search.component.js, designsafe/static/scripts/search/components/search/search.component.spec.js, designsafe/static/scripts/search/index.js, designsafe/static/scripts/search/services/search.service.js
This stuff got clobbered during the merge.
=> task/DES-711: Add filter switching, spinner, help dialog, unit tests in site search

designsafe/static/scripts/data-depot/components/published/published.component.html
The href link for associated projects listed on published projects were borked.
=> Bug/DES-737: fix for associated project href

designsafe/static/scripts/data-depot/components/published/published.component.html
Hybrid-Sim template was missing DOI, date and needed adjustments to global_model.
=> Bug/DES-740: Hybrid Sim template fixes

designsafe/static/scripts/data-depot/components/publications/publications.component.html, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/data-depot/components/published/published.component.js, designsafe/static/scripts/data-depot/components/published/published.component.spec.js, designsafe/static/scripts/data-depot/fixtures/published.fixture.json, designsafe/static/scripts/data-depot/index.js, designsafe/static/scripts/data-depot/services/index.js, designsafe/static/scripts/data-depot/services/published.service.js, designsafe/static/scripts/data-depot/services/published.service.spec.js, designsafe/static/scripts/data-depot/templates/view-collabs.html, designsafe/templates/base.html
This is done by modifying the header directly using `$window`.
=> DES-713: Add header metadata to publication view pages.

designsafe/static/scripts/applications/controllers/application-add.js, designsafe/static/scripts/applications/controllers/application-edit.js, designsafe/static/scripts/applications/controllers/application-tray.js, designsafe/static/scripts/applications/html/application-tray.html, designsafe/static/scripts/applications/services/apps-pems-service.js, designsafe/static/scripts/applications/services/simple-list-service.js, designsafe/static/scripts/workspace/components/application-tray/application-tray.component.js, designsafe/static/scripts/workspace/controllers/application-form.js, designsafe/static/scripts/workspace/controllers/index.js, designsafe/static/scripts/workspace/fixtures/app-meta.fixture.json, designsafe/static/scripts/workspace/services/apps-service.js, designsafe/static/scripts/workspace/services/index.js, designsafe/static/scripts/workspace/tests/application-form.spec.js, designsafe/static/scripts/workspace/tests/application-tray.component.spec.js
Fixes a bug in application-add controller
=> Task/des 703: Fix import error & Small improvements

designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js
Made Changes to Project Header
Created new authors object for sorting and ordering of authors on experiments
=> Task/DES-657 - Authorship Ordering for Experiments

designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/ng-designsafe/html/directives/dd-listing.html
Also added var declaration to fix an error as well
=> Task/DES-530 - Changing License Order

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html
added a link to the curation guidelines page under the curation tutorials link in the data depot.
=> Task/DES-551 - Curation Guidelines link

designsafe/static/scripts/data-depot/components/published/published.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js
**Changes Made:**
1. Fixed a bug causing the "Open in Jupyter" button to always be displayed in the preview modal for published projects
2. The file listing for published projects should work now
3. Removed "project image" request from init
4. Added/removed some semicolons as recommended
=> Bug/DES-730 - launch Jupyter button (from preview) and published listing fix

designsafe/static/scripts/data-depot/components/published/published.component.html
Fixed associated project href binding and an issue that caused data to overflow in the published project table.
=> Task/DES-762 - associated prj href and table overflow

designsafe/apps/api/agave/filemanager/public_search_index.py, designsafe/apps/api/projects/urls.py, designsafe/apps/api/projects/views.py, designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/components/index.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.component.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.spec.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.template.html, designsafe/static/scripts/data-depot/components/publications/publications.component.js, designsafe/static/scripts/data-depot/components/published/published.component.js, designsafe/static/scripts/data-depot/index.js, designsafe/static/scripts/data-depot/services/published.service.js, designsafe/static/scripts/ng-designsafe/html/directives/dd-public-listing.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
=> task/DES-479: Add view for NEES publications

designsafe/static/scripts/data-depot/components/projects/project-data/project-data.component.js
Fixed a few bugs causing the curation pipeline to break.
=> bug/PipelineFix - Fixing Errors in Curation Pipeline

designsafe/apps/accounts/tasks.py
Removed a `user_model `object filter and added logic to write a row stating "Unable to find profile for <username>" when users couldn't be found by `create_report`.  This should now provide an accurate count of all users.
Also added doc strings to better explain what the purpose of this function is, and what's going on inside of it.
=> Remove filter from create_report Celery task, added doc strings

designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/ng-designsafe/services/index.js, designsafe/static/scripts/ng-designsafe/services/project-service.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.js
Added a modal popup for project type selection. Right now it only fires up if a user is in an "other" project type and clicks on the "curation directory" button.
=> Task/DES-784 Project Type Selection

designsafe/apps/api/projects/views.py, designsafe/apps/projects/models/agave/base.py, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/styles/ng-designsafe.css
- Added capabilities to select or create a custom project type for "other"
- When selected project type "other" is replaced with this value in the UI
- Replaced dropdown arrows in the project listings
=> Task/DES-816 Project Other Features

designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.js, designsafe/static/scripts/ng-designsafe/services/project-service.js
Added check to selection area for incomplete or missing categories
Added green checkmark to selected exp, sims, hybsims in selection area
=> Task/DES-783 - Missing data check and Selection Checkmark

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-hybrid/pipeline-hybrid.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-simulation/pipeline-simulation.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/file-categories/file-categories.template.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/styles/ng-designsafe.css, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
DES-797, 804, 782, 786, 793, 798, 799, 800, 821, 822, 826
Multiple UI and visual bug fixes for the new projects area
=> Task/DES-[visual] See Comments

.eslintrc, designsafe/apps/api/agave/urls.py, designsafe/apps/api/agave/views.py, designsafe/apps/data/models/agave/files.py, designsafe/static/scripts/data-depot/components/file-metadata/file-metadata.component.js, designsafe/static/scripts/data-depot/components/file-metadata/file-metadata.controller.js, designsafe/static/scripts/data-depot/components/file-metadata/file-metadata.spec.js, designsafe/static/scripts/data-depot/components/file-metadata/file-metadata.template.html, designsafe/static/scripts/data-depot/components/index.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.html, designsafe/static/scripts/ng-designsafe/services/file-listing.js, package-lock.json
- Added an additional query param on the existing file metadata route which was previously setup only to return the keywords of any metadata record. 
- Created a new component for the file metadata in the preview window
- Added some unit tests for the component
=> DES-807: Add Additional metadata for Rapid folks into the preview window

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html
Reformatted project header to fix alignment issues
=> Task/DES-785 - Reformatting Project Header

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js
- removed requirement for second date figure and adjusted UI accordingly
- added loading banner for curation directory
- disabled curation buttons while directory loads
=> Task/DES-787 - rm second date requirement and disabled curation buttons while loading

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
- Changed wording on loading spinner
- Fixed spacing in experiment/category dropdowns
- Set experiment tabs to closed in selection in preview if more than 1 experiment
=> Task/DES-819 - Spinner Wording Fix and Dropdown Tab Spacing

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-move/data-browser-service-move.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.js
- Fixed typo causing issues with move button
- Hiding descriptions if not present
- Added analysis references to category listing
=> Task/DES-830-840 - Move button fix and hide missing descriptions

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-hybrid/pipeline-hybrid.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-simulation/pipeline-simulation.component.js, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.js, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js
- Pipeline "Edit" modals will be preloaded with selected edit Experiment or Category
- Fixed an issue causing Authors to no update correctly in Edit Sim and HybSim forms.
=> Task/DES-843 - Preload Experiment and Category in Edit Pipeline

designsafe/static/scripts/rapid/html/index.html
Recon Portal User Guide link added under logo.
=> task/DES-660 Add Recon Portal User Guide link on Recon Portal page

designsafe/templates/includes/header.html
Pulldown menu in upper right of Designsafe (Welcome {your name here}) which has My Dashboard, Notifications and Logout will also contain a My Tickets option that takes you to https://designsafe.dev/help/tickets/.
=> task/DES-682 Added My Tickets to Welcome pull-down

designsafe/static/scripts/workspace/html/jobs-status.html
In order to better differentiate the workspace Job events from other things on the page, I've used bootstrap's css classes for each Job state.
=> task/DES-58 Use colors from bootstrap for each Job state

designsafe/apps/api/projects/views.py, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.js
Fixed an issue causing usernames to be duplicated upon project creation
Added project type selection and warning message to edit project modal
=> Task/DES-838 - Duplicated User Fix and Edit Project Type Button

designsafe/static/scripts/data-depot/components/projects/project-listing/project-listing.component.html, designsafe/static/scripts/ng-designsafe/components/modals/dd-file-picker/dd-file-picker.js, designsafe/static/scripts/ng-designsafe/html/directives/dd-listing.html
"Fixed the error message to reflect Something went wrong. Please try again, and if this error persists please use Help to file a ticket. This was fixed on in the following areas Dd-listing.html line 70
Project-listing.component.html  line  50
Dd-file-picker.js line 114
I could not test for the error due to it being triggered by browser issues"
=> Des 640 changing the error message

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-other/pipeline-other.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html
Fixing spelling errors and changing the wording of some ui elements.
=> Task/DES-869(852, 873, 847) - Typo and wording changes

designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.template.html, designsafe/static/scripts/ng-designsafe/services/index.js, designsafe/static/scripts/projects/components/confirm-delete/confirm-delete.component.html, designsafe/static/scripts/projects/components/confirm-delete/confirm-delete.component.js, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.js, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js, designsafe/static/styles/ng-designsafe.css
- Removed hover highlight on file listing
- Added highlight for selected files
- Added "Select All" checkbox in file listing
- Added larger green checkboxes
- Created confirmation popup when deleting project entities
=> Task/DES-863(858, 857, 855) - Issues related to ui selection and deletion of entities

designsafe/apps/auth/tasks.py, designsafe/apps/auth/views.py
Fixed the code that set a user's My Data ACLs upon their first login to the portal.
=> bug/DES-811: Fix My Data ACL app code

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/ng-designsafe/directives/index.js, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js
Created a formatter 'dsUserList' to organize a list of usernames in alphabetical order.
=> Task/DES-848 - Format CoPIs in alphabetical order

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html
Dropdown arrows should display properly
Fixed a UI issue related to category relations
=> Task/DES-803, Task/DES-885, and Bug/DES-886

designsafe/static/scripts/data-depot/components/published/published.component.html
Fixed a typo preventing published hybrid sims from displaying properly.
=> Task/DES-890 Published Hybrid Simulation Fix

designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-other.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-other.component.js, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js
Allow experiment equipment type to be edited and updated other selection
=> Task/DES-532 - Allow users to edit Equipment Type

designsafe/apps/projects/models/agave/experimental.py, designsafe/apps/projects/models/agave/hybrid_simulation.py, designsafe/apps/projects/models/agave/simulation.py, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.js, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js
Adjusted some existing code that supported older single award types.
=> Bug/DES-899 Awards Correction for Existing Projects

designsafe/apps/workspace/views.py, designsafe/static/scripts/ng-designsafe/providers/notifications-provider.js, designsafe/static/scripts/workspace/controllers/application-form.js, designsafe/static/scripts/workspace/controllers/jobs-status.js, designsafe/static/scripts/workspace/html/jobs-status.html, designsafe/static/scripts/workspace/services/jobs-service.js
- Allows DCV jobs to function correctly by appending the string 'dcvserver' automatically to job names for DCV apps
- Refreshes job status panel on notification processing
- Fix jobs_wh_url
- Fix job status output for all finished jobs
- Check that params exist in app def before adding
=> Minor bug fixes: Notifications; DCV; Job Status Modal

designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
Fixed an issue causing the save function in edit project modal to fail.
=> Bug/DES-924 - Bug with Guest Users

designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-hybrid/pipeline-hybrid.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-simulation/pipeline-simulation.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/styles/ng-designsafe.css
1. Added citation preview to publication pipeline
2. Displaying experiment authors in a line instead of a column. Created a background colored block to cover last ";" since $last was not working in the filtered list authors list.
=> Task/DES-853(856) - Citation Preview & Authorship Format

designsafe/apps/workspace/views.py
=> Add _wh_base_url back to job submission params

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.js
1. Categorized files were not being updated in the Manage Categories modal. This should be fixed now.
2. Fixed a typo that wrote over the "edit" button for categories in the pipeline.
=> Task/DES-930 - Update Categorized Files in Manage Categories Modal

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js
Disabled Prepare to Publish button, and reduced opacity for curation buttons while loading
=> Task/DES-934 - Opacity change on buttons and Disabling others.

designsafe/apps/api/agave/filemanager/public_search_index.py, designsafe/apps/api/tasks.py, designsafe/apps/projects/models/agave/base.py
Creates a zip file within the published project's directory containing the project's files.
=> Task/DES-656 Zip published project data with celery task

designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
changing or saving tags on a file that shared the same category relation would overwrite or duplicate the tags on the other file with the same relation.
=> Bug/DES-945 - Fix for issues with tagging files of the same category relation

designsafe/static/scripts/data-depot/components/index.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js
Import got messed up in the merge I reckon
=> hotfix for file metadata in preview modal

designsafe/libs/elasticsearch/utils.py
- Handle files with invalid names
=> Bug/des 963: repair_paths fixes.

designsafe/static/scripts/search/components/search-listing/search-listing.component.html, designsafe/static/scripts/search/components/search/search.component.html
Remove 'created' label from DES projects, add it back to NEES projects
=> Task/des 961: Site search tweaks (update 4/25/19)

designsafe/apps/api/projects/views.py, designsafe/apps/projects/models/agave/base.py
Users added onto a project would be added to project metadata but would not have access to the project in their project directory.
=> Bug/DES-953 - Fix issue with team members not being able to access projects

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.js
Fixing some bugs with template for new published projects
Fixed a bug causing new project creators to be stuck in project type selector
=> Bug/DES-999 - Fixes for published template and project type template

designsafe/apps/api/projects/views.py, designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js, designsafe/static/scripts/projects/components/file-categories/file-categories.component.js, designsafe/static/scripts/projects/components/file-categories/file-categories.scss, designsafe/static/scripts/projects/components/file-categories/file-categories.template.html, designsafe/static/scripts/projects/components/file-category-selector/file-category-selector.scss, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.js, designsafe/static/styles/ng-designsafe.css
1. Fixed issues with Tag Formatting
2. Fixed typo preventing updates to project members
3. Added project Other file tags
4. Fixed PI not showing in normal and older publication template
5. Fixed Guest Authors not showing up
6. Fixed bug in templated for managing project type
=> Task/DES-845 - File Tag Formatting and Publication Template Fixes

designsafe/settings/common_settings.py, designsafe/settings/test_settings.py
Added settings to allow CMS to use `iframe` tags.
=> Task/des 1000 Added settings to allow CMS to use iframe tags

designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.js
License types are now individually selectable for Datasets, Works, and Software.
=> bug/DES-986: Cannot select multiple licenses

designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html
Add links to license websites to Licenses modal.
=> task/DES-988: [Medium Priority] [Functional] License website links are not functioning

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.template.html, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.component.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.spec.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.template.html, designsafe/static/scripts/data-depot/components/publications/publications.spec.js, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
At some point the name of the `neesPublishedData` state changed without any of the references to that state changing with it.
=> bug/DES-1025: NEES, Experiment tab, file links do not work

designsafe/apps/api/users/urls.py, designsafe/apps/api/users/views.py, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.component.js, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js, designsafe/static/scripts/ng-designsafe/services/user-service.js, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js, designsafe/static/scripts/projects/components/file-categories/file-categories.component.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.js
1. Created public view for returning user data for formatting a published project.
2. Fixed an issue preventing copis from being saved to projects
3. Updated published templates with the new directive
=> Bug/DES-1005 - Fix bug with PI/Authors not rendering for Logged Out Users

designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/static/scripts/ng-designsafe/services/project-service.js, designsafe/static/scripts/projects/components/manage-experiments/experimental-data.json, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js
Moved experiment details into .json file to share with other components
Modified templates to display the proper titles of each facility, tool, and type
=> Task/DES-792 - Format experiment details in published and project areas

designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js
1. Added navigation for published projects with categorized directories
2. Fixed a bug preventing other publications
=> Task/DES-1018 - Add publication subdirectory navigation

designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-agreement.html, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.js
- Fixed PI not showing for older publications
- Fixed order of authors in citation
- Removed requirement for second date field when editing an Experiment
- Fix X button in license agreement area
=> Bug/DES-1044 - Fixing various front-end bugs

designsafe/apps/api/agave/filemanager/public_search_index.py, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js
- Update the Manage Experiments modal when deleting an Experiment
- Add option to deselect radio buttons for licenses
- Fix for issue related to publishing with multiple licenses
- Template change to account for updated licenses
=> Bug/DES-1045 - Experiment update on deletion, deselect license option, license to licenses

designsafe/static/scripts/ng-designsafe/services/project-service.js, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
- Stop the modal from returning the user to the curation dir
- Update the changes made in the modal to the preview in the pipeline
=> Bug/DES-1062 - Fixes to Edit Project Modal in Pipeline

designsafe/static/scripts/data-depot/components/published/published.html
Views for Other and FR were not showing
=> Bug/DES-1074 - Other template fix

designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.js
Publish button wasn't clickable due to `validSelection` looking for `this.projectType` instead of `this.projType`
=> hotfix projects publishing

designsafe/apps/api/agave/filemanager/search_index.py, designsafe/apps/api/public_data/views.py, designsafe/static/scripts/data-depot/components/data-depot-browser/data-depot-browser.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/index.js, designsafe/static/scripts/search/components/search-listing/search-listing.component.html
Fixes these bugs:
- Trying to navigate to a directory inside a search result executes another search instead
- File preview and Open in Jupyter links are broken in search listings.
- Navigating to a file in Site Search will try to open it as a folder.
=> bug/DES-1081: Fix navigation/preview in search listings

designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html
Thanks for the screenshot @Strmiska !
=> bug/DES-1090 - Commented out the citation button from Data Depot ribbon.

designsafe/static/scripts/projects/components/file-categories/file-categories.scss
Still need to move the <file-categories-selector> element out of the <files-listing> template and into the <file-categories> component in order for the layout to look right. That is a bit more headache and I'm not confident that I can get it done and tested quickly enough.
=> make all selects in curation be 30px

designsafe/apps/api/agave/filemanager/search_index.py, designsafe/apps/api/search/views.py
Need to specifically exclude the trash folder.
=> bug/DES-1123: Exclude trash results from Community data search

designsafe/apps/api/users/views.py, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-hybrid/pipeline-hybrid.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-simulation/pipeline-simulation.component.html, designsafe/static/scripts/data-depot/components/projects/project-listing/project-listing.component.html, designsafe/static/scripts/data-depot/components/projects/project-listing/project-listing.component.js, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-move/data-browser-service-move.component.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-move/data-browser-service-move.component.js, designsafe/static/scripts/ng-designsafe/directives/index.js, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js, designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-copy.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/static/scripts/ng-designsafe/services/user-service.js, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.html
- Updated directives meant to format usernames for project related views.
- Condensed individual requests for user data in `move/copy` modals and in `project-listing`
- Updated templates where applicable
=> Task/DES-1115 - Consolidate requests for user data where possible

designsafe/static/scripts/workspace/html/jobs-status.html
Some job status info attributes have changed names from aloe
=> Update job status info from aloe

designsafe/apps/api/agave/filemanager/public_search_index.py, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/ng-designsafe/directives/ng-designsafe-directives.js, designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.html
Created a condition inside the `dsUserList` directive to accept a list of user objects for other
Added try/except catch if user's name is not found in database
=> Bug/DES-1144 - Fix user directive to support other project authors (hotfix)

designsafe/sitemaps.py, designsafe/urls.py
=> task/DES-1143 - Modify sitemap to use absolute path of each URL pt2

designsafe/static/scripts/workspace/controllers/data-browser.js
The listing needed to be tweaked to use the new Published File manager.
=> fix publication display in task/DES-1133

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/services/published.service.js, designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.js
Added project awards to published project templates
Removed old project awards format from template (separate template for older publications)
Added project citation to published template
Disabled citation button in publication preview template
Updated published licenses for publication templates
=> Task/DES-1082 - Show published projects' citations and awards

designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
- Task/DES-965 - Give PI and Team Member sections a single row with two columns of inputs  
- Task/DES-1011, Task/DES-1012, Task/DES-1013 - Adjust white space around and within input boxes
- Task/DES-1017 - Display the Project Type under Title
- Task/DES-1024 - Adjust format of Awards and Related works
- Task/DES-1047 - Fix issue causing related works to not load
- Task/DES-1167 - Remove guest users with blank inputs
=> Task/DES-(multiple) - fix formatting and design issues with edit project modal

designsafe/apps/api/agave/views.py, designsafe/static/scripts/workspace/controllers/data-browser.js, designsafe/static/scripts/workspace/html/data-browser.html, designsafe/static/scripts/workspace/services/systems-service.js
- Also allows listing refresh by clicking on the root of the current browsed system
=> task/DES-133: Add community data to workspace browser; browsing fixes

designsafe/static/scripts/data-depot/components/projects/project-listing/project-listing.component.html
Adding in new column for PRJ number.  Also by Craig's request, removing the briefcase icon from the project name column.
=> DES-667: adding prj column to My Projects listing

designsafe/apps/api/notifications/tests.py, designsafe/apps/notifications/views.py, designsafe/apps/workspace/tasks.py, designsafe/apps/workspace/views.py, designsafe/static/scripts/notifications/html/badge.html, designsafe/static/scripts/workspace/controllers/jobs-status.js, designsafe/static/scripts/workspace/html/jobs-status.html, designsafe/static/scripts/workspace/services/apps-service.js, designsafe/static/styles/main.css
- Looks for active, non-terminal job for user before when handling interactive job webhooks
- Add job id to job modal
- Better visual styling for job modal messages
- Add a "Clear all notifications" button to bottom of notification bell
=> bug/DES-1182: Add interactive webhook security; various job notif improvements

designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.template.html
The "Saved" message will appear after saving the authors, and once the authors are saved a user can continue to publish. If they want to re-order their authors (by clicking the sort arrows) the "saved" message will go away until they click save again.
=> Task/DES-987 - Allow authors to be saved and reordered repeatedly in the pipeline

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html
Changing how Related Works are displayed
Example:
Google Reference | [http://www.google.com](http://www.google.com)
to
[Google Reference](http://www.google.com)
=> Task/DES-1117 - Change format of Related Works for Project and Analysis

designsafe/apps/projects/models/elasticsearch.py, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
Requesting a review from Jake to see if the changes on `elasticsearch.py` would work, or if anything else would be needed. I added an `order` field for associatedProjects and awardNumber.
=> Task/DES-866(867) - Keep order of awards and related work

designsafe/libs/elasticsearch/docs/publications.py, designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.public.template.html
=> Task/DES-1179 - Replace (other) with datatype if provided in published listing

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js
Fixed a bug with the way we conditionally make requests for missing project metadata.
=> Bug/DES-1201 - Fix bug causing publication preview to make redundant listings

designsafe/apps/data/templates/data/data_depot.html, designsafe/apps/data/views/base.py, designsafe/templates/base.html
Updating the `<title>` tag and `<meta name="desription">` tags for improved discoverability and SEO in Google.  
Fixing a small typo in `block google_citation_meta`.
=> task/DES-1187 - Update Meta Tags on Published Projects

designsafe/static/scripts/data-depot/components/files-listing/files-listing.public.template.html
Fix bug causing NEES tag in published listing to render incorrectly
=> Bug/DES-1205 - Fix bug with NEES tag in publication listing

designsafe/static/scripts/data-depot/components/projects/project-listing/project-listing.component.html
moved prj id column, added styles for column widths
=> task/des-1203: style changes for my projects column listing

designsafe/static/scripts/data-depot/components/published/published.component.html
=> Task/DES-1210 - Close dropdowns by default in older publication template

designsafe/apps/api/search/searchmanager/community.py, designsafe/apps/api/search/searchmanager/private_data.py, designsafe/apps/data/tasks.py, designsafe/apps/search/tasks.py, designsafe/celery.py, designsafe/libs/elasticsearch/utils.py, designsafe/settings/common_settings.py
Adds a recurring task to index Community Data. 
Also tweaks a couple of search queries to restrict the fields to search on.
=> task/DES-1211: Add recurring task for community data indexing

designsafe/static/scripts/data-depot/components/published/published-view.component.js
=> Bug/DES-1219 - Enable selection boxes for published area

package-lock.json, package.json
v4.11 is incompatible with newer versions of Node.
=> bug/DES-1206:  Update node-sass version.

designsafe/static/scripts/data-depot/components/dd-publication-listing/dd-publication-listing.template.html
Add FR checkbox to publication filters.
=> task/DES-1209: Add field recon to publication filter checklist

designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-experiment/pipeline-experiment.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-field-recon/pipeline-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-hybrid/pipeline-hybrid.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-other/pipeline-other.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-simulation/pipeline-simulation.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.component.js
Removed some unused window session storage code from the pipeline
=> Task/DES-1249 - Fix license selection clear button

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js
- Add award name and numbers back to published templates
- Add related works to FR publication preview
- Fix observation type order in dropdown for FR
- Hide referenced data if missing for FR
=> Task/DES-1237 & (1238, 1240, 1242, 1243) - Various template fixes for FR

designsafe/static/scripts/workspace/controllers/application-form.js
- add archiveOnAppError to job body
=> Archive job files from failed jobs

designsafe/settings/common_settings.py
Disable the middleware until we set up communications to users.
=> task/DES-758: disable profile update middleware for now

designsafe/apps/accounts/templates/designsafe/apps/accounts/base.html, designsafe/templates/includes/header.html
Removed notification preferences tab from Manage Account, since all email notifications are handled through mailman now.
Added Manage Account to user menu dropdown at top right.
=> task/DES-1128: notifications preferences updates

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js
Fixing some template issues for the Field Research publications...
=> Task/DES-1287 - Fix for Field Research Template

designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
- Fix add/remove field research
- Fix bug with add on related works
=> Task/DES-1212 - Fix add/remove natural hazard type from field research

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-field-recon/pipeline-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html
Swapped old `ds-user` directive for newer `ds-user-list` and `ds-author-list`.
=> Task/DES-1313 - Replace old user directive with new one for FR

designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.js, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
- update category listing when creating new categories
- formatting changes to collections/missions template for Field Research
=> Task/DES-1323 - Update listing for newly created categories

designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js
The save[entity] functions were not updating the part of the UI.
=> Task/DES-1325 - Fix update issue with primary entity creation

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html
- nhTypes if an array of strings provided by the user
=> Task/DES-1322 - Fix template to show nhTypes for field research projects

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html
Adding direct links to Curation FAQ section and DesignSafe Marker Paper in help dropdown.
=> Task/DES-1317 - Add links to help section dropdown

designsafe/static/scripts/rapid/styles/rapid.css
=> fix rapid logo height

designsafe/static/scripts/data-depot/components/files-listing/files-listing.public.template.html
Added PI names and link to description modal for NEES data using the metadata object
=> task/DES-1292: NEES data in publications browsing view

designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-field-recon/pipeline-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html
Removal of elevation as well as putting coordinates (latitude and longitude) on same line.
=> Task/DES-1314: Site Location (lat long) Formatting

designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html
Rate limit message in the data depot using bootstrap alert for Box and Google Drive
=> task/DES-1235: Improve data transfer messages in Data Depot

designsafe/apps/api/projects/views.py, designsafe/apps/api/tasks.py
set_project_id is called right before email_collaborators . 
email_collaborator_added_to_project has project_id as parameter
=> task/DES-1191: Add Project ID to Project Invitation E-mail

designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js
Uncheck author boxes after creating experiment/simulation/hybrid simulation using `ng-checked` directive with `user.authorship`.
=> Task/DES-1315: Check that authors are not pre-checked anywhere

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js
=> Task/DES-1312 - Show one data diagram with all entities in preview and published areas

karma.conf.js
d3plus is added to the karma.conf file
=> Bug/DES-1373: d3plus not defined in karma config

designsafe/apps/data/templates/data/data_depot.html, designsafe/apps/data/views/base.py
Tested with
- PRJ-1434 (Experimental)
- PRJ-1648 (Experimental)
- PRJ-2319 (Simulation)
- PRJ-2548 (Simulation)
- PRJ-2397 (Field Recon)
=> Task/DES-1255: Metatags for multiple citations

designsafe/apps/data/templates/data/data_depot.html, designsafe/templates/base.html
Added identifier as described in JIRA task as well as Dublin Core identifier tag.
=> Task/DES-1290: Add DOI information as identifier meta tag

designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js
`ng-model` for "Other" observations or instruments tied to an array of values input by user. When the form is submit, other is replaced by this value.
=> Task/DES-1316: Fix Mission Observation Type

designsafe/static/scripts/data-depot/components/projects/equipment-list.json
JSON file with equipment divided into arrays by type
=> Task/DES-1347: Create Equipment List JSON

designsafe/apps/api/notifications/tests.py
Fixes issue with old user model testing with notifications, and adds more coverage.
=> fix webhook unit tests

designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-image-preview/image-preview.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-image-preview/image-preview.component.spec.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-image-preview/image-preview.template.html, designsafe/static/scripts/ng-designsafe/components/modals/index.js, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/static/styles/base.scss
Image Previews modal using UIB-carousel
=> Task/DES-1266: Fix Image Carousel Preview

designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
**NOTICE: This should be merged with task/DES-1358**
=> Task/DES-1441 - Fix bug causing Edit Prj. Modal break upon selection of FR Model

designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-experiment.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-field-recon.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-hybrid.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-simulation.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-exp.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-field.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/scripts/projects/components/manage-field-recon/reports/manage-field-recon-reports.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html
Changing some of the labels from something like `Authors` to `Author(s)`.
=> Task/DES-1421 - Fix typos in templates

designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/ng-designsafe/services/project-service.js, designsafe/static/scripts/projects/components/project-tree/project-tree.component.js
Allow collections to be sortable among other collection types
Update UI to display sorted collections
Fixes to various bugs in the Data Diagram and UI
**TO BE MERGED WITH Task/DES-1358**
=> Task/DES-1435 - Allow inter-sorting of different collection types

designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-exp.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.template.html, designsafe/static/scripts/ng-designsafe/services/project-service.js
**MERGES WITH TASK/DES-1358**
- Update the project review method
- Checking before and after the publication pipeline to prevent issues
=> Task/DES-1413 - Update project review process in publication pipeline

designsafe/apps/projects/models/agave/rapid.py, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-field-recon.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-field.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/projects/components/file-categories/field-recon-file-tags.json, designsafe/static/scripts/projects/components/manage-field-recon/collections/equipment-list.json, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.js, designsafe/static/scripts/projects/components/project-tree/project-tree.component.js
**TO BE MERGED WITH TASK/DES-1358**
- Remove "Methods of Collection" Field from templates and forms
- Hide empty input fields in templates
- Remove requirement for Geolocation fields on all Collection types
- Add additional options to Social Science Equipment list
- Change name of Reports to Documents
- Add "Event" field to mission form
- Add additional file tags for Social Science collection
=> Task/DES-1440(1419, 1433, 1439) - Collections Form Revisions

designsafe/static/scripts/data-depot/components/projects/index.js, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-privacy-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
Adding Curation guidelines  for Field Research
=> Task/DES-1383 - Add Curation Guidelines for Field Research

designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js
This will be modified in the future, but for now we cannot allow users to intentionally or unintentionally overwrite their publications.
=> Task/DES-1412 - Make users submit a ticket to republish or overwrite their publications

designsafe/apps/api/agave/views.py, designsafe/apps/data/views/base.py
CSRF Token was being enforced for anonymous users viewing public file listings.
=> Task/DES-1466 - Allow anonymous users to download and preview public files

designsafe/apps/data/management/commands/swap_reindex.py, designsafe/libs/elasticsearch/indices.py
We had multiple `connections.configure` calls that were overwriting the "correct" default config.
=> task/DES-1480: Stop overwriting default Elasticsearch connection

designsafe/apps/data/templates/data/data_depot.html, designsafe/apps/data/views/base.py
Updated type attribute tag for Google Dataset Search, and tested against Google's [Data Structure Testing Tool](https://search.google.com/structured-data/testing-tool).  It should work now.
=> task/des 1225 - Google Dataset Search Tags

designsafe/apps/rapid/templates/designsafe/apps/rapid/admin.html, designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_event_add_dataset.html, designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_event_datasets.html, designsafe/apps/rapid/templates/designsafe/apps/rapid/admin_event_edit_dataset.html
Filter fix after elasticsearch upgrade
=> fix event meta id filter

designsafe/LoginTest.py, designsafe/apps/api/external_resources/dropbox/filemanager/manager.py, designsafe/apps/djangoRT/tests.py, designsafe/apps/djangoRT/views.py, designsafe/apps/dropbox_integration/tasks.py, designsafe/apps/licenses/models.py, designsafe/apps/projects/management/commands/check_entities_relations.py, designsafe/settings/ef_http_debug_settings.py, designsafe/settings/test_settings.py, designsafe/tests.py
a few more changes found via `2to3`
```2to3 -w -n -x future designsafe```
=> more python3 updates

designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-exp.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-exp.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-hyb-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-sim.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
The titles and arrow icons were not vertically centered or consistent for the colored content dropdown bars.
=> Task/DES-1489 - Fix vertical-alignment of dropdown bars for project area

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/index.js, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-other/pipeline-other.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-experiment.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-field-recon.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-hybrid.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-simulation.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-exp.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-hyb-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.template.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-popup.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/publication-download/publication-download.component.js, designsafe/static/scripts/projects/components/publication-download/publication-download.template.html, designsafe/static/styles/ng-designsafe.css, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css, package-lock.json
Created a "Publication Download" modal and updated a few of the templates. This should download any archive created for a publication or at least show an error message for the user to submit a ticket.
This can be tested locally if you have some published projects available in your index. Just make sure that the publication has an existing archive saved on corral. The path should look something like:
`/corral-repl/projects/NHERI/published/archives/PRJ-XXXX_archive.zip`
=> Task/DES-1552 - Download Published File Archives

designsafe/apps/api/agave/filemanager/publications.py, designsafe/libs/elasticsearch/docs/publications.py, designsafe/static/scripts/workspace/controllers/data-browser.js, designsafe/static/scripts/workspace/html/data-browser.html
The Data Browser in the Workspace now loads publications in the same order as they are displayed in the Data Depot.
=> Task/des-1350 - Changes to Workspace file listings

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/projects/components/publication-download/publication-download.template.html, designsafe/static/styles/ng-designsafe.css, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
**Added the following changes to templates and css:**
* Font size of "Download Dataset" text needs to be the same as a Bolded Project Metadata Hyperlink (Keep the icon the same size). This should increase the space for the title before it needs to wrap.
* Center the modal on the screen, it is skewed up
* Reduce spacing between Project Title and Project Metadata
* Properly align the text in the green Download button of the modal
* Top bar of modal should say "Download Dataset" instead of "Download"
* Make sure the spacing between the top bar of the modal and the first line of text(_"This download is a ZIP file..."_) is equal to the spacing between that first line of text and the delimiter line that separates the listing of licenses.
*SPECIFIC RULES FOR EACH LICENSE:*
Open Data Commons …
=> Task/DES-1600 - Update ui for download publication components

designsafe/apps/api/external_resources/box/filemanager/manager.py, designsafe/apps/api/external_resources/dropbox/filemanager/manager.py, designsafe/apps/applications/views.py, designsafe/apps/notifications/views.py, designsafe/apps/workspace/tasks.py, designsafe/apps/workspace/views.py
Exception.message was removed in python 3
=> hotfix: remove message attr ref from exception

designsafe/apps/data/templates/data/data_depot.html, designsafe/apps/data/views/base.py, designsafe/static/scripts/data-depot/index.js, designsafe/static/scripts/data-depot/services/published.service.js, designsafe/templates/base.html
Added block of meta tags using Dublin Core schema
=> Task/DES-1408: Dublin Core meta tags for Google Scholar citation

designsafe/apps/data/models/agave/files.py, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-move/data-browser-service-move.component.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-move/data-browser-service-move.component.js, designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-copy.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
These modals never had infinite scroll to begin with, so this PR implements them. 
Test by setting `this.offset` or `$scope.offset` to a small number.
=> task/DES-1650: Add infinite scroll to Data Depot move/copy modals.

designsafe/static/scripts/workspace/html/data-browser.html
The sort for objects in MyData in the Workspace Data Browser now matches the sort in the Data Depot.
=> task/DES-1670 - Update MyData in WorkSpace Data Browser to match Data Depot

designsafe/apps/api/agave/filemanager/publications_legacy.py, designsafe/apps/api/search/searchmanager/publications.py, designsafe/apps/api/search/searchmanager/publications_legacy.py, designsafe/apps/api/search/searchmanager/publications_site_search.py, designsafe/apps/api/search/views.py, designsafe/settings/common_settings.py, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search-checkbox.component.js, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search-checkbox.template.html, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search.component.js, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search.template.html, designsafe/static/scripts/data-depot/components/data-depot-listing/publications-listing.template.html, designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.js, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/components/index.js, designsafe/static/scripts/data-depot/index.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/simulation-types.json
- Add advanced search table with filters/queries.
- Split NEES publications into a separate Data Depot tab.
=> task/DES-628: Advanced Search for Publications

README.md
More updates to the README after noticing some more missing and out of date information.
=> DES-1746: more README updates

designsafe/apps/projects/models/elasticsearch.py, designsafe/templates/base.html, package-lock.json, package.json, webpack.config.js
- Bump Webpack version to ^4.43.0 so that new dependencies can be bundled
- Switch to using minified AngularJS
- Add missing fields to `IndexedProject` Elasticsearch schema
=> Small Fixes for 5.0.0 Release

package-lock.json, package.json, webpack.config.js
Needed in order to get the pipeline and webpack-build both to run.
=> roll back Webpack and geojson-validation versions

designsafe/apps/api/projects/views.py
A missing immutable signature in the celery task chain for publication steps was missing and causing the pipeline to fail. I've ran the entire task chain and ensured that everything should work now.
* [DES-1784](https://jira.tacc.utexas.edu/browse/DES-1784)
Added signature to task in chain
=> Bug/DES-1784 - Add signature to e-mail task in publication chain

designsafe/static/scripts/workspace/components/workspace-data-browser/workspace-data-browser.component.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
* [DES-1712](https://jira.tacc.utexas.edu/browse/DES-1712)
Include project title in breadcrumbs.  Expand the PRJ Id's column and wrap the project titles, so that each row is more readable.  Make sure that the Workspace data browser matches what is shown in the Data Depot.
1. Check to make sure that Data Depot matches what is show in the Workspace data browser
2. Look to make sure that any long project titles are wrapping and readable in the Workspace data browser
3. Make sure the PRJ Id's are not wrapping in the Workspace data browser
4.  Make sure the the Workspace data browser is readable and doesn't require horizontal scrolling
Attached to the ticket.
=> Task/DES-1712 - Improve file listing in Workspace

designsafe/apps/api/publications/operations.py, designsafe/apps/api/publications/search_utils.py, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search.component.js
Tweak the facilities filter so that all relevant pubs are returned.
* [DES-1818](https://jira.tacc.utexas.edu/browse/DES-1818)
=> Bug/DES-1818: expand facilities filter to cover V1 and V2 pubs

designsafe/static/scripts/workspace/components/workspace-data-browser-project-listing/workspace-data-browser-project-listing.template.html, designsafe/static/scripts/workspace/components/workspace-data-browser/workspace-data-browser.component.js
* [DES-1712](https://jira.tacc.utexas.edu/browse/DES-1712)
Include project title in breadcrumbs. Expand the PRJ Id's column and wrap the project titles, so that each row is more readable. Make sure that the Workspace data browser matches what is shown in the Data Depot.
1. Check to make sure that Data Depot matches what is show in the Workspace data browser
2. Look to make sure that any long project titles are wrapping and readable in the Workspace data browser
3. Make sure the PRJ Id's are not wrapping in the Workspace data browser
4. Make sure the the Workspace data browser is readable and doesn't require horizontal scrolling
5. Make sure the the Workspace data browser dropdown labels match the side navbar in the Data Depot.
=> task/DES-1712 -  Improve file listing in Workspace

designsafe/apps/projects/models/agave/base.py, designsafe/static/scripts/ng-designsafe/services/publication-service.js
=> hotfix: handle exception when looking for licenses in legacy publications

designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search.template.html
Fix a typo preventing the "event type" query from being included in the search.
* [DES-1781](https://jira.tacc.utexas.edu/browse/DES-1781)
Perform a search for "Harvey" under the "Natural Hazard Event" field in the advanced search. Only a couple results should come up.
=> bug/DES-1781: Fix natural hazards event searches

designsafe/apps/projects/models/agave/base.py
Resolving Google Dataset Search tag errors.
* [DES-1821](https://jira.tacc.utexas.edu/browse/DES-1821)
Corrected datatypes for Licenses, Creators, and includedInDataCatalog for Google Dataset Search.
1. Check errors on https://search.google.com/search-console/datasets?resource_id=sc-domain%3Adesignsafe-ci.org&hl=en with DesignSafe Google API credentials
2. Check structured data on Google's Structured Data tool: https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=code
=> task/DES-1821 - Fixed tags for Google Dataset Search

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html
There was some missing template code preventing the Awards field from rendering in the template.
* [DES-1833](https://jira.tacc.utexas.edu/browse/DES-1833)
=> Bug/DES-1833 - Render awards on published hybrid simulations

designsafe/static/scripts/projects/components/project-tree/project-tree.component.js
- Added the entity tag names before their title in the related entity tree.
- Fixed a UI bug causing reused entities to be misaligned.
* [DES-1102](https://jira.tacc.utexas.edu/browse/DES-1102)
1. Go to a project in the projects area and open the relationship tree. You should see some sort of "[entity type] | [entity title]" label at the root of each relationship tree.
**BEFORE**
**AFTER**
=> Task/DES-1102 - Entity Relationship Tree Fixes

designsafe/apps/api/datafiles/handlers.py
This fixes the wrong message was appearing for users when prompted to connect their Google Drive accounts.
=> fix Google Drive connection message

designsafe/static/scripts/ng-designsafe/services/file-listing-service.js
Fix some issues that cause publication previews to fail to render.
* [DES-1846](https://jira.tacc.utexas.edu/browse/DES-1846)
- Group abstract listing requests into sets of 5 Tapis requests staggered by 0.5 seconds
- Add exception handling so that failed requests fail silently instead of blocking the UI.
1. Navigate to a project with a large number of curated files.
=> task/DES-1846: Throttle abstract listing requests and handle exceptions

designsafe/static/styles/main.css, designsafe/templates/includes/header.html
* [DES-1881](https://jira.tacc.utexas.edu/browse/DES-1881)
=> task/DES-1881: Open social media links in new tab

designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-changes.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.component.js, designsafe/static/scripts/data-depot/index.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
* [DES-1902](https://jira.tacc.utexas.edu/browse/DES-1902)
1.
=> Task/DES-1902 - Set up calls to back end for publication pipeline for versioning/amends

designsafe/static/scripts/projects/components/manage-field-recon/collections/equipment-list.json
* [DES-1844](https://jira.tacc.utexas.edu/browse/DES-1844)
Updated equipment list as per request, spreadsheet attached to jira task
1.
=> DES-1844: updated fr equipment list

designsafe/apps/api/projects/urls.py, designsafe/apps/api/projects/views.py, designsafe/apps/api/tasks.py, designsafe/apps/data/models/elasticsearch.py, designsafe/apps/projects/managers/publication.py, designsafe/apps/projects/models/agave/base.py, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-other.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-other.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-changes.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/ng-designsafe/services/publication-service.js, designsafe/static/scripts/projects/components/manage-project/amend-project.template.html, designsafe/static/scripts/projects/components/manage-project/manage-project.template.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
This PR is meant to complete the Amend and Revision pipelines. The process of amending and versioning a project is mostly complete.
* [DES-1902](https://jira.tacc.utexas.edu/browse/DES-1902)
**NOTE: File copying and directory creation is not currently testable from the Dev environment. This may be possible to test in Staging though. If you plan to submit any dev project for publication, revision, or amendments please DM me on Slack with the correct designsafe.env settings to use. I'm open to have some group testing on this**
1. Navigate into an "other" project that has files.
2. Go to the "Prepare to Publish" section.
- From this section you should be able to see options for revise or amend if your "other" project is published. If it is not, you can still access these through the browser …
=> Task/DES-1902 - Connect endpoints for versioning and amends

designsafe/apps/api/tasks.py
=> Change pipeline copy function to use BaseESPublication

designsafe/apps/api/publications/operations.py, designsafe/apps/api/tasks.py, designsafe/static/scripts/data-depot/components/data-depot-listing/data-depot-listing.component.js
This is a change to the Amends/Versions feature branch to redirect the publications in the published listing to the latest version.
* [DES-1966](https://jira.tacc.utexas.edu/browse/DES-1966)
=> Task/DES-1966 - Redirect to Current Version of Publication

designsafe/apps/api/projects/urls.py, designsafe/apps/api/projects/views.py, designsafe/apps/api/publications/operations.py, designsafe/apps/api/publications/urls.py, designsafe/apps/api/tasks.py, designsafe/apps/data/urls.py, designsafe/apps/projects/managers/publication.py, designsafe/static/scripts/data-depot/components/data-depot-listing/data-depot-listing.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-changes.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-project.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
This changes the publication version iterator for published projects. The 'r' in `PRJ-1234r1` is now being replace with a 'v' and the iterator starts at 2 now. Now, when a publication is versioned for the first time you will see `PRJ-1234v2` 
* [DES-1978](https://jira.tacc.utexas.edu/browse/DES-1978)
1. Publish a new version of an Other project and you should see these changes. (make sure that it has not been versioned previously)
=> Task/DES-1978-1974 - Modify versioning iterator and change versioning process

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js
Fixes HazMapper routes dynamically based on prod/staging.
* [DES-1994](https://jira.tacc.utexas.edu/browse/DES-1994)
Changes hazmapper link for frontend file listing preview modal to be dynamic based on staging/prod.
1. Make sure that staging/prod links route to corresponding hazmapper staging/prod.
=> Bug/DES-1994 - Make the hazmapper route dynamic.

designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.js
This should fix an issue with older publications which are missing certain fields. That being said, this component needs to be cleaned up a bit.
* [DES-1992](https://jira.tacc.utexas.edu/browse/DES-1992)
1. Go to [this publication](https://designsafe.dev/data/browser/public/designsafe.storage.published/PRJ-1444) before pulling this and confirm that you see an error message when opening the modal.
2. Visit the page again from this branch and ensure the changes correctly render the authors in the modal.
=> Bug/DES-1992 - hotfix for citation modal regarding early publications

designsafe/apps/api/publications/operations.py, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/projects/components/publication-metrics/publication-metrics.template.html
Metrics and searchbar UI updates
* [DES-1943](https://jira.tacc.utexas.edu/browse/DES-1943)
- Don't use default ES client for publication listings (prevent 10s load times)
- Update Metrics modal according to new requirements
- Replace "find in Data Depot" with "find in this Dataset" when searching inside of a publication
=> Task/des 1943: Metrics and searchbar UI updates

designsafe/libs/fedora/fedora_operations.py
=> Fedora/upload-files: Add toggle to allow ingesting projects without files

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js
=> hotfix/pdf-preview: Avoid sameorigin error in PDF preview by downloading in browser

designsafe/libs/fedora/fedora_operations.py
Previously all files were being uploaded to Fedora as children of the base publication container. This was causing updates to time out since publications can have a massive number of files associated to them and Fedora doesn't support pagination. The solution is to put files in a "data" container that will never need to be updated (since anything that updates files is by definition a revision and will create a new archive).
1.
=> Fedora: Make files children of a data container instead of the base publication

designsafe/apps/workspace/tasks.py
Remove atomic blocks around job notification transactions so that we don't run into database locking issues.
* [DES-2020](https://jira.tacc.utexas.edu/browse/DES-2020)
=> task/DES-2020: Fix job webhook notifications

designsafe/apps/workspace/tasks.py
=> Task/des 2020: Remove select_for_update calls outside of transaction blocks.

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html
Updating one of the Help menu items in the Data Depot
* [DES-1469](https://jira.tacc.utexas.edu/browse/DES-1469)
Updated menu item
1.  Go to the Data Depot and check that the Help menu at the bottom of the left menu has the correct text.
=> DES-1469: updating help menu text item

designsafe/apps/api/projects/views.py, designsafe/apps/data/models/elasticsearch.py
* [DES-2028](https://jira.tacc.utexas.edu/browse/DES-2028)
1.
=> task/DES-2028: Use a new ES client for publication detail views.

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js, designsafe/static/scripts/ng-designsafe/services/file-operation-service.js
* [DES-1904](https://jira.tacc.utexas.edu/browse/DES-1904)
1. Preview a notebook in the Publications section and make sure it doesn't 404.
=> bug/DES-1904: Fix param unpacking in Jupyterhub URL formatting

designsafe/static/scripts/projects/components/publication-metrics/publication-metrics.template.html
Wording Hotfix required for by Maria and others for upcoming review.
* [DES-2057](https://jira.tacc.utexas.edu/browse/DES-2057)
=> Task/DES-2057 - Change wording of field in published data metrics

designsafe/apps/nco/managers/projects.py, designsafe/apps/nco/templates/designsafe/apps/nco/nco_index.j2, designsafe/libs/mongo/load_projects.py, designsafe/static/scripts/nco/components/nco-scheduler-filters/nco-scheduler-filters.component.js, designsafe/static/scripts/nco/components/nco-scheduler-filters/nco-scheduler-filters.template.html, designsafe/static/scripts/nco/components/nco-scheduler-list/nco-scheduler-list.scss, designsafe/static/scripts/nco/components/nco-scheduler-list/nco-scheduler-list.template.html
Updates to the NCO scheduling app main page located at https://designsafe-ci.org/nco to replace the prototype design and the fake sample dataset with a simple set of real project data from actual grants.  Boilerplate text and links relevant to facility scheduling is added to clarify the purpose for users as well as additional columns and updated filters & sorts within the data table.
* n/a
* Adding text to app's primary page.
* Changing styling to match other areas of the DS website.
* Switching the data table to pull from a set of real project data.
* Updating Angular components of the data table and python code to support additional columns for the real dataset.
* Updating the filters and sorts to match the real datasets.
1. Visit the app page at /nco
2. Confirm the table is loading …
=> Update NCO scheduling app

designsafe/static/scripts/notifications/html/notification_list.html, designsafe/static/styles/main.css
Added a style to the Notifications page for the Raw Message box to fix formatting
* [DES-2005](https://jira.tacc.utexas.edu/browse/DES-2005)
1. View the Notifications page by clicking the Notifications bell icon and clicking View All.
2. Check Raw Messages by clicking "Click to view" and confirm that none of the Raw Messages overflow the box.
=> DES-2005: Notifications Page Updates

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html
Change Co-Pi formatting and match license text in publishing process to cms page
* [DES-2050](https://jira.tacc.utexas.edu/browse/DES-2050)
* [DES-2051](https://jira.tacc.utexas.edu/browse/DES-2051)
=> Task/DES-2050 & 2051 Co PI formatting and license text changes

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/projects/components/publication-download/publication-download.template.html
Change the wording of Download Dataset and DOIs in Dataset to Project.
* [DES-1636](https://jira.tacc.utexas.edu/browse/DES-1636)
1. Hop into some published projects on DesignSafe and check that the wording has been updated
=> Task/DES-1636 - Change "Dataset" to "Project" in published templates

designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js, designsafe/static/scripts/ng-designsafe/services/file-listing-service.js
The microsurvey should now correctly send the project ID to the backend in all cases.
=> fix missing project IDs in microsurvey

designsafe/apps/nco/managers/projects.py, designsafe/apps/nco/templates/designsafe/apps/nco/nco_index.j2, designsafe/static/scripts/nco/components/nco-scheduler-filters/nco-scheduler-filters.component.js, designsafe/static/scripts/nco/components/nco-scheduler-list/nco-scheduler-list.template.html
Minor filter changes, changes to introductory text, and tweaks to data displayed in table.
1.
=> Updated NCO app slightly based on feedback from NSF and test users.

designsafe/apps/api/datafiles/views.py, designsafe/apps/api/projects/views.py, designsafe/apps/api/utils.py, designsafe/apps/applications/views.py, designsafe/settings/common_settings.py
Add IP and user agent logging to metrics logging.
* [DES-2091](https://jira.tacc.utexas.edu/browse/DES-2091)
- Add utility to extract IP from user requests (https://stackoverflow.com/a/5976065)
- Update logging template to catch the IP and user agent.
1. perform file operations in the Data Depot and check that the [METRICS] logs in Docker contain the IP address and user agent (the IP will probably be wrong in local dev due to the way Docker Desktop handles networking, but I've confirmed that `request.META['REMOTE_ADDR']` has the correct value in our deployed environments.)
=> Log IP address and user agent in metrics

designsafe/static/scripts/projects/components/publication-metrics/publication-metrics.template.html
* [DES-2094](https://jira.tacc.utexas.edu/browse/DES-2094)
With metrics: 
Without metrics:
=> Task/DES-2094: hide last-updated time for metrics that don't exist

designsafe/templates/includes/header.html
CMD requests we update the designsafe youtube link.
* [DES-2126](https://jira.tacc.utexas.edu/browse/DES-2126)
=> task/DES-2126: Update youtube link

designsafe/apps/api/datafiles/handlers.py, designsafe/apps/api/datafiles/operations/agave_operations.py, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js
Add logging when users expand primary entities
* [DES-2077](https://jira.tacc.utexas.edu/browse/DES-2077)
1. Go to a non-Other publication and expand a primary entity (experiment/mission/simulation).
2. Check the Django logs in docker for a "loglisting" operation with the DOI of that entity in the path.
=> task/DES-207: Add logging when users expand primary entities

designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.template.html
* [DES-1843](https://jira.tacc.utexas.edu/browse/DES-1843)
Added extra item to publishing section on curation start page
Only shows up if the project does not have amends/versioning available
1. Go to a project that does have amends/versioning and confirm that the fourth bullet item is not there
2. Go to a project that does not have amends/versioning and confirm that the fourth bullet item is there
=> DES-1843: adding new item to publishing section on curation start page

designsafe/static/scripts/data-depot/components/projects/publication-preview/modals/author-information-modal.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js
Allow users to view author modals for PIs and Co-PIs
* [DES-1483](https://jira.tacc.utexas.edu/browse/DES-1483)
=> Task/DES-1483: Display Author Modal for PIs and Co-PIs

designsafe/static/scripts/data-depot/components/projects/index.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/publication-metrics/entity-metrics.component.js, designsafe/static/scripts/projects/components/publication-metrics/entity-metrics.template.html, designsafe/static/scripts/projects/components/publication-metrics/publication-metrics.component.js, designsafe/static/scripts/projects/components/publication-metrics/publication-metrics.template.html
Implements new UI from task DES-2189
* [DES-2189](https://jira.tacc.utexas.edu/browse/DES-2189)
- Updates metrics UI to distinguish total vs unique views.
- Adds an "entity metrics" component to show metrics for any entity with a DOI
1. Click on "View Data Metrics" within a project published at least a month ago
2. Open a primary entity in each of Experimental, Simulation, Hybrid Sim and Field Recon, and make sure that each type has a working Data Reuse popup.
=> (DES-2189 and DES-2078) Update Make your Data Count metrics/Add individual entity views

designsafe/static/scripts/projects/components/publication-metrics/entity-metrics.template.html, designsafe/static/scripts/projects/components/publication-metrics/publication-metrics.template.html
=> task/DES-2189--design-update: move MYDC metrics to bottom of modal

designsafe/apps/api/tasks.py, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
This fixes a bug with versioned projects' breadcrumbs and the indexer.
* [DES-2250](https://jira.tacc.utexas.edu/browse/DES-2250)
The iterator for versioned projects used to be prefixed with an 'r' like PRJ-1234r2 But we changed this to 'v'. We need to fix a couple typos related to the indexer and some breadcrumbs that are still looking for this 'r'
=> Bug/DES-2250 - Fix bug with versioning iterator

designsafe/apps/projects/managers/publication.py, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.js, designsafe/static/scripts/projects/components/publication-citation/publication-citation.template.html, designsafe/static/scripts/projects/components/publication-download/publication-download.template.html
- There's a bug causing licenses to not be set on publications and this is causing the publication view to fail when accessed directly.
- Need to pass version details of previous publications to DataCite (other only)
- Need to include the version number within the Citation Modal that pops up next to the DOI on published materials.
* [DES-2282](https://jira.tacc.utexas.edu/browse/DES-2282)
=> Bug/DES-2282 - Version and Licence Fixes for DataCite

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.html
Remove the "Open In Jupyter" button in file previews.
* [DES-2331](https://jira.tacc.utexas.edu/browse/DES-2331)
=> Remove Open In Jupyter button in file previews.

designsafe/apps/api/projects/views.py, designsafe/libs/elasticsearch/docs/publications.py, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend-citation.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend-other.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-other/pipeline-other.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-experiment.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-field-recon.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-hybrid.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-primary-entity.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-primary-entity/pipeline-simulation.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-exp.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-field.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-hyb-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-sub-entity/pipeline-sub-entity-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.component.js
This PR fixes an important bug which prevents Experimental projects from being able to Amend properly. This PR also contains some wording changes and bug fixes related to the display of custom metadata fields for Experimental projects.
* [DES-2322](https://jira.tacc.utexas.edu/browse/DES-2322)
1. Removed warning text from publication pipeline "You cannot change this publication once published"
2. Fixed custom metadata fields for Experiments in the publication and versioning pipelines
3. Fixed several bugs which prevented an Experiment project from being amended if a non required entity was omitted. 
1. Go into the publication pipeline for an Experimental project
2. Check that the warning text "You cannot make changes after publishing." no longer displays
3. Check that the custom fields …
=> Bug/DES-2322 - Bugfixes for experimental amends and projects

designsafe/apps/projects/managers/publication.py, designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-preview-metadata-template.html
Remove empty date fields from publication obj prior to indexing
* [DES-2357](https://jira.tacc.utexas.edu/browse/DES-2357)
=> Bug/DES-2357 - Remove empty date fields from publication obj prior to indexing

designsafe/static/scripts/data-depot/components/projects/index.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-citation.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-experimental.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-field-recon.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend-citation.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.component.js, designsafe/static/scripts/data-depot/index.js
Frontend work for FR Amends
* [DES-2293](https://jira.tacc.utexas.edu/browse/DES-2293)
Frontend work for FR Amends
1. 
Edit Mission/Document modals not available yet
=> DES-2293: FR Amends Frontend

designsafe/libs/fedora/fedora_operations.py, designsafe/libs/fedora/fr_operations.py, poetry.lock, pyproject.toml
Add fedora formatting/ingest methods for field recon.
=> fedora/fr-operations: Add fedora formatting/ingest methods for field recon

designsafe/static/scripts/data-depot/components/projects/fixtures/project-entities-expt.json, designsafe/static/scripts/data-depot/components/projects/fixtures/project-expt.json, designsafe/static/scripts/projects/components/manage-experiments/experimental-data.json
Updating facility name as requested
* [DES-2337](https://jira.tacc.utexas.edu/browse/DES-2337)
1. 
We will need to update the two publications with the old name to use the new name as well.
=> DES-2337: updating facility name

designsafe/apps/projects/models/agave/base.py, designsafe/apps/projects/models/agave/experimental.py, designsafe/apps/projects/models/agave/hybrid_simulation.py, designsafe/apps/projects/models/agave/rapid.py, designsafe/apps/projects/models/agave/simulation.py, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-field-recon/documents/manage-field-recon-documents.component.js, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js
* [DES-2115](https://jira.tacc.utexas.edu/browse/DES-2115)
Fixed the case sensitive variables for sending Related Work info to DataCite
The Manage Experiment/Mission/FR document/etc modals should all now have 3 options in the dropdown for Related Work rather than the existing 2.
1.
=> DES-2115 Updates

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js
* [DES-2466](https://jira.tacc.utexas.edu/browse/DES-2466)
Added flag to change the url for the file preview modal for hazmapper depending on whether it is being viewed from published or from the project.
1.
=> DES-2466: Preview Modal Hazmapper Updates

designsafe/apps/accounts/templates/designsafe/apps/accounts/manage_auth.html, designsafe/apps/accounts/templates/designsafe/apps/accounts/password_reset.html, designsafe/apps/accounts/templates/designsafe/apps/accounts/register.html
* [DES-2473](https://jira.tacc.utexas.edu/browse/DES-2473)
Updating urls that referenced portal.tacc to point to the new accounts.tacc for password reset and account creation
1. Go to /register and make sure the link goes to accounts.tacc
2. Go to /account/password-reset and make sure the password reset link goes to accounts.tacc
3. After logging in, go to account management and make sure that the password page has the link to accounts.tacc
=> DES-2473: Updating links to new TUP

designsafe/static/scripts/projects/components/amend-entity-modal/amend-entity.template.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.template.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/documents/manage-field-recon-documents.template.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.template.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.template.html, designsafe/static/scripts/projects/components/manage-project/amend-project.template.html, designsafe/static/scripts/projects/components/manage-project/manage-project.template.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.template.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
Added audits to description field to make sure they're compatible with Google Dataset. 
* [DES-2474](https://jira.tacc.utexas.edu/browse/DES-2474)
All description fields should be limited to between 50 and 5000 characters. Added an error message and instructions for the user. Involves a field audiy using Angularjs, and a message that is shown and hidden depending on whether it passes or fails. Also has a new CSS class
1. Go to a DesignSafe project
2. Edit the description to be less than 50 characters and then more than 5000 characters, check to make sure you are unable to save the change and that an error message is displayed. (see UI photo)
3. Add or edit an entity (experiement/simulation/etc).  Edit the description to be less than 50 characters and then more than 5000 characters, check …
=> task/2474 - Google Dataset Compatibility

conf/nginx/error.html, designsafe/apps/api/templates/designsafe/apps/api/agave/preview.html, designsafe/apps/api/templates/designsafe/apps/api/box/preview.html, designsafe/apps/api/templates/designsafe/apps/api/data/agave/preview.html, designsafe/static/nbviewer/lib/scaffold.html, designsafe/static/vendor/httpi/example/index.htm, designsafe/static/vendor/js-custom-select/index.html, designsafe/templates/base.j2, designsafe/templates/cms_homepage.html, designsafe/templates/ef_base.html, designsafe/templates/ef_cms_page.html
Assign language `en-US` to all pages.
* [DES-2486](https://jira.tacc.utexas.edu/browse/DES-2486)
1. Verify pages _that use different base templates[^1]_ all have `<html lang="en-US">` e.g.:
- homepage
- portal
- ?
[^1]: I do not know what they all are on DesignSafe.
Skipped.
=> fix(a11y): DES-2486 html lang en-US

designsafe/static/scripts/navbar.js, designsafe/templates/includes/navigation.html
* [DES-2326](https://jira.tacc.utexas.edu/browse/DES-2326)
1.
=> task/DES-2326: Add selector for site search vs dataset search

designsafe/static/scripts/data-depot/components/data-depot-listing/publications-listing.template.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html, designsafe/static/scripts/rapid/html/rapid-admin-users.html, designsafe/static/scripts/search/components/search/search.component.html, designsafe/templates/includes/navigation.html
Resolve missing search form information:
- button text
- input label
- form role
* [DES-2475](https://jira.tacc.utexas.edu/browse/DES-2475)
* [DES-2484](https://jira.tacc.utexas.edu/browse/DES-2484)
* [DES-2485](https://jira.tacc.utexas.edu/browse/DES-2485)
1. Verify I know how to write HTML and follow directions…
Skipped.
=> fix(a11y): DES-2475, DES-2484, DES-2485 search form

designsafe/apps/api/tasks.py, designsafe/libs/fedora/fedora_operations.py, designsafe/libs/fedora/sim_operations.py
Add Fedora ingest pipeline for Simulations.
=> Add Fedora ingest for simulations

designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-preview-metadata-template.html
Other type projects were missing this field.
=> Add citation count to Other type pubs

designsafe/apps/api/users/views.py
Before showing user details to an unauthenticated client, check Elasticsearch to see if the user is an author on any publications. Only publication authors should have their user details be a matter of public knowledge.
* [DES-2547](https://jira.tacc.utexas.edu/browse/DES-2547)
=> DES-2547: Restrict user details available to unauthenticated users

designsafe/static/scripts/data-depot/components/modals/nees-doi-list.component.js
Filter experiments in the DOI modal to only show valid DOIs.
* [DES-2572](https://jira.tacc.utexas.edu/browse/DES-2572)
=> bug/DES-2572: filter NEES experiments to ensure we only show valid DOIs

designsafe/apps/accounts/templates/designsafe/apps/accounts/register.html
Add a blurb to the account registration page outlining our policies around Countries of Concern.
* [DES-2584](https://jira.tacc.utexas.edu/browse/DES-2584)
1. Navigate to https://designsafe.dev/account/register/
=> task/DES-4584 (point 2): Add message to registration page dealing with countries of concern

designsafe/apps/search/search_indexes.py
Hotfix for an issue causing site search to break.
=> bug/DES-2591: Hardcode URLs in the CMS indexer to fix deprecated page.site variable

designsafe/apps/auth/tasks.py
Created a new app that runs on frontera to set acls on user scratch dir, and implemented that here.
New setfacl app for frontera scratch: https://bitbucket.org/taccaci/portal-agave-templates/src/master/designsafe/applications/setfacl_frontera_scratch/
* [DES-2604](https://jira.tacc.utexas.edu/browse/DES-2604)
1.  With a new test user, login for the first time
2. Confirm that both your `/data/designsafe/mydata/$username` and `/scratch1/00849/tg458981/designsafe-scratch/${username}` dirs have proper acls set
=> bug/DES-2604: Run acls on frontera app for user scratch dir

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.js, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/workspace/components/workspace-data-browser/workspace-data-browser.component.js
Implement stakeholder request to use "HPC Scratch" as the label for the Frontera scratch area.
* [DES-2599](https://jira.tacc.utexas.edu/browse/DES-2599)
=> task/DES-2599: Change scratch space label to HPC Scratch

conf/docker/docker-compose-dev.all.debug.yml, conf/nginx/nginx.debug.conf
With these changes in a local dev environment, media can be synced from staging using:
`rsync -a -r <username>@designsafeci-dev.tacc.utexas.edu:/srv/www/designsafe/media/ <path/to/repo>/data/media`
=> Update local dev conf to serve media files

designsafe/templates/base.j2
Migrates snippet code to open links in a new window. The code should apply in AngularJS-managed pages now.
* [DES-2607](https://jira.tacc.utexas.edu/browse/DES-2607)
=> Open external sites in new window universally

designsafe/static/scripts/data-depot/components/data-depot-listing/data-depot-listing.component.js, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-copy/data-browser-service-copy.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js, designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-collections-template.html, designsafe/static/scripts/ng-designsafe/services/file-operation-service.js
Fix bugs where undefined DOIs were being logged with operations on files in publications.
* [DES-2610](https://jira.tacc.utexas.edu/browse/DES-2610)
- Add DOI logging for copy operations
- Fix DOI logging on browse/preview
=> task/DES-2610: Fix undefined DOI being logged with copy and other operations

poetry.lock, pyproject.toml
Add Pydantic and NetworkX as dependencies for use in managing projects/publications.
* [DES-2612](https://jira.tacc.utexas.edu/browse/DES-2612)
=> task/DES-2612: Add Pydantic and NetworkX dependencies

designsafe/apps/data/apps.py
Implements the Urllib3 keepalive solution from https://github.com/elastic/elasticsearch-py/issues/966#issuecomment-819823632
=> Configuration: Use TCP keepalive for Elasticsearch connection

designsafe/apps/googledrive_integration/templates/designsafe/apps/googledrive_integration/privacy-policy.html
=> Add read-only language to the privacy policy

designsafe/apps/projects/models/agave/base.py, designsafe/apps/projects/models/agave/experimental.py, designsafe/apps/projects/models/agave/hybrid_simulation.py, designsafe/apps/projects/models/agave/rapid.py, designsafe/apps/projects/models/agave/simulation.py
Only add funding sources if we know the funder name (for now `NSF-` implies National Science Foundation). 
TODO: Add a dropdown for the name so users are required to include it.
* [DES-2639](https://tacc-main.atlassian.net/browse/DES-2639)
=> bug/DES-2639: Don't add awards to datacite JSON if funder name is unknown

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-copy/data-browser-service-copy.component.js, designsafe/static/scripts/ng-designsafe/services/file-listing-service.js
Add HPC Work to copy modal dropdown.
* [DES-2665](https://tacc-main.atlassian.net/browse/DES-2665)
1. Copy a file from My Data to HPC Work
=> task/DES-2665: Add HPC Work to copy modal dropdown

designsafe/apps/api/datafiles/handlers.py, designsafe/apps/api/datafiles/operations/shared_operations.py, designsafe/apps/api/datafiles/operations/tapis_operations.py, designsafe/apps/api/datafiles/operations/transfer_operations.py, designsafe/apps/api/datafiles/views.py
Set up working V3 file listings ahead of the des-next deploy.
=> TV3/v3-file-listing: Add V3 file operation module and file listing util

conf/docker/Dockerfile, conf/docker/docker-compose-dev.all.debug.m1.yml, conf/docker/docker-compose-dev.all.debug.yml
- Add explicit rabbitmq image tags
- combine python-base and builder-base steps in Docker image build
=> docker-compose fix; combine python-base and builder-base steps

designsafe/static/styles/app-card.css
Remove styles in "app card" that were only for layout on outdated test page.
* Hold.
* [DES-2725](https://tacc-main.atlassian.net/browse/DES-2725)
- **added** `.app-card` stylesheet
See #1195.
See #1195.
Uses structural CSS from Core-Styles, then adds DesignSafe-specific skin CSS.
=> chore: DES-2725 remove unused code

designsafe/apps/api/projects_v2/operations/_tests/project_meta_unit_test.py, designsafe/apps/api/projects_v2/operations/project_meta_operations.py, designsafe/apps/api/projects_v2/views.py
Add a method for changing project type; add a test case
* [DES-2733](https://tacc-main.atlassian.net/browse/DES-2733)
Added a PUT method of the ProjectInstanceView that updates the project type 
Added change_project_type function to project_metadata_operations.py
Added a unit test for changing project type
1. run docker exec -it des_django pytest designsafe
2. verify test_change_project_type unit test passes.
=> Add change_project_type function and test cases

designsafe/apps/workspace/templates/designsafe/apps/workspace/app_card.html, designsafe/static/styles/app-card.css, designsafe/static/styles/app-page.css
Fix final (I hope) UI bugs on Tools & Apps page.
* Hold.
* [DES-2471](https://tacc-main.atlassian.net/browse/DES-2471): CMS: No List for Tag-less Apps
* [DES-2472](https://tacc-main.atlassian.net/browse/DES-2472): CMS: Update CSS Since Icon Class Rename
* [DES-2473](https://tacc-main.atlassian.net/browse/DES-2473): CMS: Container Too Wide
* https://github.com/TACC/Core-Styles/pull/343
1. Verify a card with no list does not show an empty gray stripe in the middle of the card.
2. Verify icon is:
- slightly bigger than title
- [aligns with the baseline](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align) of the title text
- has about a space character of width between it and title text
3. Verify container aligns left and right with logo/nav header content.
| …
=> fix: DES-2471, DES-2472, DES-2473 bugs

designsafe/static/styles/app-card.css, designsafe/static/styles/main.css
Styles for app card hover and focus.
* Hold.
* [DES-2744](https://tacc-main.atlassian.net/browse/DES-2744)
- **added** styles for app card hover and focus UX
- **added** common color as a CSS custom property
1. Hover over app card.
2. Click on app card and hold and move off and release.
3. Click on app card and release.
4. Verify no ugly UI.
5. Verify each state is unique.
https://github.com/DesignSafe-CI/portal/assets/62723358/58b1bd37-f228-4d05-9598-2a8c2caef99c
=> hotfix: des-2744 app card hover UI/UX

README.md, conf/docker/docker-compose-dev.yml, conf/docker/docker-compose.yml
Update Readme for local build.
Remove deprecated `version` in docker-compose
=> hotfix/update build info in README.md

client/modules/_hooks/src/notifications/index.ts, client/modules/_hooks/src/notifications/useNotifications.ts, client/modules/_hooks/src/workspace/useGetJobs.ts, client/modules/_hooks/src/workspace/usePostJobs.ts, client/modules/workspace/src/JobStatusNav/JobStatusNav.tsx, client/modules/workspace/src/JobsListing/JobsListing.tsx, client/modules/workspace/src/Toast/Toast.tsx, client/modules/workspace/src/utils/notifications.ts, designsafe/apps/api/notifications/urls.py, designsafe/apps/api/notifications/views/api.py, designsafe/apps/webhooks/views.py, designsafe/apps/workspace/api/views.py
* [DES-2779](https://tacc-main.atlassian.net/browse/DES-2779)
1. Submit a job
2. Confirm job listing updates upon submission
3. Confirm job listing updates upon job status update
4. Confirm notification badge increments upon job status update
5. Confirm all job listing buttons work
Job Status Notification Badge:
Job Listing Action Buttons:
Successful Resubmit:
=> task/DES-2779: Jobs Listing Notification Badge & Update Job Listing Upon Notification

client/modules/_common_components/src/lib/Button/Button.module.css, client/modules/_common_components/src/lib/Button/Button.tsx, client/modules/workspace/src/AppsBreadcrumb/AppsBreadcrumb.module.css, client/modules/workspace/src/AppsBreadcrumb/AppsBreadcrumb.tsx, client/modules/workspace/src/AppsSubmissionDetails/AppsSubmissionDetails.module.css, client/modules/workspace/src/AppsSubmissionDetails/AppsSubmissionDetails.tsx, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/FormField.tsx, client/modules/workspace/src/JobsListing/JobsListing.tsx, client/src/main.tsx, client/src/workspace/layouts/JobsListingLayout.tsx
- Fix Job Submit button color and size
- Job Submission Summary Form styling
- App Form Field styling
- Fix button size for job listing action buttons
- Use Helvetica across all workspace
* [DES-2797](https://tacc-main.atlassian.net/browse/DES-2797)
* [DES-2774](https://tacc-main.atlassian.net/browse/DES-2774)
* [DES-2808](https://tacc-main.atlassian.net/browse/DES-2808)
* [DES-2814](https://tacc-main.atlassian.net/browse/DES-2814)
* [DES-2818](https://tacc-main.atlassian.net/browse/DES-2818)
=> Apps form styling fixes

client/modules/workspace/src/AppsWizard/AppsWizard.tsx
Continue is submitting job if all required values are valid
* [DES-2789](https://tacc-main.atlassian.net/browse/DES-DES-2789)
1. Remove htmlType submit on continue button
1. Test https://designsafe.dev/rw/workspace/openfoam
=> Hotfix: App Form - Remove htmlType submit on continue button

client/modules/_hooks/src/workspace/index.ts, client/modules/_hooks/src/workspace/useGetAllocations.ts, client/modules/_test-fixtures/src/fixtures/workspace/allocations-listing.json, client/modules/_test-fixtures/src/handlers.ts, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/utils/apps.ts, client/src/workspace/layouts/WorkspaceBaseLayout.tsx, designsafe/apps/auth/views.py, designsafe/apps/workspace/api/views.py, designsafe/apps/workspace/models/allocations.py
Use allocations returned from hooks in app form.
* [DES-2820](https://tacc-main.atlassian.net/browse/DES-2820)
1.  Open network tab and go to https://designsafe.dev/rw/workspace
2. Confirm allocations are loaded
3. Open an app and confirm allocations show that are active for app's default exec system
=> task/DES-2820: Allocations in App Form

client/modules/workspace/src/JobsListing/JobsListing.tsx, client/modules/workspace/src/JobsListing/JobsListingTable/JobsListingTable.tsx
- Fixes state management for interactive session modal
- Adds better job listing placeholder
* [DES-2823](https://tacc-main.atlassian.net/browse/DES-2823)
1. Submit an interactive job like https://designsafe.dev/rw/workspace/jupyter-lab-hpc
2. When you receive notification "Session ready to view", click "Job Status"
3. Click "Open" button and confirm modal opens
4. Confirm "Connect" button in modal works
=> task/DES-2823: Fix interactive modal

README.md
Update step \# 3 of README's "First time setup" to be accurate…
…to at least what worked for me from @rstijerina's instruction.
None
- **changed** step 3 of readme "First time setup"
https://github.com/DesignSafe-CI/portal/blob/feat/Tapis-v3-redesign--readme/README.md#first-time-setup
(as of 3f6160c)
=> docs: tapis v3 redesign readme step №3

client/modules/_common_components/src/datafiles/FileListingTable/FileListingTable.tsx, client/modules/_hooks/src/datafiles/useFileListing.ts, client/modules/workspace/src/AppsWizard/FormField.tsx, client/modules/workspace/src/SelectModal/SelectModal.module.css, client/modules/workspace/src/SelectModal/SelectModal.tsx
* Title bar for Modal
* Breadcrumb and System placement in design
* Search bar and integration with data files (except Projects)
Pending for Part 2:
* Back button
* Search integration for Projects
* Styling:
* Remove border line under header
* Text color of selected option in System Select
* Do not allow drill into a file
* Allow file vs directory selection updates.
*[DES-2819](https://tacc-main.atlassian.net/browse/DES-2819)
1. Go to an app page with input: Example: https://designsafe.dev/rw/workspace/openfoam#!/
2. Select Input.
3. Adjust the system selection and see the placeholder text changing.
4. Search for files.
5. Close the modal and reopen. Ensure the search text is empty.
=> DES-2819: Select Modal Design Updates (Part 1 of 2)

client/modules/workspace/src/AppsSubmissionDetails/AppsSubmissionDetails.tsx
* [DES-2826](https://tacc-main.atlassian.net/browse/DES-2826)
* Handle nested field separately.
* Make isRequired a util
1. Go to https://designsafe.dev/rw/workspace/opensees-sp-s3?version=3.6.0
2. Remove the app args in second screen of app form.
3. Required label should show up in summary view
4. Regression test other apps - OpenFoam, MPM.
=> Bug DES-2826: Fix isRequired for nested fields

client/modules/_hooks/src/systems/usePushKeys.ts, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsWizard.tsx, client/modules/workspace/src/SystemsPushKeysModal/SystemsPushKeysModal.tsx, designsafe/static/scripts/dashboard/components/dashboard/dashboard.component.html, designsafe/static/scripts/ng-designsafe/components/notification-badge/notification-badge.component.html
- Show missing allocation message
- Fix Push Keys Modal error handling and add better styling
- Fix `onSuccess` handling after push keys
- Open "View User Guide" in new tab
- Point notifications bell "View all" button to Workspace Job History
- Remove Apps and Jobs from Dashboard
* [DES-2837](https://tacc-main.atlassian.net/browse/DES-2837)
* [DES-2838](https://tacc-main.atlassian.net/browse/DES-2838)
* [DES-2840](https://tacc-main.atlassian.net/browse/DES-2840)
* [DES-2841](https://tacc-main.atlassian.net/browse/DES-2841)
1. Go to https://designsafe.dev/dashboard/ and confirm jobs and apps do not show
2. Click notification bell in top right and click "View all", confirm goes to "Job Status" listing
3. Remove your user credential from frontera with tapipy:
```
user = Tapis(...) …
```
=> Apps form testing session fixes

client/modules/_common_components/src/datafiles/FileListingTable/FileListingTable.tsx, client/modules/_hooks/src/datafiles/index.ts, client/modules/_hooks/src/datafiles/publications/index.ts, client/modules/_hooks/src/datafiles/publications/useCreateFeedbackTicket.ts, client/modules/_hooks/src/datafiles/useFileDetail.ts, client/modules/datafiles/src/DatafilesModal/DownloadModal/DownloadModal.tsx, client/modules/datafiles/src/DatafilesToolbar/DatafilesToolbar.tsx, client/modules/datafiles/src/projects/BaseProjectDetails.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelineSelectLicense.tsx, client/modules/datafiles/src/projects/forms/BaseProjectForm.tsx, client/modules/datafiles/src/projects/modals/BaseProjectCreateModal.tsx, client/modules/datafiles/src/projects/modals/BaseProjectUpdateModal.tsx, client/modules/datafiles/src/publications/index.ts, client/modules/datafiles/src/publications/modals/DownloadDatasetModal.tsx, client/modules/datafiles/src/publications/modals/SubmitFeedbackModal.tsx, client/src/datafiles/layouts/projects/ProjectWorkdirLayout.tsx, client/src/datafiles/layouts/published/PublishedDetailLayout.tsx, designsafe/apps/api/datafiles/operations/tapis_operations.py, designsafe/apps/api/projects_v2/views.py
=> Add modals for publication feedback/archive download

client/modules/workspace/src/AppsSideNav/AppsSideNav.tsx, client/modules/workspace/src/JobStatusNav/JobStatusNav.tsx, client/src/main.tsx, client/src/workspace/layouts/layout.module.css
Fine tune borders to more closely match design
1. Ensure border weight and color matches [design](https://xd.adobe.com/view/bab9a62d-3f2a-45f8-be0f-5680c474d9c1-efea/screen/341f26ad-1618-432e-926a-e8b7055af30b/)
Before
After
=> update apps side nav border colors and weight

designsafe/apps/api/projects_v2/operations/project_publish_operations.py
- Fix default `version` arg passed into the pipeline
- Fix permissions when copying files for publication
=> fixes to pipeline publish operations

client/modules/datafiles/src/projects/ProjectTitleHeader/ProjectTitleHeader.tsx, client/modules/datafiles/src/projects/forms/BaseProjectForm.tsx, client/modules/datafiles/src/projects/forms/_fields/ReferencedDataInput.tsx, client/modules/datafiles/src/projects/forms/_fields/RelatedWorkInput.tsx, client/src/datafiles/layouts/projects/ProjectWorkdirLayout.tsx
- Allow editing of None type projects
- Fix bug where guest. members couldn't be added to type Other.
- Enforce URL formatting on referenced data/related works.
* [DES-2931](https://tacc-main.atlassian.net/browse/DES-2931)
* [DES-2932](https://tacc-main.atlassian.net/browse/DES-2932)
=> DES-2931, DES-2932, DES-2929: Project edit modal fixes

client/modules/datafiles/src/projects/ProjectPipeline/PipelineOtherSelectFiles.tsx
Show file tags in Select Files screen for type Other
* [DES-2933](https://tacc-main.atlassian.net/browse/DES-2933)
=> Bug/DES-2933: Show file tags in Select Files screen for type Other

designsafe/static/styles/_mixins/_link.scss, designsafe/static/styles/base.scss, designsafe/static/styles/bootstrap3.breadcrumb.css, designsafe/static/styles/main.css, designsafe/static/styles/variables.css, designsafe/templates/cms_breadcrumbs.html, designsafe/templates/cms_page_for_app.html, designsafe/templates/menu/breadcrumb.html
Resolve conflicts merging `main` into `feat/Tapis-v3-redesign` (after merge of #1268 to `main`).
None.
The diff mimics #1268, but the actual merge conflict resolution was to accept #1268's changes to `main.css` i.e. move variables to `variables.css`.
None really, simple resolution. But you could retest #1268 and regression test styles that use CSS variables.
Skipped.
=> feat: Tapis v3 Redesign — resolve merge conflicts with main after #1268 merge

client/modules/datafiles/src/projects/modals/ChangeProjectTypeModal.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoModal.tsx
Fix prop passing so that Protected Data options display when changing project type.
* [DES-2990](https://tacc-main.atlassian.net/browse/DES-2990)
=> Bug/des 2990  Fix fr protected data options

client/modules/datafiles/src/projects/ProjectPipeline/PipelineOrderAuthors.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelineOtherSelectFiles.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelineProofreadCategories.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelineProofreadProjectStep.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelineProofreadPublications.tsx, client/modules/datafiles/src/projects/modals/ProjectBestPracticesModal.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoStepper/ExperimentalSteps.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoStepper/SimulationSteps.tsx
(1) In cases when "Curation office hours" is in a sentence, the "C" needs to be lower case.
(2) Publish/ Amend/ Version is changed to Publish / Amend / Version (to match PROD)
* [DES-2982](https://tacc-main.atlassian.net/browse/DES-2982)
1.
=> Bug/DES-2982: text/typo/wording/spelling issues

designsafe/apps/api/projects_v2/migration_utils/graph_constructor.py, designsafe/apps/api/projects_v2/operations/project_archive_operations.py, designsafe/apps/api/projects_v2/operations/project_publish_operations.py, designsafe/apps/api/projects_v2/schema_models/_field_models.py, designsafe/apps/api/projects_v2/schema_models/base.py, designsafe/apps/api/projects_v2/schema_models/experimental.py, designsafe/apps/api/projects_v2/schema_models/field_recon.py, designsafe/apps/api/projects_v2/schema_models/hybrid_sim.py, designsafe/apps/api/projects_v2/schema_models/simulation.py, designsafe/apps/api/projects_v2/tasks.py, designsafe/apps/api/publications_v2/elasticsearch.py, designsafe/apps/api/publications_v2/operations/fedora_graph_operations.py, designsafe/libs/fedora/fedora_operations.py
- Add utilities to crawl publications and format metadata for Fedora, including generating the PROV relations.
- Add hooks to zip/archive published files and index publications in Elasticsearch after publish/amend/revise.
- [DES-2999] Fix a bug where the pipeline would fail to copy some files; prevent the pipeline from minting DOIs if files can't be copied.
* [DES-2999](https://tacc-main.atlassian.net/browse/DES-2999)
=> Pipeline fixes and Fedora representation for publications

client/modules/_common_components/src/datafiles/FileListingTable/FileListingTable.tsx, client/modules/_hooks/src/datafiles/usePathDisplayName.ts, client/modules/datafiles/src/DatafilesModal/UploadFileModal/UploadFileModal.tsx, client/modules/datafiles/src/FileListing/FileListing.tsx, client/modules/datafiles/src/projects/EmptyProjectFileListing.tsx, client/modules/datafiles/src/projects/ProjectCurationFileListing/ProjectCurationFileListing.tsx, client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx, client/modules/datafiles/src/projects/forms/CreateProjectForm.tsx, client/modules/datafiles/src/projects/forms/_fields/DateInput.tsx, client/modules/datafiles/src/projects/forms/_fields/DropdownSelect.tsx, client/modules/datafiles/src/projects/forms/_fields/UserSelect.tsx, client/modules/datafiles/src/projects/index.ts, client/modules/datafiles/src/projects/modals/ManageCategoryModal.tsx, client/modules/datafiles/src/projects/modals/ManagePublishableEntityModal.tsx, client/src/datafiles/layouts/projects/ProjectPreviewLayout.tsx, client/src/datafiles/layouts/projects/ProjectWorkdirLayout.tsx, client/src/styles.css
Fixes for small styling/display bugs in Data Depot.
* [DES-2983: Toolbar should Scroll with User](https://tacc-main.atlassian.net/browse/DES-2983)
* [DES-2985: Reset 'New Project' State](https://tacc-main.atlassian.net/browse/DES-2985)
* [DES-2987: Update message for empty listing in projects](https://tacc-main.atlassian.net/browse/DES-2987)
* [DES-2989: Remove checkboxes in listings in preview/pipeline](https://tacc-main.atlassian.net/browse/DES-2989)
* [DES-2991: Add padding under Publication Preview layout](https://tacc-main.atlassian.net/browse/DES-2991)
* [DES-2997: Use "HPC Work" instead of "My Data (Work)" in breadcrumbs](https://tacc-main.atlassian.net/browse/DES-2997)
=> [various] Data Files/Projects style fixes

client/src/styles/modal.css
Scopes the overflow and max-height changes to modals so that they only apply to the Tools & Applications area. This preserves the current production scroll behavior for modals in the Data Depot.
=> Scope scroll overflow behavior in modals to Tools & Applications

client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx, client/modules/datafiles/src/projects/SubEntityDetails.tsx, client/modules/datafiles/src/projects/forms/ProjectCategoryForm.tsx, client/modules/datafiles/src/projects/forms/PublishableEntityForm.tsx, client/modules/datafiles/src/projects/modals/ManageCategoryModal.tsx, client/modules/datafiles/src/projects/modals/ManagePublishableEntityModal.tsx, client/modules/datafiles/src/projects/modals/PipelineEditCategoryModal.tsx
- Use a single form for creating and updating categories
- Add file listings under categories in the management modal
* [DES-2984](https://tacc-main.atlassian.net/browse/DES-2984)
=> Task/DES-2984: Use a single form for creating and updating categories

designsafe/apps/api/datafiles/operations/tapis_operations.py, designsafe/apps/api/filemeta/management/commands/populate_filemeta_table_from_tavpisv2_metadata.py, designsafe/apps/api/filemeta/models.py, designsafe/apps/api/filemeta/tasks.py, designsafe/apps/api/filemeta/views.py
Update file metadata on move/copy/rename.
* [DES-2772](https://tacc-main.atlassian.net/browse/DES-2772)
1. move/copy/rename a file with custom metadata and check that the metadata is preserved at the new path/location.
=> Task/DES-2772: Update file metadata on move/copy/rename

client/modules/_hooks/src/datafiles/nees/useNeesListing.ts, client/modules/datafiles/src/DatafilesToolbar/DatafilesToolbar.tsx, client/modules/datafiles/src/nees/NeesDetails.tsx, client/modules/datafiles/src/nees/NeesListing.tsx, client/src/datafiles/layouts/nees/NeesDetailLayout.tsx, client/src/datafiles/layouts/nees/NeesListingLayout.tsx, designsafe/apps/api/publications/operations.py
- Paginate the NEES listing correctly
- Add toolbars/search to NEES listing and detail layouts
- add links to experimental files in the Experiments tab
* [DES-2776](https://tacc-main.atlassian.net/browse/DES-2776)
=> Task/DES-2776: NEES updates- toolbars and links to experiments

client/modules/datafiles/src/projects/forms/BaseProjectForm.tsx, client/modules/datafiles/src/projects/forms/CreateProjectForm.tsx, client/modules/datafiles/src/projects/forms/ProjectCategoryForm.tsx, client/modules/datafiles/src/projects/forms/PublishableEntityForm.tsx
The description field needs two messages: 
(1) If it is blank
(2) If the description length is less than 50 char or more than 5000 char
* [DES-2986](https://tacc-main.atlassian.net/browse/DES-2986)
Changes the 'rule' for all description fields to check for blank field vs length
1. Changes affect 'description' in all forms (new/edit project, new/edit categories, new/edit prj_type, etc.
=> Bug/des-2986: description error messages

client/src/workspace/layouts/AppsPlaceholderLayout.tsx, client/src/workspace/layouts/AppsViewLayout.tsx, client/src/workspace/layouts/WorkspaceBaseLayout.tsx, client/src/workspace/layouts/layout.module.css
Fix scroll in HTML apps
* [DES-3020](https://tacc-main.atlassian.net/browse/DES-3020)\
1. Make window small, and go to https://designsafe.dev/rw/workspace/ansys
2. ensure you can scroll the html
=> task/DES-3020: Fix scroll in HTML apps

client/modules/datafiles/src/projects/ProjectNavbar/ProjectNavbar.tsx, client/modules/datafiles/src/projects/modals/ProjectDataTransferModal.tsx, client/modules/datafiles/src/projects/modals/index.ts, client/src/datafiles/layouts/projects/ProjectCurationLayout.tsx, client/src/datafiles/layouts/projects/ProjectWorkdirLayout.tsx
Add help text and a modal for displaying the paths to project files on data.tacc.utexas.edu
=> Add data transfer information to Projects.

client/src/datafiles/layouts/projects/ProjectDetailLayout.tsx, client/src/datafiles/layouts/published/PublishedDetailLayout.tsx
Show a clear error instead of the infinite spinner.
=> Improve handling of error responses for projects/publications

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx
- Changes the missing allocation message as per TimC's request.
- Adds bottom padding to app form alerts.
1. In AppSubmissionForm change `missingAllocation` to `!missingAllocation` [here](https://github.com/DesignSafe-CI/portal/blob/fac661cd035574e6ad90abe2eed0b21d98abe32e/client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx#L524)
2. Make sure new message shows and link works.
=> Quick: Update missing allocation message

client/modules/workspace/src/SystemsPushKeysModal/SystemsPushKeysModal.tsx, designsafe/apps/auth/tasks.py
- Fix `check_or_configure_system_and_user_directory` `retry()` method
- Update `<SystemsPushKeysModal />` wording, as per TimC request
=> Quick: Fix `check_or_configure_system_and_user_directory` `retry()`; Update `<SystemsPushKeysModal />` wording.

client/modules/_hooks/src/datafiles/projects/types.ts, client/modules/_hooks/src/datafiles/publications/useDataciteEvents.ts, client/modules/_hooks/src/datafiles/publications/useDataciteMetrics.ts, client/modules/datafiles/src/projects/PublishedEntityDetails.tsx, client/src/datafiles/layouts/published/PublishedDetailLayout.tsx, designsafe/apps/api/projects_v2/migration_utils/file_obj_ingest.py, designsafe/apps/api/projects_v2/migration_utils/project_db_ingest.py, designsafe/apps/api/projects_v2/migration_utils/publication_transforms.py, designsafe/apps/api/publications_v2/views.py
Fix tombstone ingest and add an alert element when a pub/entity is tombstoned.
=> Quick: Fix tombstone ingest/display

client/modules/datafiles/src/projects/ProjectListing.tsx, client/modules/datafiles/src/publications/PublishedListing/PublishedListing.tsx, designsafe/apps/api/projects_v2/migration_utils/project_db_ingest.py
After migrating projects to the db, fix their last_updated dates to match Tapis.
=> fix last-updated dates on projects after migrating

designsafe/apps/api/projects_v2/operations/project_publish_operations.py, designsafe/apps/api/publications_v2/operations/fedora_graph_operations.py, designsafe/apps/api/publications_v2/tasks.py, designsafe/libs/fedora/fedora_operations.py, designsafe/settings/test_settings.py
Adds an async wrapper around Fedora ingest and call the task when performing publish/version/amend operations.
=> Fedora: Ingest on publish

designsafe/apps/auth/views.py
always use www in prod redirect uri
=> always use www in prod redirect uri

client/modules/datafiles/src/projects/modals/MetricsModal.tsx
The months in the modal where wrong 
* [DES-XXXX](https://tacc-main.atlassian.net/browse/DES-XXXX)
1.
=> Update quarters in MetricsModal to match correct time periods

client/modules/datafiles/src/projects/ProjectPipeline/PipelineOrderAuthors.tsx
Prevents entities from jumping around on the page when re-ordering authors.
=> Keep entities in the same order when re-ordering authors

designsafe/static/scripts/rapid/controllers/rapid-main-ctrl.js, designsafe/static/scripts/rapid/services/rapid-data-service.js, designsafe/static/scripts/rapid/services/rapid-data-service.spec.js
Rework filter methods to be more explicit. This is to address comment in review:  https://github.com/DesignSafe-CI/portal/pull/1384#discussion_r1715587237
=> hotifx:  rework filter methods

designsafe/apps/api/projects_v2/operations/project_archive_operations.py, designsafe/apps/api/projects_v2/operations/project_publish_operations.py, designsafe/apps/api/projects_v2/operations/project_system_operations.py, designsafe/apps/api/projects_v2/tasks.py, designsafe/apps/api/publications_v2/operations/fedora_graph_operations.py, designsafe/apps/api/publications_v2/tasks.py, designsafe/libs/common/context_managers.py
- Add a context manager to close database connections opened during Celery tasks
- Apply the context manager to Celery tasks in projects/publications
* [DES-3062](https://tacc-main.atlassian.net/browse/DES-3062)
=> task/DES-3062: Context manager to clean up database connections opened in Celery tasks

client/modules/_hooks/src/datafiles/useFileListing.ts
There was an oversight here that was affecting Other type projects.
=> Quick: properly log DOIs on all file listing operations

designsafe/apps/api/projects_v2/operations/datacite_operations.py
Prefix Datacite subtitle with "in" so entries have a title of "Experiment 1" and a subtitle of "in My Experimental Project".
* [WC-71](https://tacc-main.atlassian.net/browse/WC-71)
=> Add project title as a subtitle in datacite, prefixed with 'in'

client/modules/datafiles/src/DatafilesModal/DownloadModal/DownloadModal.tsx
Log DOIs for each downloaded file even if there are duplicates. This will allow the data team to zip the files/DOIs together and get a better understanding of which file is attached to which DOI.
* [WC-94](https://tacc-main.atlassian.net/browse/WC-94)
=> Log DOIs for each file when multiple are selected

designsafe/apps/api/projects_v2/operations/project_system_operations.py
Bump setfacls app to v0.0.2 (use TAS to look up UIDs).
* [WC-111](https://tacc-main.atlassian.net/browse/WC-111)
=> task/WC-111: Quick: Bump Setfacls app to v0.0.2

designsafe/apps/api/projects_v2/operations/datacite_operations.py, designsafe/apps/api/projects_v2/operations/project_publish_operations.py
Ensure that after a subsequent publish, existing categories have the correct publication date and aren't overwritten with the date of the most recent publication.
* [WC-113](https://tacc-main.atlassian.net/browse/WC-113)
=> Ensure correct publication dates after subsequent publish

designsafe/apps/workspace/api/views.py
Includes job post response object in audit trails logs, so events can be associated with the job uuids they create.
=> Enhance Jobs Audit logging

designsafe/apps/workspace/api/views.py
Log tapis job submit response as a dict
=> Quick: log response as dict on job submit

designsafe/static/styles/app-card.css, designsafe/static/styles/bootstrap3.breadcrumb.css
Courtesy update of Core-Styles.
None
* **updated** core-styles version (in CSS) 
N/A
No changes since old versions are relevant to these instances.
=> chore: update core-styles

client/modules/datafiles/src/publications/PublicationSearchSidebar/PublicationSearchSidebar.tsx
Show experiment type filter regardless of selected facility.
* [WC-187](https://tacc-main.atlassian.net/browse/WC-187)
=> Task/WC-187: Show experiment type filter regardless of selected facility

designsafe/static/scripts/rapid/html/index.html
=> quick: fix recon link

designsafe/apps/auth/views.py
Since we have onboarding now with tickets created for new users, we don't need the new user notification email.
* [WP-770(https://tacc-main.atlassian.net/browse/WP-770)
Removed the call to send a new user notification email.
1. this is not testable from local dev as far as I am aware
=> WP-770: change email regarding slack

client/modules/datafiles/src/AddFileFolder/AddFileFolder.tsx, client/modules/datafiles/src/DatafilesHelpDropdown/DatafilesHelpDropdown.tsx, client/modules/datafiles/src/DatafilesModal/DownloadModal/DownloadModal.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelinePublishModal.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoStepper/ExperimentalSteps.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoStepper/FieldReconSteps.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoStepper/SimulationSteps.tsx, client/modules/datafiles/src/publications/modals/DownloadDatasetModal.tsx, designsafe/apps/djangoRT/templates/djangoRT/ticketCreate.html, designsafe/apps/workspace/fixtures/job-submission.json, designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html, designsafe/static/scripts/data-depot/components/data-depot-new/data-depot-new.component.html, designsafe/static/scripts/data-depot/components/data-depot-new/data-depot-new.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-privacy-agreement.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-download-large/download-large.component.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.template.html, designsafe/static/scripts/projects/components/publication-download/publication-download.template.html, designsafe/static/scripts/workspace/fixtures/app-meta.fixture.json
* [WC-188](https://tacc-main.atlassian.net/browse/WC-188)
Updating user guide links to point to correct locations in the updated user guide format
1. 
I went through and updated _all_ user guide links regardless of if they appeared to be from the previous angular code or not, reason being is just in case those are still being used somewhere by accident.
And the formatting updates are incidental; I have "format upon saving" turned on in VS Code.
=> task/WC-188: Fix DesignSafe User Guide Links

client/modules/datafiles/src/projects/PublishedEntityDetails.tsx
- Fix label for "Referenced Data" in the published view.
- Show the type (DOI/URL) for related works.
* [WC-253](https://tacc-main.atlassian.net/browse/WC-253)
=> task/WC-253: Fix Referenced Data display in publications

client/modules/workspace/src/JobsDetailModal/JobsDetailModal.tsx, designsafe/apps/workspace/api/views.py
- Fix job detail modal
- fix job name as modal header
- fix node count rendering
- Fix valid app filtering logic
1. Submit a job with a different cores per node and node count
2. Confirm the job detail modal for this job accurately shows these numbers
3. Confirm the job detail modal shows the job name as the header
=> Quick: Workspace fixes

designsafe/apps/nco/templates/designsafe/apps/nco/ttc_grants.j2
Updating the page title in the j2 template for the NCO TTC Grants page
* [WP-985](https://tacc-main.atlassian.net/browse/WP-985)
1.
=> WP-985: NCO TTC Grants page title update

client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx
Change DOI hash routes to open/scroll to relevant collections instead of pointing to the generic publication landing page.
* [WC-261](https://tacc-main.atlassian.net/browse/WC-261)
Check that the following URLs open/focus on different document collections in PRJ-5817:
- https://designsafe.dev/data/browser/public/designsafe.storage.published/PRJ-5817/#detail-f8dccba3-e6db-470f-b24c-e6c2cd70b2b7
- https://designsafe.dev/data/browser/public/designsafe.storage.published/PRJ-5817/#detail-7064c44c-3edc-46bb-ac49-c112fdbe9e2d
- https://designsafe.dev/data/browser/public/designsafe.storage.published/PRJ-5817/#detail-12942590-52e1-4cf1-910e-51774adbedd7
=> bug/WC-261: Change DOI hash routes to open/scroll to relevant collections

designsafe/settings/rt_settings.py, designsafe/settings/test_settings.py
Add 'Allocations' to the Category pulldown on New Ticket form
* [WP-939](https://tacc-main.atlassian.net/browse/WP-939)
Add 'Allocations' to the Category pulldown on New Ticket form
1.  Navigate to https://designsafe.dev/help/new-ticket/
2. Make sure 'Allocations' is listed as a Category option
=> Add 'Allocations' to the Category pulldown on New Ticket form

client/modules/workspace/src/components/SystemStatusModal/SystemStatusModal.module.css, client/modules/workspace/src/components/SystemStatusModal/SystemStatusModal.tsx
Changes intended for the System Status modal are currently being applied to ALL modals across the site, which is causing unintended styling changes.
=> Hotfix: Scope System Status modal styles to the relevant component

client/modules/_hooks/src/workspace/types.ts, client/modules/workspace/src/AppsSubmissionDetails/AppsSubmissionDetails.tsx, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/AppsWizard/FormField.tsx, client/modules/workspace/src/AppsWizard/Steps.tsx, client/modules/workspace/src/JobsDetailModal/JobsDetailModal.tsx, client/modules/workspace/src/utils/apps.ts, client/modules/workspace/src/utils/jobs.ts
- Move reservation field to configuration
- Show reservation field by default, hide via `hideReservation` field in app notes
- (We can reverse this if desired)
- Render field in form and add to job submission similar to how we do the allocation field
* [WA-449](https://tacc-main.atlassian.net/browse/WA-449)
1. Load any app
2. See that Reservation is an optional field in configuration section
3. Type in reservation field, see it auto populate in detail summary in real time
4. Submit successfully
5. Go to job details, see field in job detail modal
6. Click "Reuse Inputs", see field populate in form field
=> task/WA-449: Reservation field edits

README.md
add es_setup step to readme
None
=> fix: add es_setup step to readme

client/modules/datafiles/src/projects/modals/ProjectBestPracticesModal.tsx
Added "Prepare to" to the button text that leads to the publishing pipeline
* [WC-258](https://tacc-main.atlassian.net/browse/WC-258)
1. 
As per Tracy, we are just adding the "Prepare to" text for now.  We can make a new task for the pre/post publication change later if they still want it.
=> task/WC-258: Publishing Pipeline Button changes

client/modules/datafiles/src/projects/ProjectPipeline/PipelineProofreadProjectStep.tsx, client/modules/datafiles/src/projects/modals/ProjectBestPracticesModal.tsx
Add documentation links for Policies and Best Practices for software projects.
=> Quick: Add policy and best practices links for software publications.
