DesignSafe-CI/portal

designsafe/apps/search/tasks.py, designsafe/celery.py
We might want to isolate the celerybeat container into its own, right now it is running in the workers container. If we were to spin up more workers, we would get more beat schedulers...
=> update CMS search index erry 15 minutes

designsafe/common_settings.py, designsafe/elasticsearch_settings.py
We will have to add a new env variable DESIGNSAFE_ENVIRONMENT to flop the different setups around. 
DESIGNSAFE_ENVIRONMENT=Prod
DESIGNSAFE_ENVIRONMENT=Staging
Or it will default to dev config of local dockerized elasticsearch
=> DES-262: moving some of the E.S. settings around

designsafe/apps/accounts/migrations/0015_create_notification_preferences.py, designsafe/apps/auth/backends.py
- Adds notification preferences to a user's model when they sign in, or when they create an account for the first time.
- Runs a migration to add a notification_preferences model to all current users where that model is null, just to be safe.
=> Opt in users to email subscriptions by default

designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/apps-service.js
It appears that parallel apps have a hard defined Processors Per Node count (`defaultProcessorsPerNode`), and deviating from the `defaultNodeCount` can cause the job to fail. e.g. OpenSeesMP (Stampede 2) has a `defaultProcessorsPerNode` of 544, and a `defaultNodeCount` of 8, and allocates 544/8=68 processors per node. In order to work within this functionality we will need to add some logic to the job submission to calculate the correct `defaultProcessorsPerNode`, and test to make sure this process is correct.
=> Remove nodeCount option for parallel apps - hotfix

designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/controllers/application-form.js, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/apps-service.js
- Reintroduces `nodeCount` as an available parameter for users to edit in job submissions for parallel apps. 
- Calculates `processorsPerNode` when `nodeCount != defaultNodeCount`, overwriting `defaultProcessorsPerNode` and allowing successful submission
=> Add functional 'nodeCount' field to job submission forms

.gitignore, designsafe/apps/api/agave/filemanager/search_index.py, designsafe/apps/api/agave/views.py, designsafe/static/scripts/data-depot/controllers/my-data.js
- Search works within the Community Data tab in the data depot
- Fixed a bug in MyDataCtrl that was preventing links from being generated for systems other than designsafe.storage.default
=> added community data search to data depot

designsafe/apps/api/agave/filemanager/search_index.py, designsafe/apps/api/agave/views.py, designsafe/apps/api/public_data/views.py, designsafe/static/scripts/data-depot/app.js, designsafe/static/scripts/data-depot/templates/data-depot-toolbar.html
Various fixes to search within the Data Depot.
- Searches in Community Data executed from the data depot will no longer redirect to the login screen for logged-out users.
- Community Data searches now show the correct options in the preview window based on user permissions.
- Searches in My Data/Shared with Me should work correctly now.
- Don't show the search bar while in My Projects.
=> fixes to data depot search

designsafe/static/scripts/data-depot/controllers/community.js, designsafe/static/scripts/data-depot/controllers/external-data.js, designsafe/static/scripts/data-depot/controllers/my-data.js, designsafe/static/scripts/data-depot/controllers/projects.js, designsafe/static/scripts/data-depot/controllers/publications.js, designsafe/static/scripts/data-depot/controllers/published.js, designsafe/static/scripts/data-depot/controllers/shared-data.js
Previous behavior: Files indexed with a `type` other than `"file"` in elasticsearch would be treated as empty folders in the data depot.
Change made: Instead of looking specifically for the `"file"` type, any document other than a folder/directory is now considered previewable.
=> Show previews for files indexed with type other than 'file'

designsafe/apps/applications/static/designsafe/apps/applications/html/application-details.html, designsafe/apps/applications/static/designsafe/apps/applications/html/application-tray.html, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-add.js, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-edit.js, designsafe/apps/applications/static/designsafe/apps/applications/scripts/controllers/application-tray.js, designsafe/apps/workspace/static/designsafe/apps/workspace/html/application-form.html, designsafe/apps/workspace/static/designsafe/apps/workspace/scripts/services/simple-list-service.js, designsafe/static/styles/main.css
- The appCategory field in the json app definition is moved to the tag on submission, in the format
`appCategory:Visualization`
- The workspace tray parses an app's tag for the appCategory, where we will store the categories in the future. Current implementation of the appCategory field in metadata is still supported.
- Fixed the navbar dropdown spacing issue.
- Added ability to enable, disable, and make private html apps/metadata.
- Fixed cloning issue.
=> Task/des 439: Moved appCategory to tags & annoying navbar css fix and other applications stuff

designsafe/apps/api/tasks.py
Currently in local dev, running the `reindex_agave` task on file upload throws `401 Client Error: Unauthorized for url` because it's trying to use an expired access token for the `ds_admin` user. 
With this change we use the service account client to do these operations, since its access token doesn't expire.
The service account client is only used if Debug mode is active, so this change shouldn't affect staging/prod.
=> Elasticsearch indexer works in local dev.

designsafe/apps/api/agave/filemanager/public_search_index.py
Filter publication searches to make sure `status = 'published'`. Otherwise old tests/unviewable publications show up.
=> Only show publications in search if status=published

designsafe/apps/api/agave/filemanager/search_index.py, designsafe/apps/api/agave/views.py, designsafe/static/scripts/data-depot/app.js, designsafe/static/scripts/data-depot/controllers/data-depot-toolbar.js, designsafe/static/scripts/data-depot/controllers/projects.js, designsafe/static/scripts/data-depot/templates/data-depot-toolbar.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
Implements a search within projects in My Projects (previously searches could only be run from the general projects listing).
This is done by adding a `query_string` argument to the `projects.view.data` router state and using it to display search results. An optional `params` argument was added to the `DataBrowserService.browse` method so that the query string can be passed to the backend without affecting file listings in other parts of the Data Depot.
=> DES-580: Search within projects in My Projects

designsafe/static/scripts/data-depot/controllers/projects.js
Fixes a potential race condition in `My Projects` where `ProjectDataCtrl` finishes a file listing before `ProjectViewCtrl` retrieves project metadata, preventing the spinner from ever leaving the busy state.
This is done by explicitly making sure that the promise returned from `ProjectService.get` is resolved before doing the file listing.
=> Bug/des 579: Race condition in My Projects

designsafe/static/scripts/data-depot/controllers/projects.js
Quick fix so the href in the breadcrumb doesn't get a query string passed to it.
=> task/DES-594: Fix breadcrumb links for within-project search

designsafe/static/scripts/ng-designsafe/html/modals/data-browser-service-preview.html
Video preview banner should now appear only while the video preview is loading.  After loading is complete, the banner will disappear.
=> task/DES-591: Video Banner for Preview Modals

designsafe/static/scripts/ng-designsafe/html/directives/dd-listing.html
https://jira.tacc.utexas.edu/browse/DES-589
"Show" link on reports now display data. 
Given most updated code on portal the "show" link is only currently available on experimental projects, but the change made should work for all sorts of projects when this link comes to be available in other sorts of projects such as simulation and hybrid.
=> task/DES-589 "Show" link on reports does not display data

designsafe/settings/common_settings.py, designsafe/templates/ramp_verification.html, designsafe/urls.py
Serve a RAMP verification file. We need to add the following line to `designsafe.env`:
`RAMP_VERIFICATION_ID=google136a59fe45020610`
=> DES-562: add RAMP verification through django urls

package-lock.json, package.json, webpack.config.js
Use `cheap-module-eval-source-map` when running `npm run dev` so that changes don't take forever to propagate.
=> Faster webpack bundling

designsafe/static/scripts/ng-designsafe/services/index.js
TicketsService was mistakenly instantiated as a `factory` in the ES6 branch. This PR fixes that by defining it as a `service`
=> change TicketsService from factory to service

CHANGELOG.md, designsafe/apps/api/tasks.py
When a project is published and its files are copied to Corral and indexed in Fedora, those files are now also indexed in Elasticsearch.
=> task/DES-617: index published files once they are copied to Corral

CHANGELOG.md, designsafe/static/scripts/data-depot/controllers/projects.js, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js, designsafe/static/scripts/ng-designsafe/services/index.js, package-lock.json, package.json
Project breadcrumbs work with angular 1.6+ and no longer break when the user clicks them or refreshes the page.
Breadcrumbs are updated after each project/file listing by pushing to an RxJS subject kept in the data browser service.
=> DES-706: Update project breadcrumbs for Angular 1.6

designsafe/urls.py
Move route for RAMP verification file to the root of Designsafe, as requested by Maria.
=> move RAMP verification route to site root.

designsafe/apps/api/agave/filemanager/public_search_index.py
Make sure publication search only returns documents with status='published'. It looks like this filter got clobbered in a merge at some point.
This addresses ticket ID 48728
=> Don't return non-"published" publications in pubs search

designsafe/static/scripts/search/components/search-listing/search-listing.component.html
The issue here was that NEES projects in site search were being linked to through URLS formatted like:
`/data/browser/public/nees.public/{project_name}` 
when they should look like:
`/data/browser/public/nees.public/{project_name}.groups`
Clicking on NEES projects in site search should now link to the files for that project.
=> DES-727: Bug with search, does not link to right place on some NEES projects

designsafe/apps/djangoRT/views.py
Added a space between ticket body and new line in DjangoRT. This solution was implemented in [CEP](https://bitbucket.org/taccaci/core-exp-portal/pull-requests/163/ticket-body-newline-issue/diff) by Carrie Arnold and ported over to DesignSafe by me.
=> Ticket body newline issue

designsafe/apps/projects/models/agave/base.py
Fixed an issue that came up when editing the PI field on a project. It would cause a bunch of blank spaces to show up in the team management area.
=> Bug/DES-644 - Project PI Edit Issue

designsafe/static/scripts/data-depot/components/data-depot-new/data-depot-new.component.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.component.js, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.spec.js
- Fixed a bug where logged-out users couldn't refresh NEES projects or navigate to them by their URL.
-  Support old-style NEES project URLs (e.g. https://www.designsafe-ci.org/data/browser/public/nees.public//NEES-2009-0732.groups with the double slash)
=> task/DES-809: bug fixes in NEES publication view

README.md
`docker run -it --rm portal_django python manage.py test --settings=designsafe.test_settings` test_settings not found.
Solution was to add `.settings` to the --settings path
=> Modify Django tests --settings path

designsafe/static/scripts/data-depot/index.js
Needed to change `my-data` to `myData` otherwise searching My Data gives an unknown provider error.
=> Hotfix: typo in My Data search route

designsafe/libs/elasticsearch/utils.py
Trying do dedup while fixing the paths was giving weird transport errors when trying to delete things. Commenting out that line for now.
=> hotfix: comment out a line in the repair_paths util

designsafe/libs/elasticsearch/utils.py
I managed to delete the line that set `basePath` on indexed files before pushing the CEP indexer port. This fix replaces it.
=> bug/indexer-040119: Set basePath during standard indexing

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.js, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/index.js
1. Navigating from a personal project to the My Projects listing would not clear the project data stored in the DataBrowserService state. This would cause incorrect data to be displayed when clicking into a new project.
2. When users quickly browse between the Working Dir, Curation Dir, and Publication Preview there is a chance for the project entities to resolve twice resulting in duplicated experiments and categories. I've disabled the navigation buttons between these states while the data is loading.
3. Made some formatting changes in data-depot-nav
=> Task/DES-868(931) - Incorrect PI in project, and Duplicated Entities Fix

designsafe/static/scripts/data-depot/components/data-depot-browser/data-depot-browser.publications.component.html
This just deletes a breadcrumb element that wasn't doing anything.
=> task/DES-936: Remove empty breadcrumb bar from Publications

designsafe/apps/workspace/views.py
Need to remove `appDefinition` from `job_post` for aloe job submission to go through.
=> remove appDefinition from job submission for aloe

designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
1. Fixed an issue causing the title of experiments, simulations, and hybrid simulations to overflow.
2. We will now move the user into the curation directory after updating their project type
3. Empty categories will now show a unique message instead of "This folder has missing files!"
=> Task/DES-929(849, 932) - exp title overflow fix, mv usr to curation dir, and empty category msg

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-categories/pipeline-categories.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html
Clicking a link before would open it in a new tab, but subsequent clicks would open links into the already opened tab.
=> Task/DES-891 - Make links open in (separate) new tabs

designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js, designsafe/static/scripts/data-depot/components/files-listing/files-listing.public.template.html, designsafe/static/scripts/ng-designsafe/services/data-browser-service.js
- Capitalize the Clear button in Publication search filters
- Search in Publications now persists any user-selected filters. This is done by moving the filters into `DataBrowserService.currentState` so they are accessible after the state change.
=> task/DES-941 and task/DES-942: Persist publication filters on search

designsafe/static/scripts/workspace/controllers/application-form.js, designsafe/static/scripts/workspace/services/apps-service.js, designsafe/static/scripts/workspace/services/simple-list-service.js
- option can be hidden by adding the string `'hideProcessorsPerNode'` into an app's tags
=> fix/des 960:  Add processorsPerNode option for parallel apps

designsafe/static/scripts/search/components/search-listing/search-listing.component.html, designsafe/static/scripts/search/components/search/search.component.html
- Remove the ‘Created’ metadata at the bottom for publications.
- Put publication keywords above description, below DOI, so its consistent with how it’s displayed inside the publication
- "Author(s)" changed to "Authors" in NEES publications
- Change purple label on files to indicate that it shows the Last Modified date.
- Change "Help" link to be more noticeable by centering it and changing text to read "Help with Search"
=> task/DES-961: Tweaks to site search templates.

designsafe/apps/api/public_data/views.py, designsafe/apps/data/views/base.py
Non users who directly visited or were linked to published projects on DesignSafe would receive a 403 error when trying to preview project files.
Using the `csrf_exempt` decorator in the `DataDepotPublishedView` class did not seem to work, so I used it in the `PublicMediaView` instead.
=> Bug/DES-948 - Fix 403 caused by missing CSRF token in preview

designsafe/static/scripts/projects/components/file-categories/file-categories.component.js, designsafe/static/scripts/projects/components/file-category-selector/file-category-selector.js, designsafe/static/scripts/projects/components/file-category-selector/file-category-selector.template.html
Multiple files can now be selected and categorized in the projects area
Fixed an issue that did not update the removed categories once the "remove" button was clicked
=> Task/DES-896(674) - Allow multi file categorizations and fix "remove" button for categories

designsafe/apps/api/agave/views.py
Before, if you tried to access another user's My Data, we would check that user's files for anything you had Read permission for and display those. This is unintuitive/potentially insecure, so now My Data is locked to a user's own files.
=> task/DES-1006: Don't show files in other users' My Data

designsafe/celery.py
The crontab needs a `minute` argument.
=> bug/DES-1009: Limit project indexer to once per day

designsafe/libs/elasticsearch/docs/files.py, designsafe/libs/elasticsearch/utils.py
Fixes an infinite recursion in cases where the root of a storage system is indexed as a child of that same system. This is a feature of at least some legacy projects.
=> bug/DES-1072: Infinite recursion in indexer

designsafe/apps/api/agave/filemanager/public_search_index.py
From the stacktrace it seems as though elasticsearch does not like `publicationEnd` to be `'None'` as a string. This should fix that, but it's kinda ugly. LMK if you have a better idea for a solution.
=> Fix 'None' str publication end date

designsafe/static/scripts/projects/components/file-category-selector/file-category-selector.template.html
Fixing an issue that made the category selector appear as "Select a Collection" for project types other than Field Research
=> Bug/DES-1101 - Change category selector for appropriate project type

designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js
This change was making file navigation in the projects area fail. I think it was related to navigating search results, so we may have to double check something or set a conditional statement here.
=> Bug/DES-1104 - Fixing bug with file navigation in projects area

designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
It looks like files were redirecting and 404ing in the published area because they did not have the expected apiParams.
=> Task/DES-1111 - Change file apiParams for published area

designsafe/static/scripts/workspace/controllers/application-form.js, designsafe/static/scripts/workspace/services/apps-service.js
Sometimes a regex validation pattern defined in an agave app definition for an input or parameter is incompatible with javascript's regex validator. In this case, don't use the validator in order to preserve the form entry
=> bug/DES-1120: Don't use invalid regex in app form

designsafe/apps/workspace/views.py, designsafe/static/scripts/ng-designsafe/ng-designsafe.js, designsafe/static/scripts/workspace/controllers/application-form.js, designsafe/static/scripts/workspace/services/apps-service.js, designsafe/static/scripts/workspace/services/jobs-service.js
- Fixes processorsPerNode calculation.
- Accommodate missing defaults in app form.
- Overhauls maxRunTime field in app job submission form. Now strictly validates based on defaultMaxRunTime defined in the app, or the maxRequestedTime of the queue if no default given.
- Fixes a bug caused by blank inputs by removing them from the job submission.
- Suppresses uncaught exceptions on client side qProvider
=> bug/DES-1124: Fix bad field validation; Other App Form fixes

designsafe/apps/accounts/views.py, designsafe/apps/auth/tasks.py
Users were getting a misleading error message when confirming the email. Their email addresses were being confirmed in TAS, but an error message was telling them that the addresses weren't.
This was because of an unnecessary  `get_user_model` call that was causing an exception. This call has been removed 
I also improved some messaging, so that logs will show when a user's email account has been confirmed in TAS successfully.
=> bug/DES-1064 - Email Confirmation Erroneous Rejection Message

designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
removed conditional api params
`file.getMeta()` directs to a view that requires login. Replaced with `file.fetch()` which will use `PublicDataListView` instead.
=> Bug/DES-1146 - Fix 403 response from published file listing

designsafe/sitemaps.py, designsafe/urls.py
It can be a SEO problem to have the site map show pages without `www` but then have the server redirect those requests to `www` pages. Google is smart enough to see the redirect but the content can be considered duplicate or not authoritative. Updated the sitemap page URLs to include the `www` since that is how our server is configured to redirect all requests.
=> task/DES-1143 - Modify sitemap to use absolute path of each URL

designsafe/apps/api/projects/models.py, designsafe/apps/api/tasks.py, designsafe/apps/projects/models/elasticsearch.py
We needed to add some fields to support newer style projects. After merging, we'll need to run `python manage.py swap_reindex --index='projects'`.
=> bug/DES-1171: Update project model in elasticsearch

designsafe/apps/data/views/base.py, designsafe/sitemaps.py, designsafe/templates/base.html
**Description:**  
Update Canonical URLs on Published Project Templates to an absolute URLs to match the sitemap. Also updated the sitemap for NEES Published Project URLs to have on a single slash. This is to improve discoverability by Google.
**Migrations:**  
No migrations.
**Expected behavior:**
1. Canonical URLs on Published projects should be absolute URLs that match the URL of the published project. If you access the project by navigating through the portal, there may be a double slash in the URL before the Project ID. You can just remove one of those slashes to reach the actual URL of the project.
2. Sitemap should have a single slash after all published projects liste
=> task/DES-1165 - Update Canonical URLs on Published Project Templates

designsafe/sitemaps.py
Needed to move the break statement to pick up the last set of projects returned by the manager.
=> task/DES-818-2: Fix sitemap to catch all publications

designsafe/apps/data/templates/data/data_depot.html
Added conditional statement to title block that fills in 'Data Depot' when the page has no citation title.
=> Add "Data Depot" to Title Tags on Non-Publication Pages

designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html
- Fixed the citation button in Other
- Changed the published templates' `project.doi` to `publication.project.value.dois[0]`
Attaching script to update publications `teamOrder` with fname/lname if needed
```
from designsafe.apps.projects.managers.base import ProjectsManager
from designsafe.libs.elasticsearch.docs.publications import BaseESPublication
from designsafe.apps.api.agave import service_account
from django.contrib.auth import get_user_model
model = get_user_model()
projectIds = [] # add projectIds of new V2 "Other" publications
for pid in projectIds:
pub = BaseESPublication(project_id=pid)
prjnames = []
for usr in pub.project.value.teamOrder:
if not usr['guest']:
prjnames.append(usr['name'])
for u in prjnames:
x = [data for data in pub.project.value.teamOrder if data.name==u] …
```
=> Task/DES-1281 - Add first and last names of users to Other authors

designsafe/apps/data/models/elasticsearch.py
The field has already been added in dev/prod, this PR keeps the model in parity.
=> task/DES-1305: Add 'dois' field to IndexedPublications

designsafe/static/scripts/ng-designsafe/services/file-listing.js, designsafe/static/scripts/projects/components/file-categories/field-recon-file-tags.json, designsafe/static/scripts/projects/components/file-categories/file-categories.template.html
- When categorizing a folder we wanted the files within the folder to show that parent tag
- Also removed an extra "other" option from a list of selectable categories
Categorized File
**BEFORE**
**AFTER**
=> Task/DES-1252 - Show tags from parent directory on children

designsafe/static/scripts/data-depot/components/files-listing/files-listing.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-sim.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection.component.html, designsafe/static/scripts/ng-designsafe/services/project-service.js
- Created a check for the report/analysis entities. Reports and analysis are not required for publication, however if they are provided we need to ensure they have files categorized under them.
- Fixed a bug preventing the "no categorized files" from showing in certain listings.
- Fixed broken link for "how to move files into a project" in empty project listings
- Adjusted wording and display conditions for listings without data within projects
=> Task/DES-1277(1272, 1273) - Check provided report/analysis for files in selection area

designsafe/apps/data/views/base.py
Updated `get_context_data` to bring DOIs into metatags for new publications (`version: 2`).
=> DES-1297 - Add DOI Metatags for new Publication Templates

designsafe/apps/api/external_resources/googledrive/filemanager/manager.py, designsafe/apps/api/external_resources/googledrive/models/files.py, designsafe/static/scripts/data-depot/components/files-listing/files-listing.component.js
Phase 1 PR to just fix navigation into google drive subfolders. Breadcrumbs still need to be fixed.
- Minor formatting fixes in google drive manager
- Change `size` property to `length`, and add property `format` to Google Drive file object in order to display file size in data depot
- Google Drive File file path code improvements -- does not change returned value
- Gives `filePath` field a file id value in state router if `stateName === 'googledriveData'`, which changes the api listing call of a google drive directory to be the object id instead of a path, in order to list the directory contents
=> fix google drive navigate into folders

designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js
- Referenced Data, Instrument, and Observation Type have issues with displaying, adding, and removing fields correctly
- These fields will add blank inputs to metadata which become impossible to remove, and in some cases cause the collection to become stuck
We needed to make sure all invalid form inputs are cleared from the collection when saving and updating.
=> Task/DES-1321 - Fixing bugs in collections modal for FR

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.scss
Updated publication-preview styling
**Before**
**After**
_This image is at a different breakpoint_
=> Task/DES-1265: Multiple metadata values need to align top with the key, not align center

designsafe/apps/googledrive_integration/templates/designsafe/apps/googledrive_integration/disconnect.html, designsafe/apps/googledrive_integration/templates/designsafe/apps/googledrive_integration/index.html, designsafe/apps/googledrive_integration/templates/designsafe/apps/googledrive_integration/privacy-policy.html, designsafe/apps/googledrive_integration/urls.py, designsafe/apps/googledrive_integration/views.py
Per Google, we needed to add a specific Privacy Policy related to Google Drive access in our app:
https://developers.google.com/terms/api-services-user-data-policy
- Adds privacy policy for gdrive (/accounts/applications/googledrive/privacy-policy)
- Add links to privacy policy in google drive status screen (/accounts/applications/googledrive/)
Once this is released to dev and prod, we will need to resubmit the oauth consent form:
https://console.developers.google.com/apis/credentials/consent
=> DES-1294: Add google drive usage policy

designsafe/apps/projects/managers/publication.py
Need to keep the _ui data on the project in order to rebuild the project's entity diagram.
=> Task/DES-1363 (HotFix) - Prevent ui data from being removed from published project metadata

designsafe/static/scripts/search/components/search-listing/search-listing.component.html, designsafe/static/scripts/search/components/search-listing/search-listing.component.js
Tested using "Hurricane Michael" as query string.
This listing uses the UserService to grab user information and displays the first member.
=> Task/DES-1169: Search (site wide) - Projects Have Blank Author Field

designsafe/apps/api/external_resources/googledrive/models/files.py
encodes all google drive filenames as utf8
=> task/DES-881: Google Drive: encode file names as utf8

designsafe/static/scripts/projects/components/publication-citation/publication-citation.component.js
Replaced `this.auths` with values from coPis and PI fields instead of authors
Example shown uses [PRJ-1434](https://www.designsafe-ci.org/data/browser/public/designsafe.storage.published/PRJ-1434)
=> Task/DES-1364: Remove "Team Members" from Project Citations

designsafe/apps/data/templates/data/data_depot.html, designsafe/apps/data/views/base.py
Tested using PRJ-2537, PRJ-2621, and PRJ-2550. 
Author names are encoded into UTF-8 to avoid Django unicode encode error in characters like ó seen in author list of 2550.
=> Task/DES-1257: Author and Keyword Metatags on Publications

designsafe/apps/api/users/views.py, designsafe/static/scripts/data-depot/components/projects/index.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/modals/author-information-modal.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/modals/author-information-modal.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js
Replaced `ds-author-list` directive with series of anchor elements for contact information modals. Only uses object that has email and institution information.
=> Task/DES-1333: Create Author Information Modal

designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/scripts/projects/components/manage-field-recon/reports/manage-field-recon-reports.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html
Removed legend for red circle requirement marks and used flexbox column to position elements in `form-group` (Project Title, Principal Investigators (PI) in the below image).
In form elements without descriptions, put requirement label (`span` with bootstrap label class) inside `label` element (Experiment Facility, Experiment Type, and Equipment Type in below image).
=> Task/DES-1348: Modify Requirement Marks

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html
In addition to the FR publications, the filter was added to any author list that used to rely on the `ds-author-list` directive
=> Bug/DES-1403: Only display authors for each mission in FR publication

designsafe/tests.py, designsafe/urls.py, designsafe/views.py
URLs like the following were redirecting to the DesignSafe 404 page. They now redirect to a search page using the project ID in the url.
- https://nees.org/warehouse/experiment/3322/project/685
- https://nees.org/warehouse/hybrid/4176/project/71
- https://nees.org/warehouse/project/666
This was tested using the links in [this document](https://engineering.purdue.edu/IISL/Publications/Technical%20Reports/IISL_Report_008.pdf).
Additionally, test coverage has been added for the redirect view.
=> Bug/DES-895: NEES URLs are forwarding to malformed DesignSafe URLs

designsafe/static/scripts/applications/controllers/application-tray.js, designsafe/static/scripts/applications/html/application-tray.html
`_.chunk` is used to create separate pages to render in the bootstrap tabs for the applications.
Each page has 12 apps.
All of the apps are searchable regardless of what page the user is viewing.
=> Task/DES-724: Paginate Applications builder page

designsafe/apps/api/agave/views.py, designsafe/settings/common_settings.py
This will allow User Services to differentiate between a preview of a file and a download.  It also updates the logs with the IP of the request.
=> task/DES-1284 - Logging for Previews of files

designsafe/static/scripts/data-depot/components/data-depot-listing/files-listing.template.html
updated files-listing template for pagination and removing sorting by item type for now
This affects the My Data listing, files listing within a project, and potentially a file listing within a publication (though I have not tested that last one).
If you are on Keith's Walk Experiment Demo project, I copied my lotsoftestfiles directory into that project to test the pagination there, so that's available to anyone for testing as well.
=> task/DES-935: fixing My Data file listing pagination

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.scss
This PR adds a CSS class to align the `td` within the collapse buttons.
=> Task/DES-1420: Collection and Mission title text needs to be center aligned

designsafe/apps/api/projects/views.py, designsafe/apps/api/tasks.py, designsafe/apps/projects/managers/publication.py, designsafe/static/scripts/data-depot/components/projects/pipeline-team/pipeline-team.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
**NOTICE: This should be merged with task/DES-1358**
This fix adds a "path" to the file tag object within a project/entities' metadata. A task was added to fix newly created tags and older tags without the "path" when a project is published. Lastly, there was a bug fixed with other publications not saving the "dois" field when proceeding through the pipeline.
=> Task/DES-1079 - Update UUIDs of file tags for published files

designsafe/static/scripts/projects/components/manage-experiments/experimental-data.json, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js
This is a hack to remove two dropdown options defined in a .json form. We can't delete the field from the .json because the existing published Experiments which selected this option will break. This .json file is referenced by both published and non published projects... Fixing this correctly will require updating all previously published experiments, as well as updating the way these fields are saved (so we don't reference a .json for both published and non published projects). At the time I've submitted this, I do not have access to modify published metadata locally, and there is an important user waiting for this change. I'll be making a ticket to fix the underlying issue.
=> Bug/DES-1404 - Remove field from experimental-data.json

designsafe/apps/api/agave/views.py
The search manager was getting passed a parameter via kwargs that it didn't want.
=> bug/DES-1456: Fix Shared With Me listing

designsafe/apps/data/apps.py, designsafe/apps/data/management/commands/swap_reindex.py, designsafe/apps/search/tasks.py, designsafe/celery.py, designsafe/libs/elasticsearch/indices.py, requirements.txt
This is another weird legacy choice that could be contributing to timeouts.
=> Task/des 1480: Update CMS index non-destructively and only once per day.

designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js
Pretty important bug fix. Will not allow FR projects to publish without a report.
A previously required field was not being checked for at the end of the pipeline and with it omitted it will cause a missing key error when generating the parameters for a publication request.
=> BUG/DES-1515 - Fix obj w/ missing key error for FR

designsafe/apps/projects/models/agave/base.py
A quick fix for v1 projects. The larger issue has been moved into Task/DES-1456
The early v1 projects are sharing the same project class with the v2 projects. The old and new versions of the projects metadata schema are almost the same except for the `award_numbers` field:
```
v1_award_numbers = 'ABC_123'
v2_award_numbers = [{'order': 0, 'name': 'ABC_123'}]
```
The `award_number` (character field) from v1 has been adapted in a few places to fit to the newer v2 project schema of `award_numbers` (list of objects) when it's needed.
This will fix the 500 error causing the v1 publications not to load, but I feel like this should be resolved at the same time as this issue:
https://jira.tacc.utexas.edu/browse/DES-1465
Getting the `award_numbers` fields to match between the old and new project …
=> Bug/DES-1529 - Fix data type issue causing v1 publications to 500 error

designsafe/settings/common_settings.py, designsafe/settings/test_settings.py
With dtn01 going out of commission soon, we need to update our hosts on project systems going forward to point to cloud.corral.
Using the `tg458981` service account, the key pair in the [TACC Keys Service](https://github.com/TACC-Cloud/ssh-keys-client/tree/master/tacc-keys) can auth against cloud.corral on behalf of `tg458981`
To test:
Create a new project, and confirm all file operations succeed.
=> task/DES-1508: Move future project systems from dtn01 to cloud.corral

designsafe/static/scripts/ng-designsafe/services/project-service.js
A conditionally required entity type (social science or geoscience) was being returned incorrectly in an error message sent back to users even if they had the minimum requirements.
If a mission is published it must have:
- Planning Set
- Social Science OR Geoscience Set
- Files within all Sets
=> Bug/DES-1582 - Filter conditionally required field from error message

designsafe/static/scripts/data-depot/components/modals/nees-doi-list.component.js
There's a bug where the `.map` function is expecting authors, but not all of these experiments have authors.
You can test with this project:
https://designsafe.dev/data/browser/public/nees.public//NEES-2010-0946.groups
=> Bug/DES-1590 - Fix bug with All Citations button for NEES publications

designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/data-depot/components/published/published.component.js, designsafe/static/scripts/projects/components/publication-download/publication-download.template.html
You can test these changes here:
https://designsafe.dev/data/browser/public/designsafe.storage.published//PRJ-1640
Changes Include:
Added download publication modal to v1 publications (publications older than v2, but not NEES)
The download button is in the same position as v2 publications, It should have the same functionality. I do not have archives created for the rest of the v1 publications, but they can be easily added to corral.
=> Task/DES-1596 Add download publication button to v1 publications

designsafe/apps/licenses/models.py
This fixes the infinite recursion happening when rendering the `str` representation of the model in the admin panel list view for a license. After moving to python 3, the `str` function handles what `unicode` did to represent the model item string representation in the admin panel.
=> fix/DES-1618: Fix str recursion bug for licenses

designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-privacy-agreement.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-publish.component.js, designsafe/static/scripts/projects/components/manage-categories/manage-categories.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
**Issue:**
Added a loading spinner and adjusted the publication submission modal so that users could not publish their project if it was already published.
Fixed some smashed submission buttons for entity modals and publication submission modal
**To Test:**
- Within each project (except other) in the **Curation Directory** we have modals for adding experiments, collections, simulations etc. The green buttons there appear smashed to one side currently. You should see that those are no longer smashed.
- If you would like to test the publication submission modal you can use any of the "walk" projects (if you don't see them I can invite you to them). Go to publication preview>continue>select a publishable entity (there should be at least one in each set) continue all the way down the pipeline …
=> Bug/DES-1603 - Fix ui elements and issue with publication submission

designsafe/apps/data/models/elasticsearch.py, designsafe/settings/elasticsearch_settings.py
Legacy NEES files were indexed using their own schema and need their own index now. 
The call to `_reindex` should be formatted: 
```
{
"source": {
"remote": {
"host": "http://designsafe-es01.tacc.utexas.edu:9200"
},
"index": "des-files",
"query": {"match": {"systemId": "nees.public"}}
},
"dest": {
"index": "designsafe-production-files-legacy"
}
}
```
=> task/DES-1624: Add index for legacy NEES files

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/edit-project/edit-project.component.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
This PR will fix bugs with the awards, related works, and data type (other projects) fields. There were several issues related to these fields:
- Could not add an additional awards field in the modal
- Could not remove awards/related works fields by deleting their contents (not using the remove button)
- Data Type for "Other" project types was not required and causing issues with the publication listing.
- Related Works field was not hiding properly when there were no related works for publications
=> Bug/DES-1627 - Edit project modal fix for awards, works, and data type

designsafe/static/scripts/rapid/controllers/rapid-main-ctrl.js, designsafe/static/scripts/rapid/html/index.html
This PR adds a method to clear filter text on click of the trash icon. It can be tested locally [here](https://designsafe.dev/recon-portal/).
=> Bug/DES-1551: Delete button on filter in recon portal does not appear to work

designsafe/static/scripts/data-depot/components/projects/publication-preview/modals/author-information-modal.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/modals/author-information-modal.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js
This PR fixes two bugs.
1) DES-1540: The `author` data is passed in to the modal component and then the orcid id is fetched from the back-end. Prior to this, the modal was only opened once the `UserService` promise was resolved.
2) DES-1597: Since the modal is triggered by an `ng-click` directive with '#' inside the href tag, the page was scrolling to the top. `href="javascript;;"` keeps the tag valid and stops the issue
=> Task/DES-1540 & Bug/DES-1597: Author Modal Fixes

designsafe/apps/rapid/migrations/0001_initial.py
Rapid initial migration failing locally, and is unneeded, so removing the call to custom script form the migration.
=> removing call to custom script from rapid initial migration

designsafe/apps/data/templates/data/data_depot.html, designsafe/apps/data/views/base.py, designsafe/static/scripts/data-depot/components/nees-publication/nees-publication.component.js, designsafe/static/scripts/data-depot/index.js, designsafe/static/scripts/data-depot/services/published.service.js
In this PR, metatags for project sub entities are populated from the client side (`PublishedService`) and back-end templates. 
From the back-end, Reports were added to the template and on the front-end, metatags can be populated between `ui-router `state changes.
=> Task/DES-1632: Create meta tags for publications with multiple DOIs

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.scss, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/file-category-selector/file-category-selector.template.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
1516: Changed dropdown text
1526: Various experiment template fixes (license icon display, other values)
1539: Centered modal
=> Task/DES-1678: Curation Quick Fixes (1516, 1526, 1539)

designsafe/static/scripts/data-depot/services/published.service.js
This can be tested using [this publication](https://designsafe.dev/data/browser/public/designsafe.storage.published//PRJ-2290) locally. The `updateHeaderMetadata` method now adds reports to the header if they are published. 
In prod, as seen [here](https://designsafe-ci.org/data/browser/public/designsafe.storage.published//PRJ-2290), the publication gets stuck on loading.
=> Fix Simulations Not Rendering

conf/env_files/designsafe.sample.env, designsafe/apps/auth/tasks.py, designsafe/settings/common_settings.py, designsafe/settings/test_settings.py
removed list wrapping to send to new user alerts to multiple email addresses.
=> DES-1717 - Add multiple users to email notifications to add new users to Slack

conf/env_files/designsafe.sample.env, designsafe/apps/auth/tasks.py, designsafe/settings/common_settings.py, designsafe/settings/test_settings.py
The `NEW_ACCOUNT_ALERT_EMAILS` environment variable was being cast as a string, so we do away with the array and use commas to separate the emails.
=> Fix alert email. Uses a string instead of a list, 'cause of env var fun

designsafe/static/scripts/ng-designsafe/services/project-service.js
Updated minimum requirements for a Field Research project to be publishable.
A Field Research project needed either a single report, or a mission with a **planning set** and either a **social science set** or **geoscience set**
A Field Research project needs either a single report, or a mission with **any** one collection type.
You can test this by creating a mission in an FR projects with a single collection of any type and trying to advance past the first step in the publication pipeline "Selection" If you are missing files or if you do not have at least one collection in your mission, you should see an error.
=> Task/DES-1716 - Update minimum requirements for FR projects

designsafe/static/scripts/projects/components/project-tree/project-tree.component.js
Fixing a bug which prevents Field Research projects from being able to sort their entities in the "Relate Data" modal. If the project does not have any missions, the `initiateEntityOrder` function would not be triggered.
=> Bug/DES-1674 - Fix bug with FR ordering in "Relate Data" modal

designsafe/apps/api/projects/urls.py, designsafe/apps/api/projects/views.py, designsafe/apps/api/tasks.py, designsafe/settings/common_settings.py, designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-publish/pipeline-privacy-agreement.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.html, designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/ng-designsafe/services/project-service.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.component.js, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.template.html
The **Project Overview** appears after creating a new project, editing a project's type, or visiting the project overview.
1. Updated the User Guidelines for storing and publishing Protected Data (PII)
2. Added additional overview slides for Field Research
3. Added task to generate notification email for project admins when PII is going to be published (part of overview)
4. Fix various bugs in the UI which prevented the Project Overview from appearing in the Working Directory and Curation Directory
1. Open an empty project (or one you do not care about completely erasing).
2. Click **Edit Project** at the top of the page.
3. Click **Edit Project Type** near the top of the modal. (this will load the Project Overview)
4. Select a radio button for a project type (note: Hybrid Simulation and …
=> Task/DES-1708(1714, 1581) - Project Overview Updates and updated PII Policy Guidelines

designsafe/apps/api/external_resources/box/filemanager/manager.py, designsafe/apps/api/external_resources/dropbox/filemanager/manager.py, designsafe/apps/api/external_resources/googledrive/filemanager/manager.py, designsafe/apps/api/tasks.py, designsafe/apps/dropbox_integration/models.py, designsafe/apps/dropbox_integration/views.py
This is at least one of the things that's breaking transfers in External Resources. These operations depend on having Corral mounted so they can't be tested locally.
=> Hotfix: fix dropbox oauth flow and stop unnecessary decoding of external resources file paths

designsafe/apps/api/projects/views.py, designsafe/apps/api/tasks.py
When the user clicks Request DOI & Publish, an additional task has been added to the publish chain that notifies the user that the project is being prepared for publication.
=> Task/DES-1286: Send user email immediately after clicking Request DOI & Publish

designsafe/apps/api/tasks.py, designsafe/apps/api/tasks_unit_test.py, designsafe/celery.py
- Rewrite the projects indexer to make ~99% fewer Tapis and Elasticsearch calls.
- Fix bug where empty date objects would cause indexing to fail.
=> task/DES-1587: Fix projects indexer

designsafe/apps/projects/managers/publication.py
Fixed an issue preventing awardNumber(s) from being saved to the published metadata for all project types.
=> Task/DES-1655 - Fix awardNumber issue in the publication process

designsafe/apps/api/tasks.py, designsafe/apps/projects/managers/publication.py
Other publications do not have entities, and when they are being published part of the publication task chain will fail silently and prevent the publication status from being set correctly.
=> Task/DES-1752 - Fix publication status update issue with other publications

designsafe/apps/api/projects/views.py, designsafe/apps/api/publications/operations.py
Publication objects are failing to save initially because of a couple typos
- `datetime` module is not imported
- `self` parameter of `save_publication` operation is not used and throwing off input parameters
* [DES-1783](https://jira.tacc.utexas.edu/browse/DES-1783)
1. You can test this on one of the test publications "walk other demo" if needed. Shell into Django container locally
```
from designsafe.apps.api.publications.operations import save_publication
pub = {
"license":{"datasets": "","software": "", "works": "Creative Commons Attribution Share Alike"},
"project":{"uuid": "{{prj-uuid}}", "value": {"projectId": "{{PRJ-XXXX}}"}}
}
pub = save_publication(pub, 'saving')
```
Should not have an error and should save the publication.
=> Bug/DES-1783 - Fix issue with saving initial publication object

designsafe/apps/api/datafiles/operations/agave_operations.py
Perform a listing before each call to the postits API in order to ensure that the permissions are correct.
=> hotfix/20201009-postit-href: Always list files before creating postits

designsafe/apps/data/tasks.py, designsafe/libs/elasticsearch/utils.py
- Use correct queue for the recursive indexing (previously recursive calls were being put in the "default" queue)
- Tweak `walk_levels` method to reduce Agave calls by ~50%.
=> task/DES-1785: Use correct queue for recursive indexing

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-move/data-browser-service-move.component.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-rename/data-browser-service-rename.template.html, designsafe/static/scripts/ng-designsafe/services/file-operation-service.js
We want to prevent users from moving or renaming files that are categorized to an entity or contain files that are categorized to an entity. If this happens project will become unresponsive and requires manual effort to fix.
This check will only take place when moving/renaming from the My Projects area. With these changes we will request entities for the project and check that the file path(s) to be move/renamed are not among them. To test this feature, go into any project and try to move/copy files. If there are categories associated to the files you should be notified.
=> Bug/DES-1737 - Prevent move and rename of files containing categorized data in projects

README.md
N/A
Added instructions for adding ca-certificates on Fedora/RHEL/CentOS linux distributions. 
1. Install a Red Hat-based linux distribution.
2. Follow the instructions on `README.md`.
3. `openssl verify $PROJECT/conf/nginx/certificates/ca.pem`
N/A
Followed [Fedora's official documentation](https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/#proc_adding-new-certificates) and a [Red Hat tutorial](https://www.redhat.com/sysadmin/ca-certificates-cli) for reference.
=> Add instructions on installing CA certificates on Fedora/RHEL/CentOS

designsafe/static/scripts/data-depot/components/data-depot-listing/data-depot-listing.component.js, designsafe/static/scripts/data-depot/components/data-depot-listing/files-listing.spec.js, designsafe/static/scripts/data-depot/components/data-depot-listing/files-listing.template.html
* [DES-1721](https://jira.tacc.utexas.edu/browse/DES-1721)
* Added the message, "Trashed items will be kept a maximum of 90 days", between the breadcrumb and file-listing of My Data. 
* Added a basic test to see if the message appears in specified paths.
1. Run `npm run test` and see if tests pass.
2. Go to "My Data" from "Data Depot"
3. If there is no ".Trash" create a folder and move it to trash.
4. Go to the ".Trash" directory or any of its subdirectories.
5. Confirm that the message appears.
6. Go to "My Projects" from "Data Depot"
7. Create a Project if there is none.
8. If there is no ".Trash" create a folder and move it to trash.
4. Go to the ".Trash" directory or any of its subdirectories.
5. Confirm that the message appears.
I wasn't sure if it was ok to put this directly inside …
=> DES-1721 - Add informative message inside trash directories.

designsafe/apps/applications/views.py
If we don't provide a `sessionId` to `metrics.info` then the logger throws an error internally.
=> task/DES-1803: Fix logging in applications call_api view

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js
Fixed a few typos and bugs preventing the hybrid simulation publication types from rendering correctly.
* [DES-1830](https://jira.tacc.utexas.edu/browse/DES-1830)
Fixed a few issues:
1) We were trying to get file object info from an entity does not have files categorized to it.
2) There are some entities that are not required and will show up as "undefined".
3) There was a typo in the spelling of hybridsimulation_set which was also causing issues.
1. Update your local publications index so that you can see the latest hybrid simulation publication
2. Check that the publication renders correctly (PRJ-1634: Aeroelastic Real-Time Hybrid Simulation - A New Concept for Wind Engineering Testing)
=> Bug/DES-1830 - Fix hybrid_sim publications

designsafe/static/scripts/data-depot/components/published/published.component.js
Mediaurl param was causing issues with the publication download modal.
* [DES-1847](https://jira.tacc.utexas.edu/browse/DES-1847)
1. open up an older publication from around early 2018-2017 and check that the "download dataset" button opens the modal in the top right
=> Task/DES-1847 - Fix issue with download modal for v1 projects

designsafe/static/scripts/projects/components/project-tree/project-tree.component.js
Before the other collection types were created, there was just a generic "collection" that was categorized under missions for FR projects... Since there were some published projects using this older model, we need to support the display of those collections in the relationship tree. You can use this existing publication to test the view:
https://www.designsafe-ci.org/data/browser/public/designsafe.storage.published//PRJ-2440
**Note:** Mission and Collection ordering was not available when these projects were published, so you should see things categorized correctly, but the order may not match 100% to the published view.
* [DES-1542](https://jira.tacc.utexas.edu/browse/DES-1542)
1. Check the Field Research relationship Tree for older FR publications. Here is one: …
=> task/DES-1542 - Support old collection type for FR projects in relationship tree

designsafe/apps/projects/models/agave/base.py
Google needs either "name" or "url" to be specified for the license in Dataset search tags. I'm adding urls and making sure that all license types are being picked up.
* [DES-1834](https://jira.tacc.utexas.edu/browse/DES-1834)
- Created a modular `generate_licenses` function
- Added urls for each type of license
View the page source for each of these publications
1. Open Data Commons Attribution -  PRJ-2971
2. Open Data Commons Public Domain Dedication - PRJ-2534
3. Creative Commons Attribution Share Alike - PRJ-2982
4. Creative Commons Public Domain Dedication - PRJ-2519
5. GNU General Public License - PRJ-2938
Creative Commons Attribution Share Alike publications seem to not render locally in either this branch or master
=> task/DES-1834 - Add license URLs to Google Dataset meta tags

designsafe/static/scripts/applications/controllers/application-edit.js, designsafe/static/scripts/ng-designsafe/ng-designsafe.js, designsafe/static/scripts/workspace/services/simple-list-service.js
This is a quick fix to rename some app categories per the DES-1836 task. A future PR will come that further decouples app categories from the deployed code, and allows for dynamic app category population.
* [DES-1836](https://jira.tacc.utexas.edu/browse/DES-1836)
1. Once deployed to dev, we can publish test apps to these new categories, which will appear in the apps tray.
=> task/DES-1836: Rename app categories

designsafe/static/scripts/applications/controllers/application-edit.js, designsafe/static/scripts/ng-designsafe/ng-designsafe.js, designsafe/static/scripts/workspace/services/simple-list-service.js
Addendum to https://github.com/DesignSafe-CI/portal/pull/848.
Accommodate deprecated app category names by interpreting an existing app with an old category to be categorized to the new category.
* [DES-1836](https://jira.tacc.utexas.edu/browse/DES-1836)
1. When testing in dev, all existing apps should auto populate to their new respective category.
=> task/DES-1836 Addendum: Accommodate previous category names

designsafe/static/scripts/data-depot/components/projects/index.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-other.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-selection/pipeline-selection-other.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-changes.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/index.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
Created some of the basic views for the publication, versioning, and amends pipeline.
* [DES-1859](https://jira.tacc.utexas.edu/browse/DES-1859)
I created separate component controllers for the starting view, versioning, and amend sections of the publication pipeline. The state changes should all work, but various bits of functionality can be added in now if this looks fine.
1. Go to any project type (other if you want to see the versioning/amends views) and navigate past the publication preview.
=> Task/DES-1859 - Create component/templates for versioning and amends pipeline

designsafe/apps/api/projects/views.py, designsafe/apps/api/publications/operations.py
If a `revisionText` parameter is passed in the POST body of the publication view, it will be added to the publication model in Elasticsearch.
1.
=> Task/des 1887:   Add revision text to post body

bin/run-celery-debug.sh, bin/run-celery.sh, requirements.txt
* [DES-1905](https://jira.tacc.utexas.edu/browse/DES-1905)
1. Rebuild container with `docker-compose -f conf/docker/docker-compose.yml build`
2. Bring up the portal and run `celery -A designsafe inspect active_queues` inside the `des_django` container. There should be 4 queues and 2 nodes online.
=> task/DES-1905: bump Celery version and use unique hostnames for workers.

designsafe/apps/projects/models/agave/base.py
Some of the metadata is being submitted to Datacite with incorrect mapping.
* [DES-1236](https://jira.tacc.utexas.edu/browse/DES-1236)
This should make the metadata passed to Datacite correctly cite multiple DOIs and multiple award numbers in publications.  I followed all_data_models_mapping_fedora_2021 in DES-1666.
1. Pick a publication that has multiple DOIs and Awards.  I used PRJ-2864
2. Open the DS Django shell locally
3. Run 
```
from designsafe.apps.projects.managers.base import ProjectsManager
from designsafe.apps.api.agave import service_account
manager = ProjectsManager(service_account())
project = manager.get_project_by_id("PRJ-XXX")
project.to_datacite_json()
```
=> task/DES-1236 - Corrections for passing metadata to DataCite

designsafe/settings/common_settings.py, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search.component.js, designsafe/static/scripts/data-depot/components/modals/nees-doi-list.template.html, designsafe/static/scripts/projects/components/edit-project/edit-project.component.js
This PR fixes 2 issues that have outstanding tickets associated with them.
Testing instructions:
1. Go to https://designsafe.dev/data/browser/public/nees.public/NEES-2009-0707.groups and click "view all DOIs".
2. Make sure that the DOI links in the modal work correctly..
=> bug/DES-1928: Fix typo in NEES citation modal and add .sas to previewable filetypes.

CHANGELOG.md, designsafe/apps/api/publications/operations.py, designsafe/apps/api/tasks.py, designsafe/apps/data/models/elasticsearch.py, designsafe/apps/projects/managers/publication.py, designsafe/libs/elasticsearch/docs/publications.py, designsafe/libs/elasticsearch/utils.py
…ying on the default
Elasticsearch sniffing errors are much too frequent on the worker machine to rely on the `default` client in the publication pipeline. Until we can investigate and resolve this issue, the best course of action is to instantiate new Elasticsearch clients at each step of the publication pipeline, which eliminates the need to maintain long-lived TCP connections.
* [DES-1926](https://jira.tacc.utexas.edu/browse/DES-1926)
- Add a `new_es_client()` method to the Elasticsearch utils library to instantiate new clients.
- Update methods in `IndexedPublication` and `BaseESPublication` to support passing in a custom client (defaulting to `default`).
- Update publication pipeline methods to use new ES clients instead of `default`.
1. In local dev, try publishing a project and …
=> task/DES-1926: Instantiate ES clients a-la-carte in the Publication Pipeline

designsafe/static/scripts/workspace/components/workspace-data-browser-file-listing/workspace-data-browser-file-listing.template.html, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
This should fix the issue with the left align "Add" button in the Data Depot while also keeping the left alignment of the file links in the workspace listing.
* [DES-1935](https://jira.tacc.utexas.edu/browse/DES-1935)
1. Check the Data Depot that the blue Add button on the left has center aligned Text
2. File links in the Workspace should still be left aligned
=> Task/DES-1935 - Fix text position issues for data depot add button and workspace file links

designsafe/apps/api/projects/views.py, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-changes.template.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
There are several areas in the portal that need to disabled while projects are in the process of being published. This can be picked up by checking the status of the publication object.
Disable submit buttons and force users out of the publication/amend/version pipelines after submitting
Prevent users from entering the pipeline if status is "publishing"
Prevent users from selecting the latest version of a publication if that version's status is "publishing"
* [DES-1969](https://jira.tacc.utexas.edu/browse/DES-1969)
=> Task/DES-1969 - Disable some features while a project is publishing

designsafe/apps/api/datafiles/operations/agave_operations.py, designsafe/settings/common_settings.py, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.html, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js, designsafe/static/scripts/ng-designsafe/services/file-operation-service.js
Adds preview and link (to HazMapper) for `<map_uuid>.hazmapper` files.
* [DES-1936](https://jira.tacc.utexas.edu/browse/DES-1936)
Added to `agave_operations.py` for processing `.hazmapper` files.
Added iframe preview for `.hazmapper` files and a button to open in HazMapper. 
1. Run HazMapper/Geoapi locally (have to change default port 8000)
2. Create a file with a project's uuid + .hazmapper
3. For now, you have to change the hazmapperHref in `data-browser-service-preview.component.js` and `agave_operations.py` to `'http://localhost:4200/project/' + uuid;` rather than the production server.
4. Confirm link and iframe loads.
Tested against HazMapper's master branch (the project routes aren't in production yet, they will be there really soon). 
Also, we aren't sure how to handle …
=> Task/DES-1936 HazMapper Preview/Link

designsafe/static/scripts/workspace/components/workspace-data-browser-project-listing/workspace-data-browser-project-listing.template.html
The "Project Name" and "Project ID" column headers in the Workspace data browser needed to be switched
[DES-1995](https://jira.tacc.utexas.edu/browse/DES-1995)
The "Project Name" and "Project ID" column headers needed to be switched
1.  Check out the data browser in Workspace
2. Make sure the headings of each column are correct.
=> task/DES-1995 - Fixed data browser headings for project

designsafe/apps/projects/managers/publication.py, designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
Subsequent versions of a publication would not correctly update the file uuids for the file tags in a project.
We needed to adjust a regex pattern in the file listing for publications as well as update a base path being used when attempting to correct the file uuid being updated in the publication/versioning process.
* [DES-1976](https://jira.tacc.utexas.edu/browse/DES-1976)
1. You'll have to copy your project files into a versioned directory you want to test on corral. For example: you would copy the files (which have tags in your project to /published/PRJ-1234v2)
2. When those files are copied shell into the django container running locally and run the following task 
`from designsafe.apps.api import tasks` 
`tasks.swap_file_tag_uuids('PRJ-1234', revision=2)`
3. Check your publication …
=> Task/DES-1976 - Fix missing file tags for versioned publications

designsafe/static/scripts/data-depot/components/projects/project-view/project-view.component.js, designsafe/static/scripts/projects/components/manage-project/manage-project.component.js, designsafe/static/scripts/projects/components/manage-project/manage-project.template.html
This PR fixes some bugs related to projects with "None" set as a project type (newly created projects). 
* [DES-1990](https://jira.tacc.utexas.edu/browse/DES-1990)
1. Fixed up loading/submitting conditions for project management modal (all projects)
2. Fixed modal freeze when saving new users (none projects)
3. Fixed redirect when selecting curation/publication preview (none projects)
1. Create and update a project using the project management modal (all projects). This should display a "saving" or "creating" message and disable the form
2. Attempt to add a user to a project with no project type set
3. From within a project with no project type set, select the curation and publication preview buttons. These should open the "Manage Project" modal.
=> Task/DES-1990 - Bug fixes for None projects and project management modal

designsafe/static/scripts/data-depot/components/published/published-view.component.js
Infinite scroll was broken in listings inside of a publication due to an unnecessary abstract listing that was being performed. This PR removes the call to do that listing.
* [DES-2018](https://jira.tacc.utexas.edu/browse/DES-2018)
1. Try infinite scroll in a directory listing inside a publication, e.g. https://designsafe.dev/data/browser/public/designsafe.storage.published/PRJ-2421/Building%20Modelling
=> bug/DES-2018: Fix infinite scroll in publication filenav.

designsafe/apps/projects/managers/datacite.py, designsafe/apps/projects/models/agave/base.py
For a while now, type Other publications have been failing to complete the publication process. Their DOI status failed to update to "published" on DataCite due to a failing API post, and this led to some other issues as a result.
This change fixes a couple typos in the JSON attributes passed to DataCite
* [DES-2015](https://jira.tacc.utexas.edu/browse/DES-2015)
Fixed a couple typos related to the award information and removed an unused date field.
=> Task/DES-2015 - Fix issues with failing type other publications

designsafe/apps/api/datafiles/operations/box_operations.py
The Weblink (Bookmarks) document type in Box does not have a `size` attribute, so we'll ignore that for these file types.
* [DES-2069](https://jira.tacc.utexas.edu/browse/DES-2069)
1. Go to https://designsafe.dev/data/browser/box/ and ensure the listing doesn't fail
=> bug/DES-2069: Support weblink in Box listings

designsafe/static/scripts/projects/components/publication-download/publication-download.component.js
Utterly massive PR to fix Publication Archive downloads for versioned publications
* [DES-2076](https://jira.tacc.utexas.edu/browse/DES-2076)
swapped the old `r2(3,4,5...)` iterator to `v2(3,4,5...)` for the download link.
1.  Try to download a published archive of a versioned publication
=> Task/DES-2076 - Fix Bug with Archive Download Link

designsafe/static/styles/ng-designsafe.css
"While scrolling through files in the Data Depot, if a user reaches the end of what is loaded before infinite scroll loads more files, the page will scroll down to the footer and move the toolbar out of view. The user then has to move their mouse out of the files and scroll the page back up to view the toolbar and other navigation."
This PR adds a CSS attribute that Wesley uncovered that prevents the page from scrolling when the user reaches the bottom.
* [DES-1949](https://jira.tacc.utexas.edu/browse/DES-1949)
1. Scroll to the bottom of a file/publication listing and confirm that the surrounding page doesn't scroll further upon reaching the end.
=> Task/des 1949:  Fix overscroll behavior

designsafe/apps/api/publications/search_utils.py, designsafe/static/scripts/data-depot/components/data-depot-listing/publication-advanced-search/publication-advanced-search.component.js
- Change the dropdown filter "Custom" to "Other"
- This Other Data Type (formerly Custom) filter needs to display all Data Types that users wrote in themselves
- Add "Check Sheet" as a predefined piece of metadata to the list of Data Types
* [DES-1942](https://jira.tacc.utexas.edu/browse/DES-1942)
1. In Advanced Search, check "other" and select "check sheet" and "other" in the dropdown. "check sheet" should return checksheet projects and "other" should return a bunch of projects with "other"/"none" or custom types.
=> task/DES-1942: Add Other and Check Sheet options to advanced search dropdown

designsafe/settings/common_settings.py, requirements.txt
Hedda/CMD have requested the DjangoCMS Snippets plugin to be enabled.
* [DES-2113](https://jira.tacc.utexas.edu/browse/DES-2113)
1. run `docker exec -it des_django python manage.py migrate`
2. Go to a cms page, edit the page, and add a snippet
3. Confirm it succeeds and there are no errors
=> task/DES-2113: Add `djangocms-snippet` plugin

designsafe/apps/api/projects/views.py
* [DES-2117](https://jira.tacc.utexas.edu/browse/DES-2117)
Add metrics logging so that viewing a publication's abstract listing (by navigating to that publication) is logged as a listing of that publication's root directory.
1. Navigate to a non-Other type publication and inspect the logs in Docker.
=> Task/DES-2117: Log abstract publication listings in metrics

designsafe/apps/nco/managers/projects.py, designsafe/static/scripts/nco/components/nco-scheduler-filters/nco-scheduler-filters.component.js, designsafe/static/scripts/nco/components/nco-scheduler-filters/nco-scheduler-filters.template.html, designsafe/static/scripts/nco/components/nco-scheduler/nco-scheduler.component.js
Users were confused by the default view and could not easily figure out
how to see what is happening right now in the facilities.  They were being
presented by default with the full history of all projects in all facilities,
sorted from newest to oldest, causing projects scheduled a year or more into
the future to be the first thing displayed when they load the page.
This change replaces the menu of "start date"-based filters entirely with 
a simple checkbox to show or hide projects that are already completed.  
It also reverses the default ordering from "newest first" to "oldest first".
Applying the new "hide history" filter and reversing the sort order by default 
on page load will mean users are now presented immediately with a view
of projects that is more in-line with expectations:
* …
=> Replace "start date" filters with simple show/hide history toggle.

designsafe/static/scripts/data-depot/components/projects/_common/hazmapper-maps/hazmapper-maps.component.js, designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js
Make HazMapper map links when opening files more defined and dynamic by utilizing the new `deployment` field in the saved file.
* [DES-2149](https://jira.tacc.utexas.edu/browse/DES-2149)
Changed handling of the hazmapper file in [data-browser-service-preview.component.js](https://github.com/DesignSafe-CI/portal/blob/cf26bc0a822dbe4696c41d27a8396d16670f5bb6/designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-preview/data-browser-service-preview.component.js#L61).
1. Try creating a file in https://hazmapper.tacc.utexas.edu/staging/ go to `Manage` (in the left-hand panel) and click `Save`.
2. Click on the file that you saved and ensure that it goes to the staging (because you saved it in staging)
3. Repeat the step above locally:
- …
=> Bug/DES-2149: Make HazMapper link location dynamic.

designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.html, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.js, designsafe/static/scripts/projects/components/manage-project/amend-project.template.html, designsafe/static/scripts/projects/components/manage-project/manage-project.component.js, designsafe/static/scripts/projects/components/manage-project/manage-project.template.html
Removed the overly complicated bootstrap datepicker from the projects area (Note: I have not removed the dependency yet, because this PR is getting a bit big). I will push up a separate issue for dropping bootstrap datepicker as a dependency.
* [DES-2143](https://jira.tacc.utexas.edu/browse/DES-2143)
The date input boxes for the `manage-project`, `manage-experiments`, `manage-collections`, and `manage-missions` components have been revised.
1. Fixed an issue related to the project date which would cause the publication process to fail.
2. Fixed a bug preventing the form from notifying the user when a date was not supplied when required (by removing bootstrap datepicker)
3. Fixed a bug where editing an entity with only one date would render incorrectly (two dates would be displayed)
4. …
=> Task/DES-2143 - Fix various bugs and formatting issues related to datepicker

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.html, designsafe/static/scripts/projects/components/manage-experiments/manage-experiments.component.js, designsafe/static/scripts/projects/components/manage-field-recon/collections/manage-field-recon-collections.component.js, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js
This should resolve several bugs related to custom inputs on project entities...
1. User supplied inputs for project entities (experiments, simulations and hybrid simulations) should render instead of "Other" in the publication preview.
2. When switching from a custom input to a preset, the custom value should be cleared to prevent issues and it should display a preset.
3. Removed redundant object pruning before posting changes to the backend
4. Revert request queue for creating multiple experiments at once (this never happens and no one will ever need to do this)
5. Refactor some ambiguous code
* [DES-2148](https://jira.tacc.utexas.edu/browse/DES-2148)
1. Work in an Experimental, Simulation, or Hybrid Simulation project
2. Create an Experiment, Simulation, Hybrid Simulation with custom …
=> Task/DES-2148 - Fix bugs for custom entity inputs

designsafe/static/scripts/data-depot/components/projects/curation-directory/curation-directory.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-project/pipeline-project.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js
Moved the remaining Edit Project urls on other templates that I missed before.
Also removed the Edit Project urls from the Publication Preview as per a new secondary request from Craig.
* [DES-2047](https://jira.tacc.utexas.edu/browse/DES-2047)
1. Click through each of the tabs in multiple types of projects.
2. Confirm that the Edit Project is now right-aligned on the Working Directory and Curation Directory pages.
3. Confirm that the Edit Project url does not exist on the Publication Preview page.
=> DES-2047 Fix: Edit Project url location fix

designsafe/apps/search/search_indexes.py, designsafe/apps/search/tasks.py
There seems to be a CMS plugin that can't be serialized for indexing. Because this only affects 1 page so far we should ignore it for now so we can keep the rest of the index up to date.
* [DES-2188](https://jira.tacc.utexas.edu/browse/DES-2188)
- Handle a plugin serialization exception that was preventing the index from being updated
- replace the `update_index` command with `rebuild_index` in our crontab. I noticed that `update_index` wasn't picking up new content in my local environment.
1. Load a recent production database dump into your local environment
2. in the container shell run `python manage.py rebuild_index`
=> bug/DES-2188: handle plugin exceptions in the CMS indexer

conf/deploy/docker-compose.all.yml, conf/deploy/nginx.conf
- Adds `designsafe_use_case` container, with watchtower enabled look for updates to `designsafeci/ds-use-case-template`
- Adds flags `WATCHTOWER_INCLUDE_STOPPED` and `WATCHTOWER_REVIVE_STOPPED` to enable watchtower for the stopped `designsafe_use_case` container, as it exits after build
* [DES-2111](https://jira.tacc.utexas.edu/browse/DES-2111)
=> task/DES-2111: Add ds-use-case docs container

designsafe/apps/api/datafiles/utils.py
The limit and offset for the file metadata query was set incorrectly. This should fix issues related to the iterative retrieval of file metadata in large quantities.
* [DES-2205](https://jira.tacc.utexas.edu/browse/DES-2205)
1. Open a shell within the Django container and try to make a large metadata query.
```
import json
from designsafe.apps.api.agave import service_account
sa_client = service_account()
query = {
"name": "designsafe.file", # this can be something like 'designsafe.project' too
}
all_results = []
offset = 0
while True:
result = sa_client.meta.listMetadata(q=json.dumps(query), limit=300, offset=offset)
all_results = all_results + result
offset += 300
if len(result) != 300:
break
print(len(all_results))
```
=> Bug/DES-2205 - Fix limit and offset for file metadata query

designsafe/static/styles/main.css, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
We use a custom bootstrap package that is committed directly to our codebase. This old bootstrap includes a margin-bottom and top for the footer and header elements. It ends up adding an unwanted margin for body content.
* [DES-2206](https://jira.tacc.utexas.edu/browse/DES-2206)
1. Ensure modified css is in /static
2. Go to designsafe.dev and confirm the body has no bottom padding, and the navbar has no bottom margin
- Before
- After
- After
=> task/DES-2206: Remove unnecessary margin/padding

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
We will show a banner above published entities and projects when a published DOI is incomplete and abandoned. This banner is triggered when the publication status is set as `tombstone` instead of `published`. 
* [DES-2150](https://jira.tacc.utexas.edu/browse/DES-2150)
Published Project templates have been updated with the alert banner.
1. Find a publication and change the status of that publication to `tombstone`. You should see the banner appear in the ui and the publication will drop from the published listing. (You can also just set the `ui` parameter to see it)
=> Task/DES-2150 - DOI Tombstone Page

designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-experimental.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-amend/pipeline-amend.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-licenses/pipeline-licenses.component.js, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/styles/ng-designsafe.css
This changes the display of license info in the published area and fixes a typo with one of the selectable licenses.
* [DES-2245](https://jira.tacc.utexas.edu/browse/DES-2245)
There is no visual difference in these changes. There are just some bug fixes and tweaks to the templates.
1. The licenses and their icons should appear in the published view as they normally do
=> Task/DES-2245 - Adjust license display and fix typo in license name

designsafe/settings/common_settings.py, designsafe/settings/test_settings.py, designsafe/static/styles/main.css, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css, designsafe/templates/cms_page_no_footer.html, designsafe/templates/includes/footer.html
- DS Uses Cases group does not want footer on page, so we need to create a new CMS template without a footer.
- Also per Hedda, margin from [DES-2206](https://github.com/DesignSafe-CI/portal/pull/954) was intentional, so revert that change from main template.
* [DES-2241](https://jira.tacc.utexas.edu/browse/DES-2241)
* [DES-2206](https://jira.tacc.utexas.edu/browse/DES-2206)
=> task/DES-2241: Add footerless template; add back nav and footer padding

designsafe/static/styles/ng-designsafe.css
Adds max size to app icons.
* [DES-2247](https://jira.tacc.utexas.edu/browse/DES-2247)
1. Open https://designsafe.dev/rw/workspace/ in a large view (over 1400px)
2. Confirm icons do not grow further
- Before
- 
- After
-
=> task/DES-2247: Fix large window app icons

designsafe/static/scripts/workspace/components/application-tray/application-tray.component.js, designsafe/static/scripts/workspace/controllers/application-form.js
Simcenter wants to be able to launch public apps not in public tray. This change makes it more like other portals, where if a valid app id is supplied in the URL, the app will be loaded.
To test, try the public app `quoFEM-frontera-1.0.0u2` which has no metadata record
* [DES-2248](https://jira.tacc.utexas.edu/browse/DES-2248)
1. Go to https://designsafe.dev/rw/workspace/#!/quoFEM-frontera-1.0.0u2
2. Confirm app is loaded
=> task/DES-2248: Allow apps with no metadata record

designsafe/apps/api/users/views.py, designsafe/static/scripts/data-depot/components/projects/publication-preview/modals/author-information-modal.component.js
Fix a bug causing ajax requests to the user lookup view to redirect to Tapis Oauth and throw a CORS error.
* [DES-2249](https://jira.tacc.utexas.edu/browse/DES-2249)
1. Navigate to a publication while unauthenticated
2. Click on a user's name in the author list and confirm that the correct name/institution come up.
=> task/bug-2249: remove SecureMixin from the user lookup view

designsafe/apps/search/tasks.py, designsafe/celery.py
Per the Django docs(https://docs.djangoproject.com/en/1.11/topics/http/sessions/#clearing-the-session-store): 
"Django does not provide automatic purging of expired sessions. Therefore, it’s your job to purge expired sessions on a regular basis."
We should set up a simple nightly crontab to do this for us.
* [DES-2253](https://jira.tacc.utexas.edu/browse/DES-2253)
=> task/DES-2253: Set up nightly crontab to clear expired sessions

designsafe/apps/workspace/views.py, designsafe/static/scripts/workspace/controllers/application-form.js
- After the TAP Functions updates, VNC server will not be available unless `vncserver` is present in the job name. 
- Allow users to define exactly their own `archivePath`
* [DES-2251](https://jira.tacc.utexas.edu/browse/DES-2251)
Archive Path:
1. Submit a job with a specific `archivePath`
2. Confirm the job archives to that path, and does not create a subdir with your username
vncserver:
1. Find the private app `Paraview-Stampede2-VNC-5.10.0` in `My Apps`
2. Run the app, and confirm you get a VNC session link
=> task/DES-2251: Add `vncserver` to VNC app job names; remove username from user defined `archivePath`

designsafe/apps/api/projects/views.py, designsafe/apps/api/tasks.py, designsafe/settings/common_settings.py
Added new celery task at the end of the Publication Pipeline to check for missing files/folders and empty top-level folders.
* [DES-2242](https://jira.tacc.utexas.edu/browse/DES-2242)
* [DES-2169](https://jira.tacc.utexas.edu/browse/DES-2169) - original request, resource issues means this exact task won't be done, but 2242 is the current solution for now.
Added new celery task to check for missing files/folders and empty top-level folders.
Specific devs will get an email if something is missing or empty.
NOTE: This is not a comprehensive "going down the tree of folders" check, only a single directory down so we don't use up too many resources traversing the folder structure.
1. Make sure you have a publication in your local elasticsearch and copy the files to your local version of the …
=> DES-2242: Publication Pipeline File Check

designsafe/apps/api/notifications/tests.py, designsafe/apps/notifications/views.py, designsafe/static/scripts/workspace/controllers/application-form.js
Substring needed is actually `tap_`, not `vncserver`. The tests succeeded in the previous PR because DCV was still launching somehow. That should be fixed in this test.
NOTE: Connection to VNC sessions are still not working, but because of a different issue.
* [DES-2251](https://jira.tacc.utexas.edu/browse/DES-2251)
1. Find the private app Paraview-Stampede2-VNC-5.10.0 in My Apps
2. Run the app, and confirm you get a VNC session link
=> fix/DES-2251: Change `vncserver` to `tap_`

designsafe/static/scripts/workspace/html/jobs-status.html
* display the "lastStatusMessage" of a job object in the job detail modal.
* [DES-2255](https://jira.tacc.utexas.edu/browse/DES-2255)
* Added a row under "Finished", called "Last Status Message"
* Added a row under that being the contents of the "lastStatusMessage" field of a job object
1. Run designsafe.dev and view the Last Status Message in the job details modal
=> DES-2255: add Last Status Message

designsafe/static/scripts/data-depot/components/data-depot-listing/files-listing.template.html, designsafe/static/scripts/projects/components/manage-project/manage-project.component.js
1275: There should be no "Select a Category" or "Save" option by the .Trash folder
2261: If doing multiple Add Project in a row, it autofills with the previous new project's information. Check that the modal is properly clearing the data before reopening.
* [DES-1275](https://jira.tacc.utexas.edu/browse/DES-1275)
* [DES-2261](https://jira.tacc.utexas.edu/browse/DES-2261)
Added a condition that looks for the file name '.Trash' If it is .Trash it does not show the drop down and save option. If it is no .Trash, it does show the drop down and save option.
Changed all this.form = this.formDefaults.new
to this.form = {...this.formDefaults.new}
1275:
1. Select a project type with categories (Experimental, Simulation, Hybrid Simulation, or Field Research)
2. Add files to this project
3. Click on …
=> Task/DES-1275(2261) - Remove category selectors and fix form object reference

designsafe/apps/projects/models/agave/base.py
Added "funding" hunk of JSON and nested "relatedIdentifiers" under "hasPart" for Google Scholar.
* [DES-2284](https://jira.tacc.utexas.edu/browse/DES-2284)
Modified JSON for Experimental publications with multiple related entities to be more compatible Google Scholar.
1. Open any publication with multiple related entities (for example [PRJ-1903](https://designsafe.dev/data/browser/public/designsafe.storage.published/PRJ-1903) )
2. View the page's source (cmd + option + u)
3. Confirm that there is a json with hunk called "funding" that contains both the award numbers and names for the publication.
4. Confirm that there are "relatedIdentifiers" under "hasPart"
=> task/DES-2284 - SEO updates

designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-preview-metadata-template.html
This fix should render the following fields correctly in the Publication project metadata header.
- DOIs in Dataset - (for all project types besides OTHER): This should show a list of DOIs which, when clicked, will scroll down and open the corresponding entity.
- Version - (any versioned publication): This should render and allow navigation between published versions.
- DOI [Citation]: This should display for OTHER and should open a modal with citation info now.
* [DES-2333](https://jira.tacc.utexas.edu/browse/DES-2333)
This fix should render the following fields correctly in the Publication project metadata header.
- DOIs in Dataset - (for all project types besides OTHER): This should show a list of DOIs which, when clicked, will scroll down and open the corresponding entity.
- Version - …
=> Bug/DES-2333 - Fix Citation and DOI section of published metadata header

designsafe/apps/api/licenses/urls.py, designsafe/apps/api/licenses/views.py
Needed to change url pattern to allow this url to be caught by jwt decorator.
* [DES-2330](https://jira.tacc.utexas.edu/browse/DES-2330)
- Removed `username` from url pattern 
- Updated view to look for `user` query string
1. Locally, go to https://designsafe.dev/api/licenses/MATLAB/?user=YOUR_USERNAME and https://designsafe.dev/api/licenses/LSDYNA/?user=YOUR_USERNAME
2. Verify that there is a dict reading {'license': ''} or {'license': '<LICENSE_CONTENT_HERE>'}
=> hotfix - Change licenses API endpoint regex to accommodate key-value 

designsafe/apps/api/decorators.py, designsafe/apps/api/licenses/views.py
Resolved variable name conflict between license API endpoint view and JWT auth
* [DES-2330](https://jira.tacc.utexas.edu/browse/DES-2330)
- Changed url param for user to get licenses for to not conflict with JWT auth url param
- Changed default value for JWT auth url user lookup to user associated with included JWT
1. Use the JWT provided independently for testing (in these testing steps, it is set as environment variable `JWT_TEST`)
2. Use the following cURL commands and confirm you get back a 200 response and a license for the first and no license for the second (i.e. `{'license': ''}`):
- `curl -i -H "X-Jwt-Assertion-Designsafe: $JWT_TEST" "https://designsafe.dev/api/licenses/MATLAB/?username=gedmonds"`
- `curl -i -H "X-Jwt-Assertion-Designsafe: $JWT_TEST" …
=> hotfix: Licenses API Endpoint picking up incorrect account to check for staff permissions

designsafe/apps/accounts/templates/designsafe/apps/accounts/manage_auth.html, designsafe/apps/accounts/templates/designsafe/apps/accounts/password_reset.html
Remove password reset forms and link to TUP for password resets.
* [DES-2349](https://jira.tacc.utexas.edu/browse/DES-2349)
Updated templates to remove the use of the password reset form and link users to TUP for password resets.
1. Check https://designsafe.dev/account/password-reset/ which should just be a link to TUP.
2. Check https://designsafe.dev/account/authentication/ which should have the same thing as the above link but within the account panel.
=> DES-2349: remove password reset forms

designsafe/static/scripts/ng-designsafe/services/file-listing-service.js
The "parent entity" listing has a bug where files/folders in a project's root directory will display as the children of every entity in the project. The logic needs to be updated to reflect the fact that a project's root directory can't be associated with an entity.
before (this is wrong, these folders aren't directly associated to any entities):
after:
=> bug/DES-2394: Fix association tags for files at project root

designsafe/apps/api/tasks.py, designsafe/static/scripts/data-depot/components/projects/pipeline-version/pipeline-version-changes.component.js
Fix a Javascript typo which was causing a `null` value to be sent to `copy_publication_files_to_corral`.
* [DES-2401](https://jira.tacc.utexas.edu/browse/DES-2401)
=> bug/DES-2401: Fix bug causing versioned Other projects to publish with no files

designsafe/static/scripts/ng-designsafe/services/file-listing-service.js
Abstract listings can fail completely if one of their component listings fails, causing the page to get stuck in a "loading" state. This PR addresses the bug by handling listing exceptions and replacing the missing listing with a "synthetic" listing that uses the Tapis path to infer the file type.
* [DES-2402](https://jira.tacc.utexas.edu/browse/DES-2402)
- Add better exception handling to the `abstractListing` method in the file listing servce.
1. Try to preview a project with a lot of associated files (https://designsafe.dev/data/browser/projects/8748128685492212201-242ac11b-0001-012/preview/exp/ is a good example).
2. Refresh the page a few times to make sure that the listing never ends up spinning forever. If you look in the network tab and see an error, but the preview still loads, …
=> bug/DES-2402: prevent Publication Preview from spinning forever

designsafe/apps/api/publications/operations.py, designsafe/apps/api/publications/search_utils.py, designsafe/static/scripts/data-depot/components/data-depot-listing/data-depot-listing.component.js, designsafe/static/scripts/data-depot/components/data-depot-listing/publications-listing.template.html, designsafe/static/scripts/data-depot/components/main/main.template.html, designsafe/static/styles/ng-designsafe.css, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
Fixes for Craig/Maria's notes:
- In the string search, “Natural Hazard Event, Project ID, or DOI” need to be searched
- There needs to be a global filter for Year Published. This is common on all repositories.
- For fitting these extra items and refining the space a bit,
- The left-hand Data Depot navigation does not need to be as wide as it is right now, there is ~30% extra space than there needs to be
- Bring the left to align with where “Workplace” in the navigation starts and the right to align with the “Search DesignSafe” in the nav bar ends
- To increase the table height, shorten “Project Description” -> “Description” and “Date of Publication” -> “Date Published”
- Don’t forget to put the Experimental, Simulation, Field Research labels on a new line beneath the title
=> Additional tweaks for Published search

designsafe/apps/data/templates/data/data_depot.j2, designsafe/static/vendor/bootstrap-ds/css/bootstrap.css
We styled the Data Depot to fill the screen, but other pages rely on the previous container styling. The Data Depot should use a unique class for setting its width.
* [DES-2467](https://jira.tacc.utexas.edu/browse/DES-2467)
1. Navigate to a CMS page (https://designsafe.dev/learning-center/nheri-graduate-student-council/) and make sure the content doesn't exceed 1170px as the window width increases.
Before:
After:
=> Restore previous max width on containers outside Data Depot

designsafe/templates/includes/cms_menu.html
Add `role="button"` attribute to CMS dropdown menu links.
* [DES-2476](https://jira.tacc.utexas.edu/browse/DES-2476)
1. Verify `role="button"` is on any CMS menu link that, when pressed, reveals a dropdown menu.
1. Verify `role="button"` is **not** on any CMS menu link that, when pressed, opens a page.
Skipped.
=> fix(a11y): DES-2476 role button on cms dropdown menu link

designsafe/templates/ef_base.html, designsafe/templates/ef_cms_page.html, designsafe/templates/includes/header.html
Remove the screen-reader–only `<h1>` before the site logo, because there is already an `<h1>` on every page.
<sup>Both Hp. and W.B. from DesignSafe agreed on this. It is also what W.B. did on https://github.com/TACC/Core-CMS long ago.</sup>
* [DES-2478](https://jira.tacc.utexas.edu/browse/DES-2478)
1. Verify that there is **not** an `<h1>` before the site logo.
Skipped.
=> fix(a11y): DES-2478 remove the `<h1>` before site logo

designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-field-recon.template.html, designsafe/static/scripts/data-depot/components/published/published.component.html, designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-collections-template.html, designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-preview-metadata-template.html, designsafe/static/scripts/projects/components/manage-project-type/manage-project-type.template.html, designsafe/static/scripts/rapid/html/index.html, designsafe/templates/includes/footer.html
Add `alt` attributes to images.
* [DES-2497](https://jira.tacc.utexas.edu/browse/DES-2497)
1. Verify the following images have `alt` attributes:
- NSF logo in footer
- Recon Portal logo… somewhere
- screenshots illustrating how to `manage-project-type` e.g. experimental project, simulation project
- any <img height="14px" src="https://www.designsafe-ci.org/static/images/ds-icons/icon-metrics.svg" /> or <img height="14px" src="https://www.designsafe-ci.org/static/images/ds-icons/icon-feedback.svg" /> icons
Skipped.
=> fix(a11y): DES-2497 `alt` attributes for images

designsafe/templates/includes/cms_menu.html
Add `aria-expanded="false"` to CMS dropdown menu links.
* [DES-2480](https://jira.tacc.utexas.edu/browse/DES-2480)
1. Verify `aria-expanded="false"` is on any CMS menu link that would reveal a dropdown menu when pressed.
Do not actually click the link. You test that the attribute is there and is `false` by default (without clicking).
3. Click such a CMS menu link.
4. Verify the attribute is now `aria-expanded="true"`.
5. Click that link again, or click outside the menu.
6. Verify the attribute is now `aria-expanded="false"`.
7. Repeat indefinitely.
Skipped.
=> fix(a11y): DES-2480 aria-expanded default false cms menu

designsafe/templates/includes/cms_menu.html
Add `aria-haspopup` attribute to CMS dropdown menu links.
* [DES-2481](https://jira.tacc.utexas.edu/browse/DES-2481)
1. Verify `aria-haspopup` is on any CMS menu link that, when pressed, reveals a dropdown menu.
1. Verify `aria-haspopup` is **not** on any CMS menu link that, when pressed, opens a page.
Skipped.
=> fix(a11y): DES-2481 aria-haspopup cms menu

designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html, designsafe/static/scripts/geo/html/map.html, designsafe/templates/includes/cms_menu.html, designsafe/templates/includes/ef_navigation.html, designsafe/templates/includes/header.html, designsafe/templates/includes/homepage_navigation.html, designsafe/templates/includes/navigation.html
Add `role="presentation"` to recurring icon elements (which have no text).
* [DES-2482](https://jira.tacc.utexas.edu/browse/DES-2482)
1. Verify CMS navigation menu dropdown links' `<span class="caret"`s have `role="presentation"`.
2. Verify CMS navigation mobile expand button `<span class="icon-bar"`s have `role="presentation"`.
<sup>These are only visible when the screen is so narrow the menu changes to mobile layout.</sup>
3. (Optional) If you know where geo map is, check any `<span class="caret"`s have `role="presentation"`.
<sup>designsafe/static/scripts/data-depot/components/data-depot-nav/data-depot-nav.component.html</sup>
4. (Optional) If you know where data depot nav is, check any `<span class="caret"`s have `role="presentation"`. …
=> fix(a11y): DES-2482 cms icons, role as presentation

designsafe/static/scripts/data-depot/components/data-depot-listing/publications-listing.template.html, designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.html, designsafe/static/scripts/rapid/html/rapid-admin-users.html, designsafe/static/scripts/search/components/search/search.component.html, designsafe/templates/includes/navigation.html
Add `role="presentation"` to FontAwesome **Search** icons.
* [DES-2482](https://jira.tacc.utexas.edu/browse/DES-2482)
1. Open a few **CMS** pages.
2. Search the markup for `fa fa-`.
3. Verify all `<i class="fa fa-search></i>` are now ``<i role="presentation" class="fa fa-search></i>`.
1. Open a few **Portal** sections.
2. Search the markup for `fa fa-`.
3. Verify all `<i class="fa fa-search></i>` are now ``<i role="presentation" class="fa fa-search></i>`.
Skipped.
This does not fix other FontAwesome icons that need `role="none"`. For that, see #1052.
If you are resolving conflicts, know the ARIA `role="none" is synonymous with `role="presentation"`.
=> fix: DES-2482 cms search icons, role presentation

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.js, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/projects/components/published-data-modal/published-data-modal.component.js
Date of Publication was always showing the newest date, meaning if a version or amend was done, then the Date of Publication was updated. This is an issue because the Date of Publication should always show the actual date if was published. 
* [DES-2492](https://jira.tacc.utexas.edu/browse/DES-2492)
For Simulation, FR, Experimental, and Hybrid Sim, I added a dictionary called dateCreated that stores a DOI : dateCreated. In the html, the dictionary is cycled through, and when the entity DOI matches the dictionary DOI, then the dateCreated is displayed. 
For type Other, the Date of Publication is not displayed on the Project side, so no changes were made. 
For each project type:
1. Find a project that has versions. 
2. In both  'My Projects' and 'Published' confirm that each entity has it's …
=> Date of Publication issue

designsafe/templates/ef_base.html, designsafe/templates/includes/header.html
Add a `role="banner"` to any `<header>` that is not a direct child of `<body>`.
* [DES-2520](https://jira.tacc.utexas.edu/browse/DES-2520)
1. Verify `role="banner"` is on a `<header>` that is not a direct child of `<body>`.
<sup>You can test on of the changes for this on https://designsafeci-dev.tacc.utexas.edu/.</sup>
Skipped.
I am not sure this solves the problem, but `<header>` was specifically called out on row #34 of [accessiBe report #2](https://acsbace.com/reports/647e36f55a483d0003a37a50?whitelabel=false&utm_medium=email&_hsmi=90649158&utm_source=hs_email).
=> fix(a11y): DES-2520 header role attribute

designsafe/libs/fedora/fedora_operations.py, designsafe/libs/fedora/sim_operations.py
Previously both `rel_path` and `project_path` were used as keys. This diff changes the manifest code to use `project_path` consistently.
=> Keep keys consistent in Fedora file manifests

designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-citation.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-authors/pipeline-authors.component.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/version-citation.template.html
In the Citation Preview, the comma was missing after the first name leading to the second name. 
* [DES-2504](https://jira.tacc.utexas.edu/browse/DES-2504)
The Citation Preview appears when publishing, amending, and versioning. In the controllers for each, the ds-author-list function is used. I changed the format to 'citation' which lists the author with the comma correctly. 
For each project type:
1. Attempt to publish a project. 
2. When you get to the citation preview, check for the comma in the author list. 
3. Attempt to amend a project. 
4. When you get to the citation preview, check for the comma in the author list. 
5. Attempt to version a project. 
6. When you get to the citation preview, check for the comma in the author list.
=> des2405-add-comma-to-authorList-in-citationPreview

designsafe/static/styles/main-ef.css, designsafe/static/styles/ng-designsafe-ef.css, designsafe/templates/ef_cms_page.html, designsafe/templates/includes/ef_navigation.html
At some point in 2020 we inverted the colors on the main Designsafe menu and stretched the container to fill the screen horizontally. This breaks the EF sites, which still rely on Bootstrap 3 style container styling. This PR adds our old stylesheets back into version control for use on the EF sites.
* [DES-2557](https://jira.tacc.utexas.edu/browse/DES-2557)
- Use legacy versions of `ng-designsafe.css` and `main.css` when rendering EF site templates.
- Undo color inversion on EF menus.
1. In `common.py` edit the SITE_ID setting to anywhere between 2 and 10 to test out the rendering of the EF sties.
SimCenter site running in local dev:
=> task/DES-2557: Allow EF sites to be displayed using recent Designsafe releases

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html
In Pub Preview, an extra (Appears when published) was appearing. It was determined to be for the "License(s)" section of the metadata.
* [DES-2554](https://jira.tacc.utexas.edu/browse/DES-2554)
In both cases, a conditional statement that would display "License(s)" was not working correctly because one of the conditions was from the wrong project type (FR), rather than HybSim or Exp. 
For all project types, find a project with a License and make sure the correct text appears. 
**BEFORE**
**AFTER**
=> Licences not displaying properly for Exp & HybSim

designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-preview-metadata-template.html
When on the Publication Preview for a type Other project, the Co-PIs do not appear.
They now appear but like PI, they are NOT hyperlinked. Checked that the citation preview for type Other also has the correct authors list (My Projects & Published).
* [DES-2292](https://jira.tacc.utexas.edu/browse/DES-2292)
In prj-pub-preview-metadata-template.html, I used similar code from PIs (type Other) to display Co-PIs (type Other). This is specific for type Other; all other types grab these fields in a different way. 
1. Find a type Other project that has Co-PI(s)
2. In My Projects, in Working Directory, verify that Co-PIs appear (should be hyperlinked)
3. Click on Publication Preview, verify that Co-PIs appear (should not be hyperlinked)
BEFORE
AFTER
I tried to hyperlink the Co-PIs, but they are …
=> des-2292: Co-Pis now appears without hypertext

designsafe/static/scripts/data-depot/components/published/published-view.component.js
Coordinator Output was not appearing in 'Published' 
All other categories appear fine. 
* [DES-2574](https://jira.tacc.utexas.edu/browse/DES-2574)
In published-view.component.js, there was a typo where `coordinator_outputs` was misspelled `coordintaor_outputs`
Fixing this resolved the issue.
1. Find a Hybrid Simulation project with all categories (Report, Global Model, Coordinator, Coordinator Output, Simulation Substructure, Simulation Output, Experimental Substructure, Experimental Output, and Analysis)
2. Make sure ALL categories appear in My Projects & Published.
=> bug/des-2574: coor-output not appearing in Pub

designsafe/apps/api/users/views.py
Disable endpoint flagged by ISO that would return all user profiles if used without a query string.
=> Prevent user search endpoint from returning all user profiles

designsafe/apps/api/publications/search_utils.py, designsafe/static/scripts/data-depot/components/data-depot-listing/publications-listing.template.html
- Escape the query string in quotes before passing to the author query, since special characters can cause a 500
- Remove the "DOI" text from the search placeholder, since searching by DOI isn't supported yet.
* [DES-2585](https://jira.tacc.utexas.edu/browse/DES-2585)
=> Remove text indicating that users can search by DOI

designsafe/static/scripts/data-depot/components/data-depot-listing/data-depot-listing.component.js, designsafe/static/scripts/data-depot/components/data-depot-listing/files-listing.template.html
Hide the .Trash folder in Community listings and other public listings.
* [DES-2586](https://jira.tacc.utexas.edu/browse/DES-2586)
1. Navigate to Community Data and confirm that the trash folder doesn't display in the top-level listing.
Before:
After:
=> bug/DES-2586: Hide trash folder for Community Data and published projects

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-field-recon.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-hyb-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-sim.component.html, designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview.component.html, designsafe/static/scripts/data-depot/components/published/published-view.component.js, designsafe/static/scripts/ng-designsafe/directives/templates/prj-pub-preview-metadata-template.html
- Use Datacite as the source of truth for view/download/citation metrics on publications
- use "--" as a loading indicator instead of defaulting to 0.
* [DES-2536](https://jira.tacc.utexas.edu/browse/DES-2536)
1. Open publications of type Experimental, Simulation, Field Research, Hybrid Sim, and Other. Check that the view/download/citation metrics load in.
=> task/DES-2536: Use Datacite metrics when displaying view/download counts

designsafe/libs/fedora/fedora_operations.py, designsafe/libs/fedora/fr_operations.py, designsafe/libs/fedora/hyb_sim_operations.py, designsafe/libs/fedora/sim_operations.py
Example: Simulation A uses a model to generate Output 1, and Simulation B uses that same model to generate Output 2. Currently Output 1 and Output 2 will BOTH show up under each simulation. This PR updates tree construction to account for the entire association ID chain.
* [DES-2594](https://jira.tacc.utexas.edu/browse/DES-2594)
1. Test the `walk_sim` and `walk_hybrid_sim` methods on publications with reused parent entities.
=> Bug/DES-2594: Prevent entity reuse from causing double-counting in Fedora

designsafe/static/scripts/data-depot/components/projects/pipeline-amend/amend-hybrid-sim.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-start/pipeline-start.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/version-experiment-selection.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/version-field-recon-selection.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/version-hyb-sim-citation.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/version-hyb-sim-selection.template.html, designsafe/static/scripts/data-depot/components/projects/pipeline-version/version-simulation-selection.template.html
More text changes that mostly relate to Hybrid Sim
* [DES-2512](https://jira.tacc.utexas.edu/browse/DES-2512)
* DES-2517: Updated amends text in amend-hybrid-sim.template.html
Updated Confirm Author section in version-hyb-sim-citation.template.html
* DES-2518: Updated Version text -- changed 'publication' to 'project in version-hyb-sim-selection.template.html as well as field-recon, experiment, simulation
1. work your way down the publication pipeline, primarily for project type HybSim
=> des-2512-more-text-changes--mostly-hyb-sim

designsafe/static/djangocms_text_ckeditor/css/cms.ckeditor.css, designsafe/static/djangocms_text_ckeditor/css/cms.ckeditor.original.css
Add styles to CMS Text editor stylesheet to prevent field size bug.
* [DES-2598](https://jira.tacc.utexas.edu/browse/DES-2598)
- **added** custom stylesheet for ckeditor
- **added** clone of original stylesheet for ckeditor
- **added** import of cloned stylesheet
1. Open CMS.
2. Login as admin.
3. Create/Edit text on a page.
4. Add so much content, a scrollbar is needed.
5. Make the text editor modal narrow.
6. While editing, view source (click the "[<>] Source" button).
7. Verify all available height in modal for text editor is used to show source.
I am unable to provide. I do not have test environemnt.
1. stole code from https://github.com/TACC/Core-CMS/pull/573/files#diff-b613bf1b786994b3d51a81e982cf9106f4a09f8adcc65fd9c14f4f8d54bdfa72R6-R8
8. applied code like …
=> fix: DES-2598 text editor too short (⚠️ untested)

designsafe/settings/common_settings.py, designsafe/urls.py, poetry.lock, pyproject.toml
Update django-cms and djangocms-admin-style versions to prevent style regressions.
* [DES-2597](https://jira.tacc.utexas.edu/browse/DES-2597)
1. While logged in as an admin, open the Users panel and check that the searchbox is legible.
=> Bump django-cms to 3.8 and fix admin UI

designsafe/apps/djangoRT/rtUtil.py
The rtpy documentation is misleading: https://python-rt.readthedocs.io/en/latest/rest1.html#rt.rest1.Rt.create_ticket 
Specifying "Requestors" instead of "Requestor" as we've been doing causes the requestors to be added AFTER ticket creation, meaning no one gets an email confirmation.
* [WP-319](https://jira.tacc.utexas.edu/browse/WP-319)
=> bug/WP-319: Fix email confirmation for tickets

designsafe/urls.py
Dependency updates broke our ability to access impersonation routes at `/admin/impersonate/<uid>`. The hack we deployed changes the URL to `/admin/impersonation` but will require communication to all admin-level users.
This diff updates the impersonation routing so that both the standard admin views and our custom-defined `/admin/impersonate/...` paths will work.
=> Hotfix: Restore ability to access impersonation routes at /admin/impersonate/

designsafe/apps/auth/tasks.py, designsafe/apps/search/tasks.py, designsafe/celery.py
If left unchecked, multiple gigabytes of old notifications can accumulate in the database. This PR adds a nightly cleanup task that deletes notifications older than 30 days.
* [DES-2605](https://jira.tacc.utexas.edu/browse/DES-2605)
=> task/DES-2605: Add a nightly crontab to delete notifications older than 30 days.

designsafe/apps/signals/static/designsafe/apps/signals/scripts/provider.js, designsafe/static/scripts/ng-designsafe/providers/ws-provider.js
Updated:	1 minute ago
Description
Currently if a websocket connection closes, we retry in an infinite loop without any kind of debounce/backoff. This results in the server getting completely slammed with incoming requests if there's any sort of error due to someone's client being stale.
* [DES-2606](https://jira.tacc.utexas.edu/browse/DES-2606)
Add an exponential backoff to websocket connections. the retry backoff starts at `1000 * Math.random()` to introduce jitter so that if the server restarts every client doesn't try to reconnect simultaneously. Subsequent retry requests double the delay until 1 minute has passed, then the client gives up.
1. In `ng-designsafe.js` replace the `/ws/websockets/` URL with `/ws/error`.
2. Check that when you visit designsafe.dev you see attempted …
=> Bug/DES-2606: add exponential backoff for websocket retries

designsafe/static/scripts/data-depot/components/data-depot-toolbar/data-depot-toolbar.component.js, designsafe/static/scripts/data-depot/components/published/published-view.component.js
Keep track of the DOI associated to a folder when the user navigates inside of a publication. This prevents undefined DOIs on file operations.
* [DES-2602](https://jira.tacc.utexas.edu/browse/DES-2602)
=> bug/DES-2602: Keep track of DOI when a user browses files in a publication

designsafe/apps/api/datafiles/utils.py
Small bug: When we copy metadata, we pass its `value` attribute into the `file_meta_object` method which updates the values to reflect the new system/path. This inadvertently updates the values on the original metadata object. This hasn't caused problems yet but it does leave the data in an invalid state. for the remainder of the request This PR changes the method to use a deep copy so the original dict is unaffected.
* [DES-2608](https://jira.tacc.utexas.edu/browse/DES-2608)
=> Bug/DES-2608: Fix copy_meta util to avoid altering the original metadata

designsafe/static/scripts/applications/controllers/application-add.js, designsafe/static/scripts/workspace/controllers/application-form.js, designsafe/static/scripts/workspace/html/application-form.html, designsafe/static/scripts/workspace/html/directives/agave-file-picker.html, designsafe/static/scripts/workspace/services/apps-service.js
- Fix validation fields
- Change display text for some fields
- Hide "Inputs" if none are defined
- Fix max, min, and default values for some fields
* [DES-2609](https://jira.tacc.utexas.edu/browse/DES-2609)
1. Go to https://designsafe.dev/rw/workspace/#!/OpenSees::Simulation
2. Confirm UI matches screenshots
3. Confirm apps submit and function correctly
=> task/DES-2609: App Form Updates

designsafe/apps/projects/models/agave/base.py, designsafe/apps/projects/models/agave/experimental.py, designsafe/apps/projects/models/agave/hybrid_simulation.py, designsafe/apps/projects/models/agave/rapid.py, designsafe/apps/projects/models/agave/simulation.py
The `IsSupplementTo` relation counts as a citation of the supplement for some reason. This PR replaces it with the `IsPartOf` relation so that no citation is registered.
* [DES-2613](https://jira.tacc.utexas.edu/browse/DES-2613)
=> bug/DES-2613: Use IsPartOf instead of IsSupplementTo in Datacite mappings

designsafe/apps/data/apps.py, designsafe/settings/test_settings.py
This fixes an issue where pylint was breaking in local dev.
=> Fix: Disable elasticsearch socket options in dev/test envs

designsafe/apps/auth/tasks.py
Fix a bug with the task definition.
* [DES-2645](https://tacc-main.atlassian.net/browse/DES-2645)
=> bug/DES-2645: Fix cleanup for old notifications

designsafe/apps/api/publications/urls.py
Fix a URL bug preventing NEES project IDs from being parsed.
* [DES-2634](https://tacc-main.atlassian.net/browse/DES-2634)
1. Click "View Description" in the NEES listing.
=> bug/DES-2634: Fix NEES description endpoint

designsafe/static/scripts/ng-designsafe/components/modals/data-browser-service-copy/data-browser-service-copy.component.js
We've altered our Google Drive scope to read-only, so copying INTO Drive should no longer be supported.
* [DES-2640](https://tacc-main.atlassian.net/browse/DES-2640)
=> bug/DES-2640: Disable copying files into Google Drive

designsafe/static/scripts/projects/components/manage-field-recon/documents/manage-field-recon-documents.component.js, designsafe/static/scripts/projects/components/manage-field-recon/documents/manage-field-recon-documents.template.html, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.component.js, designsafe/static/scripts/projects/components/manage-field-recon/missions/manage-field-recon-missions.template.html, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.component.js, designsafe/static/scripts/projects/components/manage-hybrid-simulations/manage-hybrid-simulations.template.html, designsafe/static/scripts/projects/components/manage-project/manage-project.component.js, designsafe/static/scripts/projects/components/manage-project/manage-project.template.html, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.component.js, designsafe/static/scripts/projects/components/manage-simulations/manage-simulations.template.html
Prevent users from passing empty/null facility names.
* [DES-2637](https://tacc-main.atlassian.net/browse/DES-2637)
1. Try to set a facility as Other in any project/entity without entering any text in the form field that comes up. It should prevent you from submitting the form until you type something in.
=> bug/DES-2637: Prevent users from entering empty facility names

designsafe/apps/api/datafiles/operations/agave_operations.py, designsafe/apps/api/datafiles/utils.py
Refactors bulk metadata operations to use a series of individual create/update calls.
* [DES-2636](https://tacc-main.atlassian.net/browse/DES-2636)
- Refactor bulk metadata operations to use synchronous create/update calls on individual metadata objects.
- Make bulk operations asynchronous and allow retries (max 3).
- Update the semantics of `copy_metadata` so that if it needs to be retried, it won't create duplicate metadata records attached to the destination path. (in V3 we can use custom UIDs to make duplication impossible).
Perform the following operations on a file with associated metadata (from RApp):
- Copy
- Move
- Rename
- Trash
Ensure that the metadata follows the file across each operation.
=> task/DES-2636: Refactor file move/copy to use non-bulk metadata operations

designsafe/apps/projects/models/agave/base.py, designsafe/apps/projects/models/agave/experimental.py, designsafe/apps/projects/models/agave/hybrid_simulation.py, designsafe/apps/projects/models/agave/rapid.py, designsafe/apps/projects/models/agave/simulation.py, designsafe/static/scripts/projects/components/manage-project/manage-project.component.js, designsafe/static/scripts/projects/components/manage-project/manage-project.template.html
Adds "funder name" as a field to the Awards section in the project management form, stored as `fundingSource`. This field is required for projects with award numbers. On publication it is used as the `funderName` in Datacite.
* [DES-2639](https://tacc-main.atlassian.net/browse/DES-2639)
1. Update a project with funding sources.
2. Call `to_datacite_json()` on that project and check that the funder name is piped through.
=> Task/DES-2639 addendum:  Add funder name to project management form.

designsafe/static/scripts/projects/components/file-categories/file-categories.component.js
Fix a string formatting issue that was preventing tags from showing up on non-Other type projects.
* [DES-2663](https://tacc-main.atlassian.net/browse/DES-2663)
1. Go to both Other and non-Other projects in dev and check that tags work.
=> bug/DES-2663: Fix tags not showing up in non-Other projects

designsafe/static/scripts/data-depot/components/projects/publication-preview/publication-preview-other.component.html
Adds tombstone banners for type Other publications with an optional `tombstoneMessage` set on the publication object in Elasticsearch.
* [DES-2665](https://tacc-main.atlassian.net/browse/DES-2664)
1. Visit publication PRJ-3908 and check that the tombstone banner is displayed.
=> bug/DES-2664: Add tombstone messages for type Other

designsafe/static/scripts/workspace/controllers/application-form.js
A conditional was preventing app parameters from rendering if no app inputs were defined
* [DES-2667](https://tacc-main.atlassian.net/browse/DES-2667)
1. Go to designsafe.dev/rw/workspace/#!/potree-viewer-0.2u5 and confirm the "Inputs" field is present
=> bug/DES-2667: Fix missing params when no inputs present

designsafe/static/scripts/data-depot/components/data-depot-browser/data-depot-browser.component.js, designsafe/static/scripts/data-depot/components/data-depot-listing/files-listing.template.html, designsafe/static/scripts/ng-designsafe/services/file-listing-service.js, designsafe/static/scripts/ng-designsafe/services/file-listing-service.spec.js
Move filtering of `.Trash` out of the file listing component and into the file listing service, upstream of the point where the listing enters global state.
* [DES-2695](https://tacc-main.atlassian.net/browse/DES-2695)
=> bug/DES-2695: Community data shows the wrong files being selected

designsafe/apps/api/publications/search_utils.py, designsafe/static/scripts/ng-designsafe/services/publication-service.js
- Improve keyword searches in Publications by applying the `cross_fields` operator.
- Add error handling in Publications if a listing/search fails.
* [DES-2696](https://tacc-main.atlassian.net/browse/DES-2696)
=> task/DES-2696: Improve query string queries in Publications and fix endless spinners

designsafe/apps/accounts/forms.py, designsafe/apps/accounts/templates/designsafe/apps/accounts/profile.html, designsafe/apps/accounts/templates/designsafe/apps/accounts/profile_edit.html, designsafe/apps/accounts/tests.py, designsafe/apps/accounts/urls.py, designsafe/apps/accounts/views.py, designsafe/static/scripts/notifications/html/notification_list.html
- Let's continue to display Full Name, Email address, Institution, Title, Country of Citizenship and the Demographic Data. Pull these in from TAM but DO NOT allow edit profile.
- Do not display Phone number (no longer needed)
- Do not display Country of residence (since TAM is no longer collecting that either)
* [DES-2699](https://tacc-main.atlassian.net/browse/DES-2699)
1. Attempt to update user profile (professional profile section) and make sure it still works.
=> Remove TAS calls from user profile; Remove notification setting page

bin/run-django.sh, conf/docker/docker-compose-dev.all.debug.m1.yml, conf/docker/docker-compose-dev.all.debug.yml, conf/nginx/nginx.debug.conf
Revert change to use nginx in local dev to serve static assets. Remove the `--noasgi` flag passed to runserver, which was interfering with static file serving.
=> Use Django to serve static files in debug mode

designsafe/static/styles/app-card.css
Add styles for new `.app-card` UI pattern.
* Hold.
* [DES-2725](https://tacc-main.atlassian.net/browse/DES-2725)
- **added** `.app-card` stylesheet
1. Open https://www.designsafe-ci.org/rw/tools-applications/tools-applications-new/?edit.
2. Verify app cards on page look similar to [design](https://xd.adobe.com/view/bab9a62d-3f2a-45f8-be0f-5680c474d9c1-efea/screen/bc798ccd-87fb-4a71-a01f-b9aceb3c914c/).
3. Verify UI changes upon hover and click on cards.
https://github.com/DesignSafe-CI/portal/assets/62723358/bec01b71-aca0-46f1-ac85-48b6f8cdfc8e
Uses structural CSS from Core-Styles, then adds DesignSafe-specific skin CSS.
=> feat/DES-2725: app card styles

designsafe/apps/api/decorators.py, designsafe/apps/api/projects_v2/views.py
Add decorator to validate Tapis JWTs so that users can access endpoints from outside the portal.
* [DES-2706](https://tacc-main.atlassian.net/browse/DES-2706)
1. Make a request via cURL/Postman to `https://designsafe.dev/api/projects/v2` and pass a header with key `x-tapis-token` and the value of your tapis JWT.
=> TV3/DES-2706: Add view decorator using Tapis JWT auth

designsafe/settings/common_settings.py, designsafe/static/styles/app-card.css, designsafe/static/styles/app-page.css, designsafe/static/styles/main.css, designsafe/templates/base.j2, designsafe/templates/cms_page_for_app.html
Perform #1198 with a Page Template.
* [DES-2725](https://tacc-main.atlassian.net/browse/DES-2725)
* refactors #1198
Atop #1198:
- **added** new CMS page template
- **changed** app page styles to require class
- **added** first global CSS variable (`--ds-accent-color`)
- **added** custom class feature to `<body>`
1. Open https://www.designsafe-ci.org/rw/tools-applications/adcirc/.
2. Change page template to "Main Site App Page".
3. Remove snippet from page.
4. Verify page still looks like it does in #1198.
> [!WARNING]
> I do not know how to test DesignSafe changes.
Should look just like #1198.
This is an alternative to #1198, that introduces new features to DesignSafe. Using #1198 alone is acceptable.
=> feat: DES-2725 app page styles - via template

conf/docker/docker-compose-dev.all.debug.yml, designsafe/urls.py
- Sets the `--noasgi` flag on the daphne `runserver` command to bypass the asgi server in favor of the wsgi server for the `django` container.
https://github.com/django/daphne/blob/63790936d1f5728ff358ff9c5d519454c36f4e33/daphne/management/commands/runserver.py#L47
- Adds `staticfiles_urlpatterns()` to `urlpatterns` if `DEBUG` is `True`, to allow wsgi to serve staticfile assets locally without the need to `collectstatic` every time.
Note: This was implemented to resolve an issue we're seeing in local dev with the asgi `des_django` server crashing intermittently, e.g.:
```
des_django         | Application instance <Task pending name='Task-28' coro=<ASGIStaticFilesHandler.__call__() running at /opt/pysetup/.venv/lib/python3.11/site-packages/django/contrib/staticfiles/handlers.py:101> …
```
=> Use wsgi instead of asgi for local django container

designsafe/settings/common_settings.py, designsafe/static/styles/app-card.css, designsafe/static/styles/app-page.css, designsafe/static/styles/app-version-list.css, designsafe/static/styles/main.css, designsafe/templates/base.j2, designsafe/templates/cms_page_for_app.html
Add stylesheet for app page.
> [!IMPORTANT]
> After deploy:
> 1. Update these pages to use new template "Main Site App Page":
>     - https://www.designsafe-ci.org/rw/tools-applications/tools-applications-new/
>     - https://www.designsafe-ci.org/rw/tools-applications/adcirc/
> 2. Merge `main` into `feat/Tapis-v3-redesign`.
> 3. Sync **prod** server pages to **next** server.
> 4. Update "Version List" and "Related Applications" to use plugin.
> 5. Edit "Version List" as necessary.
* [DES-2725](https://tacc-main.atlassian.net/browse/DES-2725)
* refactored by #1199.
* **added** a stylesheet `app-page.css`
* **added** a stylesheet `app-version-list.css`
1. Open https://www.designsafe-ci.org/rw/tools-applications/adcirc/.
2. Verify styles are loaded from `app-page.css`.
3. Verify page looks …
=> feat: DES-2725 app page styles

designsafe/templates/cms_page_for_app.html
Fix "Main Site App Page" template causing page error. (The `addtoblock` tag requires `sekizai_tags`.)
* [DES-2735](https://tacc-main.atlassian.net/browse/DES-2735)
* fixes https://github.com/DesignSafe-CI/portal/pull/1199
- **added** load of missing tags for template
1. Open a page.
2. Change page template to “Main Site App Page”.
3. Page `<body>` is given a class `s-app-page`.
=> fix: DES-2735 app page template crash

designsafe/templates/cms_page_for_app.html
App Page template was not loading app page styles (because `addtoblock` must be used within a `block`).
* Hold.
* [DES-2735](https://tacc-main.atlassian.net/browse/DES-2735)
- **added** `block` around `addtoblock` that loads stylesheet
1. Create/Open a page.
2. Change page template to “Main Site App Page”.
3. Page `<head>` loads stylesheet `app-page.css`.
=> fix: des-2735 app page not loading app page css

designsafe/apps/workspace/templates/designsafe/apps/workspace/related_apps_plugin.html
Do not show list if "Related Applications" listing is empty.
* Hold.
* [DES-2738](https://tacc-main.atlassian.net/browse/DES-2738)
- **added** if/then around app listing render
1. Create/Have an app with no related apps.
2. Create/Have an app with some related apps.
3. Add "Related Apps" listing onto page for each.
4. Verify the former renders **not** title nor list.
5. Verify the latter **does** render title and list.
| no related apps | has related apps |
| - | - |
| <img width="1440" alt="DES-2738 no related apps" src="https://github.com/DesignSafe-CI/portal/assets/62723358/14377f72-0914-4dc1-9995-43a9844ae38c"> | <img width="1440" alt="DES-2738 has related app" src="https://github.com/DesignSafe-CI/portal/assets/62723358/c96e0d2a-3ad7-4c51-a14c-9c13f4ccf38a"> |
=> fix: des-2738 do not show empty releated apps list

designsafe/apps/workspace/templates/designsafe/apps/workspace/app_card.html, designsafe/static/styles/DesignSafe-Icons.css, designsafe/static/styles/DesignSafe-Icons.font.css, designsafe/static/styles/app-card.css, designsafe/static/styles/app-page.css, designsafe/static/styles/main.css
Fix final (I hope) UI bugs on Tools & Apps page.
* Hold.
- #1221
* [DES-2743](https://tacc-main.atlassian.net/browse/DES-2741): CMS: No List for Tag-less Apps
* [DES-2743](https://tacc-main.atlassian.net/browse/DES-2742): CMS: Update CSS Since Icon Class Rename
* [DES-2743](https://tacc-main.atlassian.net/browse/DES-2743): CMS: Container Too Wide
- #1224
* [DES-2744](https://tacc-main.atlassian.net/browse/DES-2744): CMS: UI When Hovering Over Card
- #1225
* [DES-2745](https://tacc-main.atlassian.net/browse/DES-2745): CMS: Resize Specific Icons Globally
1. Verify a card with no list does not show an empty gray stripe in the middle of the card.
2. Verify icon is:
- slightly bigger than title
- [aligns with the baseline](https://developer.mozilla.org/en-US/docs/Web/CSS/ver …
=> fix: app card design bugs DES-2741 through DES-2745

designsafe/apps/api/filemeta/tests.py, designsafe/apps/api/filemeta/views.py, designsafe/apps/api/views.py, designsafe/conftest.py
Allow JWT-authed requests for filemeta routes as follow on to https://github.com/DesignSafe-CI/portal/pull/1194
* [DES-2763](https://tacc-main.atlassian.net/browse/DES-2763)
1. See unit tests
2. Or manually test (find an existing file in a project)
3. curl --insecure -X POST -H "X-Tapis-Token: $JWT"  -H "Content-Type: application/json"  -d '{"system": "project-1234", "path": "/test/path.txt", "otherKey": "value", "anotherKey": "anotherValue"}' https://designsafe.dev/api/filemeta/
4. curl -H "X-Tapis-Token: $JWT"   https://designsafeci-next.tacc.utexas.edu/api/filemeta/project-1234/test/path.txt
=> task/DES-2763: Allow JWT-authed requests for filemeta routes

designsafe/apps/workspace/templates/designsafe/apps/workspace/app_variant_plugin.html, designsafe/static/styles/app-version-list.css
Make the "App Version Selection" look different if only one variant exists.
* Hold.
* [DES-2766](https://tacc-main.atlassian.net/browse/DES-2766)
- **added** different version list markup if only 1 variant
- **added** styles for `s-version-list` sans `<article>`s
1. Open page that has "App Version Selection" plugin instance.
2. Ensure the app selected is one that only has one variant.
3. Verify UI is:
> Already know everything?
> [[ Get Started ]](https://example.com/)
| before | after | in situ |
| - | - | - |
| ![before](https://github.com/DesignSafe-CI/portal/assets/62723358/a932a724-094c-43b3-8a2d-37c1a89bee50) | ![after](https://github.com/DesignSafe-CI/portal/assets/62723358/c4af4eb6-be3a-4a69-99cb-83e73eb2b359) | ![in …
=> fix: DES-2766 app with 1 variant needs diff list

designsafe/apps/api/filemeta/models.py, designsafe/apps/api/filemeta/tests.py
Fix file metadata route path issue so that all `path`'s are normalized to start with `/`.  See example problem in [DES-2767](https://tacc-main.atlassian.net/browse/DES-2767)
* [DES-2767](https://tacc-main.atlassian.net/browse/DES-2767)
1. Run unit tests
2. Find a top-level file in a project system
3. See if you can create metadata on file and see that has `/` at the start of path:
```
% curl --insecure -X POST -H "X-Tapis-Token: $JWT" -H "Content-Type: application/json" -d '{"system": "project-4983294419299528210-242ac118-0001-012", "path": "image.jpg", "otherKey": "value", "anotherKey": "anotherValue"}'  https://designsafe.dev/api/filemeta/
{"result": "OK"}%
% curl --insecure -H "X-Tapis-Token: $JWT"   https://designsafe.dev/api/filemeta/project-4983294419299528210-242ac118-0001-012/image …
```
=> task/DES-2767: fix file metadata route path issue

client/modules/_hooks/src/workspace/usePostJobs.ts, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/Toast/Notifications.module.css, client/modules/workspace/src/Toast/Toast.tsx, client/modules/workspace/src/Toast/index.tsx, client/modules/workspace/src/index.ts, client/modules/workspace/src/utils/index.ts, client/modules/workspace/src/utils/jobs.ts, client/modules/workspace/src/utils/notifications.ts, client/modules/workspace/src/utils/truncateMiddle.ts, client/package-lock.json, client/package.json, client/src/workspace/layouts/WorkspaceBaseLayout.tsx, designsafe/apps/api/views.py, designsafe/apps/webhooks/views.py, designsafe/apps/workspace/templates/designsafe/apps/workspace/index.j2, designsafe/static/scripts/ng-designsafe/providers/notifications-provider.js
- Display toast notifications for v3 job status updates
- Disable v2 angular toast notifications
* [DES-2758](https://tacc-main.atlassian.net/browse/DES-2758)
* [DES-2747](https://tacc-main.atlassian.net/browse/DES-2747)
1. Submit a job
2. Confirm toasts show in bottom left corner
TODO items for future:
=> task/DES-2758, DES-2747: Tapis v3 Job Notifications

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/AppsWizard/Steps.tsx, client/modules/workspace/src/utils/apps.ts
This PR handles updates to queue value changes specifically.
* [DES-2749](https://tacc-main.atlassian.net/browse/DES-2749)
* Steps: make configuration and outputs part of the fields, schema and defaults structure that Files and ParameterSets are using. 
* Because object.entries does not guarantee order, a field ordering is created in Steps for configuration and outputs.
* AppSchema:
* Includes all categories now.
* Configuration schema and fields is allowed to be re-created based on queue value changes.
* App submission form:
* Add states for schema, fields, steps. Schema state is needed to handle dynamic validation. Fields and Steps have description with field specific info.
* Add watch for queue value.
* Handle queue value changes.
1. Go to …
=> Task/DES-2749: Dynamically update nodes and cores validation when queue changes

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/src/workspace/layouts/AppsViewLayout.tsx
Use key to make new instance of component on navigation.
* [DES-2786](https://tacc-main.atlassian.net/browse/DES-2786)
* [DES-2782](https://tacc-main.atlassian.net/browse/DES-2782)
1. Add key property to App Form
2. set initial step state in additional to re-initialization of steps.
3. Remove unnecessary execSystemId initialization
1. Go to OpenFoam. Click Continue
2. Go to MPM, it has default file set, click continue - Should not see any error
3. Go back to OpenFoam, it should be in first step.
4. More testing steps in  [DES-2786](https://tacc-main.atlassian.net/browse/DES-2786)
=> Bug/DES-2786: Use key to make sure app instance is created on navigation

client/modules/_hooks/src/workspace/usePostJobs.ts, client/modules/workspace/src/AppsSubmissionDetails/AppsSubmissionDetails.tsx, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/AppsWizard/Steps.tsx
Various app form bugs related to steps, summary panel and express app usage.
* [DES-2781](https://tacc-main.atlassian.net/browse/DES-2781)
* [DES-2787](https://tacc-main.atlassian.net/browse/DES-2787)
* [DES-2788](https://tacc-main.atlassian.net/browse/DES-2788)
1. Shows steps that are available. U
2. Adjust step back and continue according to availability
3. Do not show node and core counts in summary/details if they are not visible in form. Summary panel has edit button, which might give a false indication that the fields are editable
4. Do not show allocation if it is not applicable.
5. Make node, core counts as optional in job post.
6. Summary panel should not show main category if they are empty.
These different apps, test the variations:
1. All steps are available: …
=> Bugs: App Form step and summary rendering fixes

client/modules/_hooks/src/systems/types.ts, client/modules/workspace/src/SelectModal/SelectModal.tsx
Use portal names to build system list in select modal
* [DES-2629](https://tacc-main.atlassian.net/browse/DES-2629)
1. System definition has notes section indicating portals applicable. Use that info.
2. Sort the list by private then public (I think other places in portal have similar listing order).
=> Task/DES-2629 Use portal names to build system list in select modal

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/AppsWizard/AppsWizard.tsx
Only validate current step on continue. Previous behavior was that it validated all the fields in the form.
* [DES-2789](https://tacc-main.atlassian.net/browse/DES-2789)
* Remove association of prev and next button onclick to form submit handler. This causes validation of the entire form to trigger. 
* An alternative approach is to write custom zod resolver, but that complicates things for the final submit button. This seemed to be a simpler solution.
* Use methods#trigger to trigger validation on the fields in the current step.
* z.string() does not check for strings with length 0 in zod (when compared with Yup). Adjust the validation.
1. Go to app: https://designsafe.dev/rw/workspace/opensees-express?appVersion=3.6.0
2. Hit continue and it should allow the user to continue to next …
=> Bugs/DES-2789 Only validate current step on continue

client/modules/workspace/src/AppsWizard/AppsFormSchema.ts
Zod does not automatically handle [undefined or empty values](https://github.com/colinhacks/zod/issues/310) in optional fields like Yup. Handle that specifically.
* [DES-2830](https://tacc-main.atlassian.net/browse/DES-2830)
Test below and contrast behavior with next:
1. Go to https://designsafe.dev/rw/workspace/paraview?version=5.10.0. Para view definition does not require input directory as required. 
* check if job submit button is enabled
* click continue and no error should be shown
* submit job
2. Enter junk value in input file for para view and it should show validation error. Submit is disabled. Continue is halting progress.
3. Submit paraview with valid file path in input.
=> Bug DES-2830: Handle zod optional fields for undefined or empty values

client/modules/_hooks/src/workspace/useAppsListing.ts, client/modules/workspace/src/AppsBreadcrumb/AppsBreadcrumb.tsx, designsafe/apps/workspace/api/views.py
Include app overview link in breadcrumbs
* [DES-2805](https://tacc-main.atlassian.net/browse/DES-2805)
1. Load an app that exists in your App Entries model
2. Confirm the overview link appears in breadcrumbs
3. Load an app that does not exist in your App Entries model
4. Confirm overview link does not appear, but app still loads
=> DES-2805: App overview breadcrumb

client/modules/_common_components/src/datafiles/DatafilesBreadcrumb/DatafilesBreadcrumb.tsx, client/modules/_hooks/src/datafiles/usePathDisplayName.ts, client/modules/workspace/src/SelectModal/SelectModal.tsx
* [DES-2876](https://tacc-main.atlassian.net/browse/DES-2876)
5 bugs fixed in this:
1) Select button is secondary button
2) Header now matches the label for System. Previously for Published, it showed Data Files
3) Default placeholder for search was empty - fixed the default state.
4) Disallow drilling into a file, change icon for file vs folder. 
5) Fix hyperlink for folder to not extend beyond the text.  Like this: 
[Design reference](https://xd.adobe.com/view/bab9a62d-3f2a-45f8-be0f-5680c474d9c1-efea/screen/4f5c890c-a48d-4a55-8d5d-4d400dd9222e/specs/)
1. Open Select File for an app: https://designsafe.dev/rw/workspace/openfoam
2. See the file vs folder differentiation for icon and link
3. Select button is secondary. 
4. Hyperlink fix
5. default search placeholder as soon as opening the …
=> Bug DES-2876: Select Modal bug fixes

client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/AppsWizard/FormField.tsx, client/modules/workspace/src/SelectModal/SelectModal.tsx
* [DES-2829 - System Selection bug](https://tacc-main.atlassian.net/browse/DES-2829)
* [DES-2828 - Validation bug](https://tacc-main.atlassian.net/browse/DES-2828)
* Use the file input value and pass the system information to select modal
* Adjust the values in the modal based on the system information
* Validation: trigger validation on return from modal selection
Use this app: https://designsafe.dev/rw/workspace/openfoam#!/
1. Validation bug:
* Add invalid file path in input file text box
* Error “Input file must be a valid Tapis URI, starting with 'tapis://'“ shows up.
* Use Select file and select a file.
* Error goes away
2. System selection bug:
* Select a file from community, hit continue.
* go back and select file again. The system name and all relevant labels should show …
=> Bugs/DES-2828 and DES-2829: Select Modal system selection and validation bugs

designsafe/apps/data/management/commands/es_setup.py
Update the management command to reindex ElasticSearch in the dev environment
* refactored so that it doesn't stop if one re-indexing step fails  (the publications reindexing fails currently)
* increased timeout to 300s (was 10s which was causing an issue sometimes)
* [DES-2879](https://tacc-main.atlassian.net/browse/DES-2879) - confirming that setup instructions for ReconPortal dev setup works
1. get password for ES staging
2. docker exec -it des_django bash
3. `python manage.py es_setup`
=> hotfix: update command to reindex on local development environment

designsafe/static/scripts/rapid/controllers/rapid-main-ctrl.js
DES-2875
In ReconPortal (`/recon-portal/`), user could zoom out too far and also do an endless scrolling.  See [DES-2875](https://tacc-main.atlassian.net/browse/DES-2875).  Now we limit where users can scroll to on the map and we do not let them zoom out farther than 2.
* [DES-2875](https://tacc-main.atlassian.net/browse/DES-2875)
1. go to /recon-portal
2. try to zoom out
3. try to pan left or right
before:
after:
=> task/DES-2875: prevent zooming out too far and endless scrolling in ReconPortal

client/src/styles.css, designsafe/static/styles/main.css
- Workspace content has full height of screen
- Workspace side nav is limited to full height of screen, and overflow scrolls
- Adjusts the `flex-basis` of `.o-site__body` to `0`, to account for DS header, removing annoying extra scroll from any react content
* [DES-2794](https://tacc-main.atlassian.net/browse/DES-2794)
1. Go to https://designsafe.dev/rw/workspace/opensees-sp-s3?appVersion=3.6.0 and confirm layout looks good. Side nav should scroll in place
2. Go to https://designsafe.dev/rw/workspace/history and confirm side nav and job status listing scroll in place, separately.
3. Confirm "Job Status" and "Applications:" headers above side nav do NOT scroll
=> task/DES-2794: Workspace Layout Adjustments

client/src/datafiles/layouts/projects/ProjectDetailLayout.tsx, client/src/styles.css
Redirect guest users to login (authorization page) when accessing non-published project
* [DES-1989](https://tacc-main.atlassian.net/browse/DES-1989)
Prevents an infinite spinner and api call when unauth'd users attempt to access a project. Also some minor styling changes to the alert error jsx component to make it look like the one provided by django for file listings.
1. Find the URL for an unpublished project that you should have access to.
2. Log out of DS  (may need to go to incognito mode of your browser)
3. Attempt to go to the URL of your project. It should present you with an error message, not a spinner.
=> task/DES-1989 - Redirect guest users when accessing non-published project

client/modules/_hooks/src/notifications/useNotifications.ts, client/modules/workspace/src/AppsSubmissionDetails/AppsSubmissionDetails.tsx, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsWizard.tsx, client/modules/workspace/src/JobStatusNav/JobStatusNav.tsx, client/modules/workspace/src/JobsDetailModal/JobsDetailModal.tsx, client/modules/workspace/src/JobsListing/JobsListing.tsx, client/modules/workspace/src/JobsListing/JobsListingTable/JobsListingTable.module.css, client/modules/workspace/src/JobsListing/JobsListingTable/JobsListingTable.tsx, client/modules/workspace/src/Toast/Toast.tsx, client/modules/workspace/src/utils/timeFormat.ts, client/src/styles.css, client/src/workspace/layouts/AppsPlaceholderLayout.tsx, client/src/workspace/layouts/WorkspaceBaseLayout.tsx, designsafe/apps/api/notifications/views/api.py, designsafe/apps/auth/views.py, designsafe/settings/common_settings.py, designsafe/static/scripts/ng-designsafe/components/notification-badge/notification-badge.component.html, designsafe/static/scripts/ng-designsafe/controllers/notifications.js, designsafe/static/scripts/ng-designsafe/providers/notifications-provider.js, designsafe/static/scripts/notifications/app.js
Fixes for issues discovered during the [testing session](https://tacc-main.atlassian.net/wiki/x/AYDiD) on 6/12/24.
* [DES-2831](https://tacc-main.atlassian.net/browse/DES-2831)
* [DES-2887](https://tacc-main.atlassian.net/browse/DES-2887)
* [DES-2889](https://tacc-main.atlassian.net/browse/DES-2889)
* [DES-2890](https://tacc-main.atlassian.net/browse/DES-2890)
* [DES-2891](https://tacc-main.atlassian.net/browse/DES-2891)
* [DES-2893](https://tacc-main.atlassian.net/browse/DES-2893)
* [DES-2899](https://tacc-main.atlassian.net/browse/DES-2899)
* [DES-2900](https://tacc-main.atlassian.net/browse/DES-2900)
- Fix bad job finished date while job is running
- Fix scroll for long app form
- Fix login redirect always going to /account
- Fix disabled state styling for AntD button elements, .e.g. …
=> Workspace fixes from 6/12 testing session

client/modules/datafiles/src/projects/BaseProjectDetails.tsx, client/modules/datafiles/src/projects/utils.ts
Improve links from DS projects to hazmapper maps:
* each URL that is created should point to a specific map on either prod, staging, local, dev or experimental Hazmapper deployments
* when we are in production DesignSafe, we only show maps that are from production hazmapper
* **And** if we are viewing a published project, we only want to send users to the public map (we assume it exists).
* [DES-294](https://tacc-main.atlassian.net/browse/DES-294)
1. Find a map with link to hazmapper maps in staging, prod, dev, or experimental (if you need help with this, let me know, i got a quick script from confluence info to grab ds-next DB and populate locally). (note, this bug can get in your way https://tacc-main.atlassian.net/browse/DES-2886)
2. Check that links go to correct map on the proper …
=> task/WG-294: improve links from DS projects to hazmapper maps

designsafe/apps/api/licenses/views.py
JupyterHub uses the Licenses API to enable MATLAB or LSDYNA for users in JupyterHub. This enables Tapis v3 JWT auth for this endpoint.
* [DES-2906](https://tacc-main.atlassian.net/browse/DES-2906)
1. Grab a jwt for your user, who is set as staff locally
a. e.g. via tapipy: `user.get_tokens()`, then `user.access_token.access_token`
2. curl your local endpoint: 
```
❯ curl -H "x-tapis-token: $jwt" -X GET https://designsafe.dev/api/licenses/MATLAB/\?username\=sal
{"license": "LICENSE HERE"}%
```
=> task/DES-2906: Enable JWT auth for License API

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx
Do not block continue to next step on invalid fields. Previously continue button was disabled or did nothing if there are validation errors. This bug removes that restriction
* [DES-2896](https://tacc-main.atlassian.net/browse/DES-2896)
1. https://designsafe.dev/rw/workspace/swbatch?appVersion=0.4.1
2. Click through continue without entering values
3. Click back and see that required fields have validation error messages.
=> Bug/DES-2896  Do not block continue to next step on invalid fields

client/modules/workspace/src/JobStatusNav/JobStatusNav.module.css, client/modules/workspace/src/JobStatusNav/JobStatusNav.tsx, client/src/styles.css
Set background color for Job Status Nav when hovered and when selected.
* [DES-2898](https://tacc-main.atlassian.net/browse/DES-2898)
1. Ensure job status nav appears as below when hovered, and selected. Confirm no link cursor when active and hovered while in Job Status.
=> task/DES-2898: Active job status nav styling

conf/env_files/designsafe.sample.env, designsafe/apps/workspace/api/views.py, designsafe/settings/common_settings.py
This is a request to remove certain allocation from list. Adding is as part of settings to customize exclusion
* [DES-2907](https://tacc-main.atlassian.net/browse/DES-2907)
Edit designsafe.env to add the following and make start and go to  https://designsafe.dev/rw/workspace/swbatch?appVersion=0.4.1
-     Test Case 1: ALLOCATIONS_TO_EXCLUDE=DesignSafe-DCV,TACC-ACI
This will show image at the bottom
-     Test Case 2: ALLOCATIONS_TO_EXCLUDE=DesignSafe-DCV
DesignSafe-DCV is not shown.
-     Test Case 3: No change in env file.
App form and Allocations functions as before.
-     Test Case 4: ALLOCATIONS_TO_EXCLUDE=
App form and Allocations functions as before.
=> Bugs/DES-2907: Exclude allocations at portal level

client/modules/_hooks/src/workspace/types.ts, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts
Render `jobAttributes` `notes.label` as form field label if it exists
* [DES-2911](https://tacc-main.atlassian.net/browse/DES-2911)
1. Go to https://designsafe.dev/rw/workspace/opensees-express?appVersion=3.6.0 and confirm labels for fields in "Parameters" step are human readable labels with proper capitalization, i.e. "TCL Script" and not "tclScript"
=> task/DES-2911: Render `jobAttributes` `notes.label` as form field label if it exists

client/modules/_hooks/src/workspace/types.ts, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/AppsWizard/FormField.tsx, client/modules/workspace/src/SelectModal/SelectModal.tsx
* Adjust the select modal to allow selection based on type (file, directory or both). See [design](https://xd.adobe.com/view/bab9a62d-3f2a-45f8-be0f-5680c474d9c1-efea/screen/4f5c890c-a48d-4a55-8d5d-4d400dd9222e/specs/).
Input field in app, will have this note (see [mpm](https://github.com/TACC/WMA-Tapis-Templates/blob/main/applications/mpm/app.json#L79)):
```
"notes": {
"selectionMode": "directory" // can be "directory", "file" or "both"
}
```
* System selection based on the value in input file is broken for certain paths, fix the regex to detect storage system. The regex was only considering paths like tapis://<storage_system>/path1 and failing on tapis://<storage_system>/path1/path2
* [DES-2888](https://tacc-main.atlassian.net/browse/DES-2888)
* …
=> Bugs/DES-2888: Select Modal - regex fix to detect storage system and file selection modes

client/modules/datafiles/src/DatafilesModal/RenameModal/RenameModal.tsx, client/src/datafiles/layouts/projects/ProjectPipelineSelectLayout.tsx
(1) Rename (DES-2835/2921): when renaming a file, the file extension was getting lost. (My Data, HPC Work, My Projects)
(2) Amend bullet (DES-2855): add bullet point to tell user to make changes in Curation Directory
* [DES-2835](https://tacc-main.atlassian.net/browse/DES-2835)
* [DES-2921](https://tacc-main.atlassian.net/browse/DES-2921)
* [DES-2855](https://tacc-main.atlassian.net/browse/DES-2855)
1. Test the Rename file works for different file extension. 
2. Verify Amend Metadata text includes bullet point that instructs user to make changes in Curation Directory.
Rename with file extension: 
Amend text (similar to Version):
=> Bug/DES-2835,2855: Ribbon Buttons and Amend text

client/modules/datafiles/src/projects/ProjectPipeline/PipelineSelectForPublish.tsx, client/modules/datafiles/src/projects/forms/BaseProjectForm.tsx, client/modules/datafiles/src/projects/modals/ProjectInfoStepper/FieldReconSteps.tsx
- Add line break for clarity in the process description
- Include instructions for submitting a ticket with project number, dataset name(s), and author order
- Remove text that instructs user that Keywords should be comma-separated.
* [DES-2922](https://tacc-main.atlassian.net/browse/DES-2922)
1. In an FR project, verify the text appears correctly.
2. In the Amends pipeline make verify the text is updated to include author order. 
3. When you click 'Edit Project', make sure keywords no longer includes "...comma-seperated."
=> bug/DES-2922: word/spelling/typo issues

designsafe/apps/auth/tasks.py
Add full ACL declaration for the My Data dir created for a user upon initial login. In particular we needed to make sure the `other` ACLs were closed off.
* [DES-2910](https://tacc-main.atlassian.net/browse/DES-2910)
1. Create a new test account and login to the portal. Confirm correct ACLs applied at `cloud.data.tacc.utexas.edu:/data/designsafe/mydata`
OR
1. Run the `setfacl` command via an ipython session with tapipy and check ACLs for that path:
```
client.files.setFacl(
systemId=system_id,
path=path,
operation="ADD",
recursionMethod="PHYSICAL",
aclString=f"d:u:{username}:rwX,u:{username}:rwX,d:u:tg458981:rwX,u:tg458981:rwX,d:o::---,o::---,d:m::rwX,m::rwX",
)
```
=> fix/DES-2910: Set default ACLs on new My Data dirs for `tg`, `other`, and `mask`

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts
When apps have custom label for env variables, the label cannot be used in job submission. Use the key instead.
* [DES-2940](https://tacc-main.atlassian.net/browse/DES-2940)
All three of them submitted the job:
1. ParameterSet->Env variables (lots of) with custom label:
https://designsafe.dev/rw/workspace/swbatch?appVersion=0.4.1
**Job submission json from client**
```
{
"operation": "submitJob",
"licenseType": null,
"isInteractive": false,
"job": {
"archiveOnAppError": true,
"appId": "swbatch",
"appVersion": "0.4.1",
"execSystemId": "stampede3",
"fileInputs": [
{
"name": "Working Directory",
"sourceUrl": "tapis://designsafe.storage.default/cyemparala/swBatch"
}
],
"parameterSet": {
"envVariables": [
{
"key": "name",
"value": "test"
},
{
"key": "ntrial",
"value": "3"
},
{
"key": "ns0", …
```
=> Bugs/DES-2940 Job submission fix for apps with env variables and custom label

designsafe/static/styles/_mixins/_link.scss, designsafe/static/styles/base.scss, designsafe/static/styles/bootstrap3.breadcrumb.css, designsafe/static/styles/main.css, designsafe/static/styles/variables.css, designsafe/templates/cms_breadcrumbs.html, designsafe/templates/cms_page.html, designsafe/templates/cms_page_for_app.html, designsafe/templates/menu/breadcrumb.html
Add TACC-style breadcrumbs to CMS.
<sup>(because there are already too many)</sup>
<sup>If merge, then I do this in #1269.</sup>
* [DES-2806](https://tacc-main.atlassian.net/browse/DES-2806)
* required by https://github.com/DesignSafe-CI/portal/pull/1269
* requires https://github.com/TACC/Core-Styles/pull/346
- **added** link state mixin & styles
- **moved** CSS variables
- **added** CSS variables
- **added** CMS breadcrumbs template
- **changed** DjangoCMS breadcrumb template
- **added** ID to App Category Listing heading
1. Have a CMS page that is heavily nested.
- See "**Testing**" > "**for DesignSafe App Redesign**" for suggestion.
3. Set template to "Main Site Page" (or non-Main templates).
4. Verify no breadcrumbs.
5. Set template to "Main Site App Page".
6. Review breadcrumbs:
- …
=> feat: DES-2806 cms breadcrumbs

designsafe/apps/api/projects_v2/operations/project_meta_operations.py
Persist HazMapper maps when changing project type. These maps are unique with respect to other metadata because they're populated by HazMapper and not by our form.
* [DES-2886](https://tacc-main.atlassian.net/browse/DES-2886)
=> Bug/DES-2886: Persist HazMapper maps when changing project type

client/modules/_hooks/src/datafiles/publications/useCitationMetrics.ts, designsafe/apps/api/publications/views.py
In Publications, when you open a publication, the browser makes a few calls to https://designsafeci-next.tacc.utexas.edu/api/publications/data-cite//  (ie no DOI is being sent over), and those calls hang for 30 seconds until they time out. These calls might be tying up the server and causing performance issues.
* [DES-3000](https://tacc-main.atlassian.net/browse/DES-3000)
In useCitationMetrics, I added a check that only returns getCitationMetrics if there is a DOI.
1. With Inspect open, go to Network. 
2. In publications, click on a publication. Check that useCitationMetrics is never called without a DOI
=> bug/DES-3000: Handle DOI not provided in useCitationMetrics

client/modules/datafiles/src/DatafilesModal/MoveModal/MoveModal.tsx, client/modules/datafiles/src/DatafilesModal/PreviewModal/PreviewMetadata.tsx, client/modules/datafiles/src/DatafilesModal/PreviewModal/PreviewModal.module.css, client/modules/datafiles/src/DatafilesModal/PreviewModal/PreviewModal.tsx, client/modules/datafiles/src/DatafilesToolbar/DatafilesToolbar.tsx, client/modules/datafiles/src/FileListing/FileListing.tsx, client/modules/datafiles/src/projects/ProjectCurationFileListing/ProjectCurationFileListing.tsx, client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx
Addresses the following tickets related to the Preview Modal:
DES-2924: Add file metadata to previews.
DES-2996: Use file name instead of full path in preview header.
DES-2998: Add move/download/copy to preview modal.
* [DES-2924](https://tacc-main.atlassian.net/browse/DES-2924)
* [DES-2996](https://tacc-main.atlassian.net/browse/DES-2996)
* [DES-2998](https://tacc-main.atlassian.net/browse/DES-2998)
=> task/DES-2924: Add metadata and move/copy/download buttons to preview modal

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/package-lock.json, client/package.json, client/src/workspace/layouts/AppsViewLayout.tsx
Add error boundary over the suspense for app form. This should handle both allocation and getApps suspenses.
* [DES-2872](https://tacc-main.atlassian.net/browse/DES-2872)
Use ErrorBoundary over suspense, following documentation [here](https://tanstack.com/query/latest/docs/framework/react/guides/suspense/#resetting-error-boundaries)
using react-error-boundary as mentioned above. 
1. Go to https://designsafe.dev/rw/workspace/opensees-does-not-exist
2. Once error is seen, hit a valid app in left nav and see that the error disappears. 
3. Any job submission related error are already handled by app form and do not fall into this (tested this by forcing bad data in client code).
=> Bugs/DES-2872: [AppForm] Handle axios request errors without crashing client

designsafe/static/styles/ng-designsafe.css
Adds a CSS class that should be added to the HTML app body in the admin form to apply consistent margins/padding.
* [WA-199](https://tacc-main.atlassian.net/browse/WA-199)
Usage: Add the `html-app-container` class to the top-level element in the app HTML, next to the jumbotron class.
=> Task/WA-199: Uniform margin/padding for HTML app content.

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/utils/apps.ts
App entry models have an icon field, which comes across in an app variant object as bundle_icon, which is accessible from the client side. Use this field as the first choice option for the app icon in the app form header, reverting to the app’s notes.icon if bundle_icon doesn’t exist or the app doesn’t exist in the portal database.
* [DES-2761](https://tacc-main.atlassian.net/browse/DES-2761)
1. Go to apps in app left-nav and check if icons show up.
2. Navigate directly to an app: https://designsafe.dev/rw/workspace/qgis-s3?appVersion=3.34.4 and check icon
=> DES-2761: [AppForm] Use bundle_icon field for app icon in App Form header

client/modules/_common_components/src/datafiles/FileListingTable/FileListingTable.tsx, client/modules/workspace/src/SelectModal/SelectModal.tsx
See [Referenced Design](https://xd.adobe.com/view/bab9a62d-3f2a-45f8-be0f-5680c474d9c1-efea/screen/4f5c890c-a48d-4a55-8d5d-4d400dd9222e/specs/)
New features added - back button and first row:
* First row match the last part of the breadcrumb.
* First row is selectable
* Back button moves up.
* In search mode, back button go to root of the system.
* [DES-2819](https://tacc-main.atlassian.net/browse/DES-2819)
* Updated file listing common component to take first row as optional parameter. This seems to be a good reliable way to handle the indent and go along with listing UX.
* Remove existing header component and add back button.
* Back button handler
Use an app like https://designsafe.dev/rw/workspace/mpm?appVersion=1.1.0
1. Go to my data, navigate into folder and see the first row …
=> [SelectModal] New features added - back button and first row

designsafe/apps/projects/models/agave/base.py
This is causing breaking issues in projects with >100 entities.
=> Hotfix: Bump entity listing limit to 300

designsafe/apps/accounts/templates/designsafe/apps/accounts/password_reset.html, designsafe/static/styles/variables.css
Convert "Password Reset" page to an "Account Help" page.
* [DES-2700](https://tacc-main.atlassian.net/browse/DES-2700)
* https://github.com/TACC/tup-ui/pull/449
* **changed** page title
* **changed** page content
* **added** page styles
* **added** global CSS variable
1. Open https://designsafe.dev/account/password-reset/.
2. Review.
| before | after |
| - | - |
| <img width="1275" alt="before" src="https://github.com/DesignSafe-CI/portal/assets/62723358/3c62571f-9170-4d70-9e21-06198cf64fc8"> | <img width="1275" alt="after" src="https://github.com/DesignSafe-CI/portal/assets/62723358/2307a897-e470-4160-b8af-5b692584d477"> |
1. Ideally, this change is coupled with change, on [login page](https://agave.designsafe-ci.org/authenticationendpoint/login.do?forceAuth=false&passiveAuth=false&relyin …
=> feat: DES-2700 Improve Login Support Page

client/modules/_hooks/src/notifications/useNotifications.ts, client/modules/workspace/src/Toast/Toast.tsx
- Add class `hover: pointer` to toast notification
- Increase toast duration to 5s
- Clicking a notification navigates to Job Status
- Notifications will not be marked as read by refocusing window
* [DES-2935](https://tacc-main.atlassian.net/browse/DES-2935)
1. Submit a job and confirm:
a. notification toast has `hover: pointer` css class
b. clicking a notification toast navigates to Job Status
c. a notification lasts 5 seconds if another does not replace it
d. navigating away from the tab, and back to it does not cause notifications to be read
=> task/DES-2935: Notifications fine tuning

client/modules/_hooks/src/workspace/usePostJobs.ts, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx
memoryMB is not a UI field, and is generally defined in app definition. There are scenarios where a queue has lower max memoryMB than what is defined in app definition. In those cases adjust the max before submitting a job
Only applicable to batch jobs, since queue is only available on batch
* [DES-3022](https://tacc-main.atlassian.net/browse/DES-3022)
* Adjust job submission logic to keep max memory within limits. 
1. rtx-dev has lower memory than small queue in frontera. submit a frontera job (https://designsafe.dev/rw/workspace/FigureGen-Serial?appVersion=51.0.0) with rtx-dev queue.
2. Submit a job on S3 to check for regression.
job payload shows memoryMB
=> [DES-3022] Handle memoryMB greater than queue maximum

Makefile, client/modules/workspace/src/JobsDetailModal/JobsDetailModal.tsx
- Update `Makefile` commands with `docker compose` instead of `docker-compose` after recent docker update.
- Show execution dir in Job Details while job is running
1. Update docker desktop and run `make start`, confirm works
2. Run a job and confirm appears as below
=> Quick: Update makefile and show execution dir

client/modules/datafiles/src/DatafilesHelpDropdown/DatafilesHelpDropdown.module.css, client/modules/datafiles/src/DatafilesHelpDropdown/DatafilesHelpDropdown.tsx, client/modules/datafiles/src/index.ts, client/src/datafiles/layouts/DataFilesBaseLayout.tsx
Add help dropdown with links to documentation.
=> Add dropdown with help links

designsafe/apps/workspace/api/views.py
Job listing is not showing 'finished' as status when interactive apps timeout.
There is existing logic to handle this, but this is not done for listing endpoint.
* [DES-3023](https://tacc-main.atlassian.net/browse/DES-3023)
* Update listing endpoint to also adapt to status changes. 
go to listing, find an existing interactive app that failed with timeout.  Just before vs after.
Before:
After:
This is broken in core also, created jira [WP-597](https://tacc-main.atlassian.net/browse/WP-597) to fix.
=> [Job Listing] Translate timeout errors to finished for interactive apps

client/modules/_hooks/src/workspace/useAppsListing.ts, client/modules/workspace/src/AppsBreadcrumb/AppsBreadcrumb.tsx, designsafe/apps/workspace/api/views.py
Add category link to app form breadcrumb
* [DES-3028](https://tacc-main.atlassian.net/browse/DES-3028)
1. Go to any DS app and confirm it has a category link, e.g. https://designsafe.dev/rw/workspace/adcirc?appVersion=55.01
2. Go to a private app, or unregistered public app and confirm it does not have a category link
With
Without
=> task/DES-3028: Add category link to app form breadcrumb

client/modules/_common_components/src/datafiles/FileListingTable/FileListingTable.tsx, client/modules/_hooks/src/datafiles/publications/index.ts, client/modules/_hooks/src/datafiles/publications/useDoiContext.ts, client/modules/_hooks/src/datafiles/useFileDetail.ts, client/modules/_hooks/src/datafiles/useFileListing.ts, client/modules/_hooks/src/datafiles/useFilePreview.ts, client/modules/datafiles/src/DatafilesModal/CopyModal/CopyModal.tsx, client/modules/datafiles/src/DatafilesModal/DownloadModal/DownloadModal.tsx, client/modules/datafiles/src/DatafilesModal/PreviewModal/PreviewModal.tsx, client/modules/datafiles/src/FileListing/FileListing.tsx, client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx, client/modules/datafiles/src/publications/modals/DownloadDatasetModal.tsx, client/src/datafiles/layouts/published/PublishedEntityListingLayout.tsx
Log the DOI when published files are copied/downloaded/previewed. Log the entity name and DOI when the publication collapse dropdown is opened.
* [DES-2601](https://tacc-main.atlassian.net/browse/DES-2601)
1. Download/copy/preview files in a publication in dev, and check that the DOI appears in the logs.
2. Download multiple files from separate DOIs on a publication's landing page. Check that each DOI shows up in the logs after `op=download`.
=> Task/DES-2601: DOI logging for file/publication operations

client/modules/workspace/src/JobsDetailModal/JobsDetailModal.tsx, client/modules/workspace/src/utils/jobs.ts
* Notes section is still in json and not parsed. Parse the notes json and correctly hide the fields.
* Show empty input or parameters - only ignore undefined input, but empty values are useful in debugging job results.
* [DES-3033](https://tacc-main.atlassian.net/browse/DES-3033)
1. Test paraview before and after fix.
2. Test empty optional fields and ensure they show up in details to allow user to see that optional data is not passed in.
Para view job details before:
Para view job details after:
Empty string for a parameter: (additional parameters for converter)
=> Bugs/DES-3033 [Job Details Modal] Do not show hidden fields and show fields with empty strings

designsafe/templates/403.html, designsafe/templates/404.html, designsafe/templates/500.html
Addresses the following items in the security audit:
1. Client-side template injection
2. Client-side HTTP parameter pollution
These issues were flagged because we were passing `request.path` as a query param to the ticket creation page, so the solution is to remove them and rely on other methods (e.g. splunk) to determine which paths raise exceptions.
=> Security: Remediate client-side injection in error pages

client/modules/datafiles/src/DatafilesModal/PreviewModal/PreviewModal.tsx
Hide the move and copy buttons in the preview modal when the user does not have permission for these operations.
* [DES-XXXX](https://tacc-main.atlassian.net/browse/DES-XXXX)
1. Check when previewing a file in a publication or NEES archive, the Move button is not displayed
2. Check that when previewing a file while logged out, the Copy button is not displayed.
=> Quick: Fix move/copy buttons in preview modal

designsafe/apps/workspace/templates/designsafe/apps/workspace/app_card.html, designsafe/static/styles/app-card.css
Highlight "SimCenter" flag on App Card.
<sup>Snippets — used on [prod](https://www.designsafe-ci.org/admin/djangocms_snippet/snippet/18/change) and [next](https://designsafeci-next.tacc.utexas.edu/admin/djangocms_snippet/snippet/18/change/) — are temporary because they rely on old markup.<sup>
* [DES-3046](https://tacc-main.atlassian.net/browse/DES-3046)
- **changed** how markup distinguishes Popular vs. SimCenter
- **added** styles for SimCenter
1. Load `/use-designsafe/tools-applications/` ([prod](https://www.designsafe-ci.org/use-designsafe/tools-applications/), [next](https://designsafeci-next.tacc.utexas.edu/use-designsafe/tools-applications/)).
2. Verify app that `is_popular` has **yellow** flag.
3. Verify app that `is_simcenter` has **light blue** flag.
| SimCenter | Popular |
| - …
=> enhance: DES-3046 highlight other flag of app card

client/modules/reconportal/.babelrc, client/modules/reconportal/.eslintrc.json, client/modules/reconportal/README.md, client/modules/reconportal/project.json, client/modules/reconportal/src/ReconPortal/ReconPortal.module.css, client/modules/reconportal/src/ReconPortal/ReconPortal.spec.tsx, client/modules/reconportal/src/ReconPortal/ReconPortal.tsx, client/modules/reconportal/src/ReconPortalHeader/ReconPortalHeader.module.css, client/modules/reconportal/src/ReconPortalHeader/ReconPortalHeader.spec.tsx, client/modules/reconportal/src/ReconPortalHeader/ReconPortalHeader.tsx, client/modules/reconportal/src/index.ts, client/modules/reconportal/tsconfig.json, client/modules/reconportal/tsconfig.lib.json, client/modules/reconportal/tsconfig.spec.json, client/modules/reconportal/vite.config.ts, client/src/main.tsx, client/src/reconportal/layouts/ReconPortalBaseLayout.tsx, client/src/reconportal/reconportalRouter.tsx, client/tsconfig.base.json
Add reactoportal react library with placeholder components.  This is to just illustrate where we should put things to follow the pattern that already exists in DesignSafe.
* [DES-2880](https://tacc-main.atlassian.net/browse/DES-2880)
0. See discussion on slack https://tacc-team.slack.com/archives/C07168Y3XGS/p1721769585646989?thread_ts=1721769343.928439&cid=C07168Y3XGS
1. Run and see that its there at /recon-portal
=> task/DES-2880: add module and placeholder components

client/modules/datafiles/src/publications/modals/DownloadDatasetModal.tsx
Log DOIs when downloading the archive of a project. If there are multiple DOIs, they will be formatted as a comma-separated list.
Sample log: 
```
des_django         | [METRICS] INFO views metrics.put:82: Data Depot user=jarosenb ip=172.19.0.1 agent=Mozilla/5.0 
(Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 
sessionId=h31uiskvoqy411zwd7bkzk16ga0zq1wb op=download info={'api': 'tapis', 'scheme': 'public', 'system':
'designsafe.storage.published', 'path': '/', 'body': {'paths': ['/archives/PRJ-3242_archive.zip']}, 'doi': '10.17603/ds2-x8rr-
yw04,10.17603/ds2-kzmf-ta46,10.17603/ds2-sa8v-0a73,10.17603/ds2-503c-ye80'}
```
=> Quick: Log DOIs when downloading project archives

designsafe/middleware.py, designsafe/settings/common_settings.py, designsafe/templates/maintenance.html
Allows toggling a maintenance page via the `DJANGO_MAINTENANCE` flag in designsafe.env. users who are already authenticated with staff-level permissions will be able to view pages behind the maintenance wall.
1. Temporarily set `DJANGO_MAINTENANCE = True` in common_settings.py
2. Confirm that maintenance page displays only when not authenticated as a staff-level user.
=> Quick: Maintenance toggle with staff bypass

client/modules/workspace/src/AppsWizard/AppsFormSchema.ts
regex parsing for fields is broken in app form.
[WP-650](https://tacc-main.atlassian.net/browse/WP-650)
* Use Zod#Refine instead chained .regex for existing ZodEffects.
For these two apps, test the following: 
https://designsafe.dev/rw/workspace/compress
https://designsafe.dev/rw/workspace/ls-dyna-stampede3?appVersion=2024R1
1. Open dev console.
2. Load the app, ensure there is app related info messages in dev tools console.
3. For compress, put a name for Archive (second step in form) which contains invalid characters like `&`
4. Similarly, for ls-dyna, in the second step, put a invalid name like test.pdf
5. Also use valid inputs and check if error message goes away in the form.
=> Bug: Use Zod.refine for regex fields

client/modules/datafiles/src/DatafilesToolbar/TrashButton.tsx, client/modules/datafiles/src/projects/ProjectCurationFileListing/ProjectCurationFileListing.tsx, client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx, client/modules/datafiles/src/projects/ProjectTree/ProjectTree.module.css, client/modules/datafiles/src/projects/ProjectTree/ProjectTree.tsx
Hotfixes for the curation frontend:
- Don't allow trashing of files that are associated to a category
- Show categories in the correct order in Publication Preview
- Improve UI in the Relate Data tree view for categories with multi-line names.
=> Curation frontend hotfixes 8/14/24

designsafe/apps/api/projects_v2/operations/project_system_operations.py, designsafe/apps/workspace/api/views.py
- Remove `portalName` filter in jobs listings by default to show all jobs for that user on the tenant.
- Unrelated: change the description of the setfacl job to no longer include "test"
* [WP-647](https://tacc-main.atlassian.net/browse/WP-647)
1. Submit a job from the command line / tapipy with no "portalName" tag. Alternatively, edit the workspace api code to not append the portalName tag upon job submission.
2. Go to the job listing page and confirm you see your job: https://designsafe.dev/rw/workspace/history
=> task/WP-647: Remove portal name filter for jobs by default

designsafe/apps/api/projects_v2/operations/datacite_operations.py
Datacite leaves DOIs in draft if the identifier types on related works are lower-cased.
=> Quick: Pass upper-cased identifier types to Datacite

designsafe/apps/api/projects_v2/views.py
We were passing in the PRJ number, which was resulting in malformed system IDs being passed to Tapis.
=> Pass project UUID instead of PRJ number when removing users from projects

client/modules/_hooks/src/workspace/types.ts, client/modules/datafiles/src/projects/modals/MetricsModal.tsx, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/utils/apps.ts, designsafe/apps/workspace/api/views.py, designsafe/settings/common_settings.py
For Express apps, user would like to have all their projects mounted and available.
Follow the solution from v2, where if _UserProject env var is available, then the list of projects is appended in this format:
uuid1, projectid2 uuid1, projectid2
upto 500.
QGIS app is updated to handle mapping the values.
* [WP-655](https://tacc-main.atlassian.net/browse/WP-655)
1. Go to https://designsafe.dev/rw/workspace/qgis_express?appVersion=3.36. Submit job and see if your projects are in MyProjects folder.
2. Go to https://designsafe.dev/rw/workspace/openfoam to test nothing is broken regression wise and job submission works. This app has env vars and making sure nothing in existing env var breaks
Followups:
* I move the script to create project mounts into a shared one - so it can be reused
=> Tasks/WP-655 Add support for User Projects in apps

designsafe/apps/workspace/cms_plugins.py, designsafe/apps/workspace/templates/designsafe/apps/workspace/app_variant_plugin.html, designsafe/apps/workspace/templates/designsafe/apps/workspace/app_variant_plugin_button.html, designsafe/static/styles/app-version-list.css
- Show disabled apps with disabled "Unavailable" button.
- Try to render app variant buttons at same width.
- <details><summary>Add app variant `version` in HTML `id` attr.</summary>
This lets JavaScript or CSS change specific buttons, e.g. make on read "Coming Soon".
</details>
* Hold.
* [WA-325](https://tacc-main.atlassian.net/browse/WA-325)
* same template as #1396
- **added** property to template context
- **added** attribute to app variant in template
1. Create/Have a CMS page that lists at least two app variants.
2. Uncheck "Enabled" on one variant.
3. Load the page.
4. **Verify** the disabled variant has disabled "Unavailable" button.
5. **Verify** each variant has unique `id` attribute.
| 4. setting | 4. render |
| - | - |
| <img width="392" alt="setting" …
=> enhance: WA-325 show disabled app variants in CMS

designsafe/apps/api/projects_v2/operations/project_publish_operations.py
From [Django docs](https://docs.djangoproject.com/en/5.1/ref/databases/#caveats):
> If a connection is created in a long-running process, outside of Django’s request-response cycle, the connection will remain open until explicitly closed, or timeout occurs. You can use django.db.close_old_connections() to close all old or unusable connections.
For projects >100GB, there have been sporadic timeouts/errors from keeping a database connection open while copying files.
=> Fix: Close open database connections in pipeline before copying files

designsafe/apps/api/projects_v2/operations/project_publish_operations.py
Need to send amend=False if the project is being versioned or initially published.
=> Fix: wrong argument being sent to fedora ingester

client/modules/datafiles/src/projects/forms/_fields/AuthorSelect.tsx, designsafe/apps/api/projects_v2/migration_utils/project_db_ingest.py
- Add a script to migrate legacy guest authors into the new `users` field
- Fix author selection to prevent errors when duplicate emails exist
=> Quick: Fixes for guest users

designsafe/apps/auth/tasks.py, designsafe/apps/auth/views.py
Dispatch the `new_user_alert` task when a user initially logs in. This was a part of the V2 OAuth flow that got omitted in V3.
=> Quick: Restore new_user_alert task on initial login

client/modules/datafiles/src/projects/forms/BaseProjectForm.tsx, client/modules/datafiles/src/projects/forms/ProjectCategoryForm.tsx, client/modules/datafiles/src/projects/forms/PublishableEntityForm.tsx, client/modules/datafiles/src/projects/forms/_fields/AuthorSelect.tsx
Addresses an issue where the author order would be reset each time experiment/simulation metadata was saved.
* [WC-87](https://tacc-main.atlassian.net/browse/WC-87)
When updating project metadata, the user-defined author order is used to sort the set of selectable authors. This prevents the author order from being overwritten by the arbitrary order in the `users` array.
1. In an Other-type project/Simulation/Experiment, set 3 or more authors.
2. In the Publication Pipeline, reverse the default author order
3. add a new author to the metadata from steps 1 and 2.
4. Confirm that the author order you set in step 2 is respected.
=> task/WC-87: Preserve author order when updating metadata

client/modules/datafiles/src/projects/BaseProjectDetails.tsx, client/modules/datafiles/src/projects/PublishedEntityDetails.tsx
href types should be uppercased (**DOI**/**URL** instead of **doi**/**url**) in the project metadata display.
=> Upper-case href types in project metadata

designsafe/apps/api/projects_v2/operations/project_publish_operations.py
Fixes a bug where even though each node in the project tree is supposed to be independent, we were assigning values in such a way that multiple nodes could contain the *same* value dictionary.
* [WC-92](https://tacc-main.atlassian.net/browse/WC-92)
=> BUG/WC-92: Deep-copy entity values before inserting them into the project tree

client/modules/datafiles/src/DatafilesModal/DownloadModal/DownloadModal.tsx, client/modules/datafiles/src/projects/BaseProjectDetails.tsx
Clear file selection when changing publication version. Fixes a bug where files from multiple versions of a publication could be selected at once. 
* [WC-95](https://tacc-main.atlassian.net/browse/WC-95)
=> Task/WC-95: Clear file selection when changing publication version

client/modules/datafiles/src/publications/PublishedListing/PublishedListing.tsx
If a publication has >3 keywords, only show the first 3 in the main listing.
* [WC-79](https://tacc-main.atlassian.net/browse/WC-79)
=> task/WC-79: Only show up to 3 keywords in the publication listing

client/modules/datafiles/src/projects/ProjectPipeline/PipelineOtherSelectFiles.tsx, client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx
When users click on directory links inside of the Publication Preview, they should be navigated to that directory in the Curation area.
* [WC-91](https://tacc-main.atlassian.net/browse/WC-91)
1. Go to a project with folders associated to some entity, and click "Prepare to Publish.
2. Check that when you click on a directory name in Publication Preview, you are
=> task/WC-91: Directories in Publication Preview should open in the Curation listing

client/src/datafiles/layouts/published/PublishedDetailLayout.tsx
* [WC-96](https://tacc-main.atlassian.net/browse/WC-96)
1. Open a non-Other type publication
2. Confirm that an `op=listing` log is generated with the correct project ID and version.
=> Task/WC-96: Log views of non-Other type publications as listings on the root dir

client/modules/datafiles/src/publications/PublishedListing/PublishedListing.tsx, designsafe/apps/api/publications_v2/views.py
Escape slashes in queries to prevent copy/pated DOIs from triggering errors.
* [WC-114](https://tacc-main.atlassian.net/browse/WC-114)
=> bug/WC-114: Fix DOI support in Publication search

client/modules/_hooks/src/systems/types.ts, client/modules/workspace/src/SelectModal/SelectModal.tsx, designsafe/apps/auth/backends.py
- Adds support for `cloud.data:/work` system in workspace File Select modal
- handles errors in the `revoke()` method in the auth backend
* [WP-685](https://tacc-main.atlassian.net/browse/WP-685)
1. In [client/modules/workspace/src/SelectModal/SelectModal.tsx:line 36](https://github.com/DesignSafe-CI/portal/blob/c659f4c412715a9cd7a72c2540f7a4e3052d1062/client/modules/workspace/src/SelectModal/SelectModal.tsx#L36) set `portalName` to `DesignSafeTest`
2. Go to https://designsafe.dev/rw/workspace/openfoam and open the select modal
3. Confirm that "Work" appears in the dropdown, and it points to the user's $STOCKYARD (`/work/numbers/username`)
- On release day of this feature and #1423 , we will need to update the `cloud.data` system `notes.portalNames[]` field to use `DesignSafe` instead of …
=> task/WP-685: user work workspace file select

client/modules/datafiles/src/projects/BaseProjectDetails.tsx, client/modules/datafiles/src/projects/PublishedEntityDetails.tsx, client/modules/datafiles/src/projects/SubEntityDetails.tsx, client/src/styles.css
Add a CSS class to render linebreaks in project descriptions.
* [WC-62](https://tacc-main.atlassian.net/browse/WC-62)
=> task/WC-62: respect line breaks in project/entity descriptions

client/modules/datafiles/src/nees/NeesDetails.tsx
Some DOIs have links to NEES projects that aren't compatible with the routing in the relaunched portal. This diff reformats the paths so that the listing will display.
* [WC-33](https://tacc-main.atlassian.net/browse/WC-33)
1. Visit https://designsafe.dev/data/browser/public/nees.public/NEES-2010-0921.groups/Experiment-3 and confirm that you get a listing and not an error.
=> Bug/WC-33: Fix NEES DOI links by appending project root to paths

client/modules/datafiles/src/projects/ProjectCollapser/ProjectCollapser.tsx, client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx
This is a performance enhancement- rendering tabes conditionally while opening the collapser could cause the UI to get laggy/framey.
=> Quick: Force collapse dropdowns to render before being activated

client/src/datafiles/layouts/DataFilesBaseLayout.tsx
Redirect to the publication listing instead of Community Data. when the user selects "Data Depot" from the top navbar.
=> Quick: Redirect unauthenticated users to publications by default

client/modules/datafiles/src/projects/ProjectCollapser/ProjectCollapser.tsx, client/modules/datafiles/src/projects/ProjectTree/ProjectTree.tsx, client/modules/datafiles/src/projects/constants.ts
The `designsafe.project.field_recon.collection` entity type wasn't supported in the frontend and would cause an exception when trying to look up its display attributes.
=> Hotfix: Fix display bug for generic FR collections from 2019

designsafe/apps/rapid/views.py, designsafe/static/scripts/rapid/controllers/rapid-main-ctrl.js, designsafe/static/scripts/rapid/html/index.html, designsafe/static/scripts/rapid/styles/rapid.css
Requested UI changes from Tracy before 4Kitchens and CMD design review
* [WG-376](https://tacc-main.atlassian.net/browse/WG-375)
- Removes external dataset header and toggle and associated styles
- Changes order of Clear and Hide buttons, adds filter
to the wording in the button
- Adds search bar on button row
- Adds checkbox to hide and add DesignSafe data
- Adds message in sidebar if no results are returned for a filter search
1. Go to https://designsafe.dev/recon-portal/ and check search functionality
2. Use search bar in sidebar to ensure it still works with the filters
Main screen with filters showing
No dataset match for filters
=> Task/wg 375 recon portal UI changes

client/modules/datafiles/src/projects/ProjectCitation/ProjectCitation.tsx
Filter non-author "authors" when formatting citations.
* [WC-123](https://tacc-main.atlassian.net/browse/WC-123)
=> hotfix/WC-123: Filter citation authors to remove those with authorship=false

client/modules/_hooks/src/workspace/types.ts, client/modules/workspace/src/utils/jobs.ts
Handle case where `job.tags` is `null`.
1. Comment out https://github.com/DesignSafe-CI/portal/blob/6f5520c7f5bb0aa0c3489d0438a60ff1fbac4207/designsafe/apps/workspace/api/views.py#L781-L784
2. Submit a non-interactive job
3. Confirm that "View Details" modal works properly
=> Quick: fix case when `job.tags` is null

client/modules/datafiles/src/DatafilesToolbar/DatafilesToolbar.tsx
The Move button needs to allow for selecting multiple files.
All buttons needs to handle if a .hazmapper file is anywhere in the selected files, not just the first file in the array.
* [WP-707](https://tacc-main.atlassian.net/browse/WP-707)
1. Check that selecting multiple files in a project within the project.
2. Check that selecting multiple files in a publication does not enable the Move action.
3. Check that selecting a hazmapper file does not allow rename/move/copy/trash/download, no matter if it was the first or later file selected in a multiselect.
=> WP-707: Data Depot Toolbar updates

conf/env_files/designsafe.sample.env
Add missing setting.
* follow-up to #1472
* **add** `REACT_RENDER` to `designsafe.sample.env`
1. Run project.
2. Visit (`/rw/`)`workspace`.
3. Verify app loads.
Skipped.
=> fix: add RENDER_REACT to designsave.sample.env

designsafe/static/styles/app-card.css
Fix alignment of gray box of hazard tags on an app card on Tools & Apps page.
> [!IMPORTANT]
> To self:
> 1. If approved, publish page (to activate [snippet](https://designsafe-ci.org/admin/djangocms_snippet/snippet/21/change/)).
> 2. If deployed, delete [snippet](https://designsafe-ci.org/admin/djangocms_snippet/snippet/21/change/).
* [DSAPP-57](https://tacc-main.atlassian.net/browse/DSAPP-57)
* requires https://github.com/TACC/Core-Styles/pull/405
* **changed** version of Core-Styles for `c-app-card`
* **added** forced height on `c-app-card` description
1. Replicate layout on prod with code from this branch:
- **A**: [snippet](https://designsafe-ci.org/admin/djangocms_snippet/snippet/21/change/) and [top 3 simulation apps](https://designsafe-ci.org/use-designsafe/tools-applications/)
- …
=> fix: DSAPP-57 alignment of app card hazard tags

designsafe/apps/auth/tasks.py
Resolve race condition where the `setfacl` step in onboarding fails because the `mkdir` command has not been run. Instead of resolving each error individually, resolve all each time. No error is thrown if the particular issue has already been resolved and is "re-resolved".
=> Hotfix: Resolve onboarding mkdir race condition

client/src/workspace/layouts/AppsViewLayout.tsx, client/src/workspace/layouts/layout.module.css, designsafe/static/styles/ng-designsafe.css
Move and change `.html-app-container` CSS.
> [!NOTE]
> After prod deploy, delete `<style …>…</style>` from HTML of each such variant. (See "Notes".)
* [DSAPP-60](https://tacc-main.atlassian.net/browse/DSAPP-60)
- **delete** old global styles
- **add** new styles (and put them where they are used)
> [!WARNING]
> Not deployed to dev. To test, do so locally.
1. Run/Deploy site.
2. Create/Have an app with a variant that has "HTML" e.g. [EE-UQ (dev admin)](https://designsafeci-dev.tacc.utexas.edu/admin/workspace/applistingentry/22/change/).
3. Open that variant in the workspace e.g. [EE-UQ (dev workspace)](https://designsafeci-dev.tacc.utexas.edu/workspace/eeuq).
4. Verify class `._html-app-container_...` is on the wrapper div (from workspace code).
5. Verify `<p>`’s inside have extra margin …
=> enhance(client): html-app-container css

designsafe/apps/api/projects_v2/elasticsearch.py, designsafe/apps/api/projects_v2/tasks.py, designsafe/apps/api/publications_v2/elasticsearch.py, designsafe/celery.py, designsafe/settings/elasticsearch_settings.py, designsafe/settings/test_settings.py
Create/update an index of published projects so that the Data team can run analyses.
* [WC-125](https://tacc-main.atlassian.net/browse/WC-125)
```
from django.conf import settings
from designsafe.libs.elasticsearch.indices import setup_index
from designsafe.apps.api.projects_v2.elasticsearch import reindex_projects
prj_conf = settings.ES_INDICES['projects_v2']
setup_index(prj_conf, force=True)
reindex_projects()
```
=> Task/WC-125:  Create/update projects index for V3

client/modules/datafiles/src/nees/NeesDetails.tsx, designsafe/apps/nco/managers/ttc_grants.py
Mongodb queries by default are case insensitive, and NCO requested, if possible, for it to be made case-insensitive.
* [WP-698](https://tacc-main.atlassian.net/browse/WP-698)
Added "i" flag to the regex queries that are part of the text search field to make them case-insensitive.
1. Page is here: [local-url]/nco/ttc_grants
2. search for "simpson" and "Simpson" should show the same results.  Clear the search between attempts to make sure you're seeing the search happen.  Also note that you have to click the search button manually for the search to happen.
Need to be on the vpn for the connection to the nco mongodb to work.
Also, this solution will work, but if the database grows much larger, this could cause the searches to become slow.  However, due to how the search needs to be run, …
=> task/WP-698: NCO text search made case insensitive

designsafe/apps/nco/managers/ttc_grants.py, designsafe/static/scripts/nco/components/nco-ttc-grants/nco-ttc-grants.template.html
Adding in Co-PIs to the searchable fields for the text search
* [WP-718](https://tacc-main.atlassian.net/browse/WP-718)
Updated label for text search
Added Co-PI field to db query
1. Go to /nco/ttc_grants
2. Look in the listing for a Co-PI in one of the rows, then search on that name.
3. Test with and without capitalization, meaning the search should be case-insensitive.
4. Test on a Co-PI that has a comma after their last name, to double check that the search returns that listing.
5. Example: 'millea`/'Millea' should return 1 result
Sometimes on local dev, the searches take a bit to respond and update the page and it won't look like anything is happening.  If you've run a search and nothing is changing, give it a bit and it should update.
=> task/WP-718: NCO Search includes Co-PIs

designsafe/apps/onboarding/steps/project_membership.py
rtpy has the args to `create_ticket` documented incorrectly. Passing `requestors` instead of `requestor` can lead to weird behavior including email confirmations getting lost.
=> Quick: Fix args for  RT ticket creation during onboarding

designsafe/apps/onboarding/steps/system_access_v3.py, designsafe/libs/common/decorators.py
Add `retry` decorator, and retry steps during System Access step known to be time-sensitive.
* [WI-221](https://tacc-main.atlassian.net/browse/WI-221)
1. Create a test user and delete their 'My Data'
2. Run the System Access step
3. Confirm that the step retries while the setfacl command is being run, until it succeeds.
Relevant logs showing retry
```
des_workers        | [DJANGO] $(processName)s INFO 2024-11-13 20:19:16,515 receivers designsafe.apps.api.notifications.receivers.send_setup_event:53: Sending setup event through websocket
des_workers        | [DJANGO] WARNING 2024-11-13 20:19:17,574 decorators designsafe.libs.common.decorators.f_retry:127: <class 'tapipy.errors.UnauthorizedError'>, Retrying in 3 seconds...
des_workers        | [DJANGO] $(processName)s WARNING 2024-11-13 …
```
=> task/WI-221: Add retry decorator and retry system access steps during onboarding

client/modules/workspace/src/AppsWizard/AppsFormSchema.ts, client/modules/workspace/src/utils/apps.ts
This PR clairifies the text in App Form to differentiate between interactive app vs all other apps.
The label of max job runtime and references to job are changed to "interactive session".
[WA-343](https://tacc-main.atlassian.net/browse/WA-343)
1. View app form for interactive app: https://www.designsafe-ci.org/workspace/qgis-s3?appVersion=3.34.4
2. View app form for regular app: https://designsafe.dev/rw/workspace/mpm?appVersion=1.1.0
=> WA-343: App Form - label update for interactive session

client/modules/_hooks/src/workspace/useInteractiveModalContext.ts, client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/modules/workspace/src/JobsDetailModal/JobsDetailModal.tsx, client/modules/workspace/src/JobsListing/JobsListing.tsx, client/modules/workspace/src/Toast/Toast.tsx
- Displays remote job id (slurm job id) in job detail modals, if it exists
- Closes interactive session modal if job webhook comes back with failed status
* [DSAPP-77](https://tacc-main.atlassian.net/browse/DSAPP-77)
* [WA-363](https://tacc-main.atlassian.net/browse/WA-363)
1. Go to https://designsafe.dev/rw/workspace/history and confirm `Remote Job Id` displays for jobs that are past the queuing stage
2. Submit an interactive job with a runtime of 10 minutes, then confirm the modal closes itself once the job ends
=> task/DSAPP-77,  task/WA-363:  Remote Job Id & Interactive Session Modal handling

client/modules/datafiles/src/FileListing/FileListing.module.css, client/modules/datafiles/src/FileListing/FileListing.tsx
Fix long file names showing up as just an ellipsis
Before: 
After:
=> Quick: Fix long filenames showing up as ellipsis

designsafe/apps/api/datafiles/handlers.py, designsafe/apps/api/datafiles/operations/tapis_operations.py, designsafe/apps/api/datafiles/views.py, designsafe/apps/workspace/api/views.py, designsafe/settings/common_settings.py
Includes audit tracking id in audit logs, and sets as `X-Tapis-Tracking-Id` header in tapipy jobs requests.
* [task/WI-224](https://tacc-main.atlassian.net/browse/task/WI-224)
=> task/WI-224: Include tracking id in audit logs

designsafe/apps/api/datafiles/operations/box_operations.py, designsafe/apps/api/datafiles/operations/dropbox_operations.py, designsafe/apps/api/datafiles/operations/googledrive_operations.py, designsafe/apps/api/datafiles/operations/tapis_operations.py
Datafiles operations can now receive a tapis tracking id as a keyword arg, so they need to have their function signatures updated to accept that argument without raising an exception.
=> Hotfix: Ensure all datafiles operations accept kwargs

client/modules/workspace/src/AppsSubmissionForm/AppsSubmissionForm.tsx, client/src/onboarding/layouts/OnboardingUserLayout.tsx
Ticket links were using a URL convention from CEP instead of the Designsafe page.
=> Hoffix: Fix ticket links in apps/onboarding pages

designsafe/apps/auth/backends.py, designsafe/apps/workspace/api/views.py
- Fixes an error where METRICS logging would fail when attempting to log the tapis response in the case where the response is a "push keys" signal sent to the frontend from the portal jobs api
- Cleans up the logout backend: primarily addressing a rare error where the `user` object is `None`
1. Submit a job for a system where you need credentials
2. Confirm process works normally, and metrics log successfully
=> Quick: fix error when logging metrics on jobs push keys response

designsafe/apps/api/datafiles/operations/tapis_operations.py
If tracking ID isn't passed, default to an empty string. Null values produce errors in Tapis.
=> Quick: Prevent null value from being passed as Tapis tracking ID

designsafe/apps/workspace/api/views.py
Long job response objects were exceeding the splunk log line limit.
=> slim down audit job response log

designsafe/settings/common_settings.py
Adds a log filter to the metrics logger that generates a UUID for each log. This will help with deduplication in case we need to re-ingest logs over a specific time frame.
* [WI-232](https://tacc-main.atlassian.net/browse/WI-232)
=> Task/WI-232: Add guid to metrics logs for de-duping audit trails.

designsafe/settings/common_settings.py
The metrics logger name must exactly match the filter for the guid.
=> Quick: fix metrics logger name

designsafe/static/styles/app-card.css, designsafe/static/styles/app-page.css
Make descriptions of App Cards (on [Tools & Applications page](https://designsafe-ci.org/use-designsafe/tools-applications/)) (maximum) 3 lines tall, not two.
* [DSAPP-87](https://tacc-main.atlassian.net/browse/DSAPP-87)
* **changed** cross-file CSS math to use variables
* **added** 3 lines value override
1. Open https://designsafeci-next.tacc.utexas.edu/use-designsafe/tools-applications/.
2. Change window size until Jupyter card description shows three lines.
- If it shows two lines and "..." truncation, then I failed.
https://github.com/user-attachments/assets/965a79bb-7049-48d0-be33-337c37905dac
=> fix: app cards only two lines tall

designsafe/apps/api/projects_v2/elasticsearch.py
Quick: Add `created` date when indexing pubs for the data group.
=> add creation date to indexed projects in Elasticsearch

client/modules/datafiles/src/projects/ProjectCitation/ProjectCitation.tsx, client/modules/datafiles/src/projects/ProjectPipeline/PipelineOrderAuthors.tsx
Replace `"PROJECT_NAME", in PROJECT_NAME` with just the name of the project for type Other.
* [WC-173](https://tacc-main.atlassian.net/browse/WC-173)
1.
=> task/WC-173: Remove duplicate project name in citation for type Other

designsafe/apps/api/projects_v2/operations/project_system_operations.py, designsafe/settings/common_settings.py, designsafe/settings/test_settings.py
Replace cloud.corral with cloud.data in project system definitions.
=> Hotfix: Replace cloud.corral with cloud.data in project system operations

designsafe/apps/data/management/commands/es_setup.py
Some indices were getting auto-initialized with incorrect mappings when running this script.
=> Quick: fix es_setup util to actually initialize indexes

designsafe/apps/api/projects_v2/operations/datacite_operations.py
Datacite’s OAI tool doesn’t correctly parse given/family names when converting metadata to Dublin Core. This diff changes our ingest util to construct the full name manually when formatting metadata.
* [WC-197](https://tacc-main.atlassian.net/browse/WC-197)
=> task/WC-197: Workaround for datacite OAI-MPH author bug

designsafe/apps/workspace/api/views.py
Add a `_TAS_DIR` environment variable to interactive app job submissions to handle mounting work directories in our interactive VMs
=> Quick: add _TAS_DIR env var for interactive apps for work mounts

client/modules/datafiles/src/DatafilesToolbar/DatafilesToolbar.tsx
* [WP-637](https://tacc-main.atlassian.net/browse/WP-637)
- Add check for `USER_WORK_SYSTEM` for determining if selected files can be trashed or not (copying approach for download eligibility)
1. Go to Data Depot > Work file listing (hosted on cloud.data)
2. Confirm that, for any file(s)/folder(s) selected in this listing, the `Trash` toolbar button is disabled
3. Go to Data Depot > My Data file listing and confirm Trash behavior is unchanged
=> task/WP-637: Disable trash for VM or HPC file listings

designsafe/apps/accounts/forms.py
Noticed this during intern onboarding- the profile update form auto-generates a field for the `setup_complete` attribute, which could interfere with onboarding.
=> Quick: Exclude 'setup_complete' from the profile update form

client/modules/datafiles/src/DatafilesSideNav/DatafilesSideNav.tsx, designsafe/apps/box_integration/integrations.py, designsafe/apps/googledrive_integration/integrations.py
Remove Box and Google Drive integration.
This is just UI change, not functional.
* [WP-773](https://tacc-main.atlassian.net/browse/WP-773)
1. Navigate to Data Depot. Box.com and Google Drive options should not be displayed in left navigation bar.
2. Navigate to /account/applications/.  Box.com and Google Drive options should not be displayed as 3rd Party Applications.
=> Task/wp 773 remove Box and Google Drive integration

client/modules/_hooks/src/apiClient.ts, client/modules/_hooks/src/datafiles/useUploadFile.ts, client/modules/_hooks/src/datafiles/useUploadFolder.ts
Defaults to 1min now for timeout, and increases upload timeouts to 5min
1. Upload a largeish file and confirm it succeeds
2. In `client/modules/_hooks/src/datafiles/useUploadFile.ts, change the default timeout to `1000`, 1 second. Upload the same file and watch it fail.
=> Hotfix: increase axios timeout

client/modules/datafiles/src/projects/utils.ts
Our way to filter non-production maps on prod broke with the newish host for dev/pprd (`pprd.designsafe-ci.org`).  This PR improves the filtering.
* [WG-463](https://tacc-main.atlassian.net/browse/WG-463)
=> task/WG-463: improve hazmapper map filtering in pprd

designsafe/settings/common_settings.py
Addresses RT ticket https://consult.tacc.utexas.edu/Ticket/Display.html?id=103566 by adding preview support for the following ascii file extensions:
- `.env`
- `.exitcode`
-`.pid`
=> RT Support preview for Tapis output files

designsafe/apps/api/projects_v2/views.py
Fix a bug where project admins would get a permission error when creating entities on behalf of users.
* [WC-247](https://tacc-main.atlassian.net/browse/WC-247)
=> bug/WC-247: Allow project admin users to create entities

designsafe/apps/api/datafiles/views.py, designsafe/settings/common_settings.py
- Add a log filter that hashes the session key before writing to Splunk.
- Hash session keys passed as `tapis-tracking-id` headers.
* [WI-272](https://tacc-main.atlassian.net/browse/WI-272)
=> task/WI-272: Hash session keys before writing to logs

client/modules/_hooks/src/reconportal/index.ts, client/modules/_hooks/src/reconportal/useGetOpenTopo.ts, client/modules/_hooks/src/reconportal/useGetReconPortalEventTypes.ts, client/modules/_hooks/src/reconportal/useGetReconPortalEvents.ts, client/tsconfig.base.json
Refactor types and hooks in recon-portal:
* Updated hook names to include more info (i.e. recon portal and open topo)
* Improve types
* added some missing properties
* use `geojson`' `FeatureCollection`
* used types (e.g. useQuery typing and response typing)
* Removed calculation of midpoint.  can always revert this but assume we'll show the actual geometry of open topo data due to the new design. 
* [WG-486](https://tacc-main.atlassian.net/browse/WG-486)
Change `client/modules/reconportal/src/ReconPortalHeader/ReconPortalHeader.tsx` to:
```
import React from 'react';
import styles from './ReconPortalHeader.module.css';
import { useGetOpenTopo, useGetReconPortalEvents, useGetReconPortalEventTypes } from '@client/hooks'
import { Spin } from 'antd';
export const ReconPortalHeader: React.FC …
```
=> task/WG-486: refactor types and hooks in recon-portal

designsafe/apps/api/datafiles/views.py, designsafe/settings/common_settings.py
Fixes a bug where unauthenticated users (`session_id=None`) were seeing 500 errors because their session ID couldn't be hashed.
=> Quick: Fix 500 error when session_id is None

client/modules/datafiles/src/DatafilesModal/NewFolderModal/NewFolderModal.tsx
Addresses an issue where the "New/Create Folder" modal in Data Depot did not clear the folder name input field between uses. Now, every time the modal is opened, the input is reset.
* [WP-640](https://tacc-main.atlassian.net/jira/software/c/projects/WP/boards/46?assignee=712020%3Aa66df098-eece-4aae-a1c3-6b226867069f&selectedIssue=WP-640)
Added form reset login using Form.useForm() adn resetFields() to clear the folder name input every time the modal is opened.
1. Go to Data Depot
2.Select a Project
3.Add → New Folder
4.Enter some value and create a folder.
5.Repeat step 3, the textbox should be empty.
N/A
=> Create folder text box clears every time its opened

client/src/workspace/layouts/AppsViewLayout.tsx, designsafe/apps/api/datafiles/handlers.py, designsafe/apps/api/datafiles/views.py, designsafe/apps/onboarding/steps/system_access_v3.py, designsafe/apps/workspace/api/views.py, designsafe/settings/common_settings.py
- Handle TMS credential creation in datafiles for failed TMS system listings
- Do not show push keys modal in apps for TMS_KEYS systems
1. Delete your `designsafe.storage.default` credential
2. Navigate to your my data listing
3. Confirm creds are created in the background and your listing succeeds
=> Add handling for tms credential creation in datafiles get view

client/modules/reconportal/src/LeafletMap/LeafletMap.tsx, client/modules/reconportal/src/LeafletMap/OpenTopoPopup.tsx, client/modules/reconportal/src/LeafletMap/leafletUtil.tsx, client/modules/reconportal/src/LeafletMap/utils.ts, client/package-lock.json, client/package.json
Show OpenTopography datasets on map.
Display OpenTopography datasets by rendering the provided GeoJSON (always a polygon or multipolygon). In addition, place a marker for each dataset at one of its vertices to
Note, there is some follow-up work:
- Determine style for open topo datasets (Issues with this in https://tacc-main.atlassian.net/browse/WG-510)
- Include selected feature when determining if open topo datasets should be shown. (waiting onhttps://github.com/DesignSafe-CI/portal/pull/1558)
* [WG-495](https://tacc-main.atlassian.net/browse/WG-495)
1. Zoom into an area (Austin or Florida Panhandle)
2. Click on Marker to see popup
3. Click on polygon to see popup
4. Check contents of popup and link to OpenTopo website.
=> task/WG-495: show open topo datasets on leaflet map

client/modules/datafiles/src/projects/ProjectCitation/ProjectCitation.tsx, client/modules/datafiles/src/publications/modals/DownloadDatasetModal.tsx
Updating text for usage figures to match the dataset metrics modal, with mouseovers.
Updated the Data Transfer Guide link in the download dataset modal that got missed in a previous PR.
* [WC-234](https://tacc-main.atlassian.net/browse/WC-234)
1. Go to publication view for PRJ-3963 (only specified because it's known to have a large zip for testing the download dataset url change, otherwise can use any publication)
2. Check that the highlighted info in the citation area with usage figures shows the correct text, plus the mouseover. (correct text and mouseover is in the jira task)
3. Click the "download dataset" button to view the modal, and click the data transfer guide link.  Update the url to point to prod rather than local and make sure it shows the data transfer guide and not a "this …
=> WC-234: Change Usage Figures Language

client/modules/workspace/src/components/SystemStatusModal/SystemStatusModal.tsx
Fixed issue when selecting either a VM or non-HPC app that it would not show any queues for systems until manually pressed on.
* [WP-686](https://tacc-main.atlassian.net/browse/WP-686)
-Modified SystemStatusModal.tsx to automatically default to Vista system when the app's default execution system is not one of the main HPC systems (Frontera, Vista, Stampede3, Lonestar6)
-Added useEffect to automatically switch to Vista when activeSystem is not in the available systems list
1. Open app using VM or non-hpc
2.Verify Vista is selected when system status modal is opened up
=> Fixed vm or non-hpc app to default system selection

poetry.lock, pyproject.toml
NetworkX plans to introduce breaking API changes to the `node_link_data` and `node_link_graph` methods in an upcoming minor version. This PR pins us to the version that we launched with in the original Tapis V3 migration.
=> Quick: Pin NetworkX to v3.2.1

client/modules/workspace/src/components/SystemStatusModal/SystemStatusModal.tsx, client/modules/workspace/src/utils/apps.ts
Fixes crash when accessing apps without a exec system.
* [WP-1016](https://tacc-main.atlassian.net/jira/software/c/projects/WP/boards/46?assignee=712020%3Aa66df098-eece-4aae-a1c3-6b226867069f&selectedIssue=WP-1016)
-Used optional chaining to prevent accessing properties of undefined
-if jobAttributes or execSystemId is missing return empty array
1. Open app that dosen't have exec system like Simulation -> Ansys or Simulation -> EE-UQ -> EE-UQ (Download)
=> Working when selecting app w/o exec system

client/modules/reconportal/src/LeafletMap/LeafletMap.tsx
Sync markers on the map with filters from the side panel
* [WG-520](https://tacc-main.atlassian.net/browse/WG-520)
- Updated to use `useReconEventContext` to get `filteredReconPortalEvents` to display on map
1. Go to Recon Portal and use the filters in the side panel. Make sure map markers are updated accordingly
=> task/WG-520 -  Recon Portal Map Filtering

client/modules/_hooks/src/datafiles/projects/types.ts, client/modules/datafiles/src/projects/ProjectListing.tsx, client/modules/datafiles/src/projects/PublishedEntityDetails.tsx, client/modules/datafiles/src/projects/forms/PublishableEntityForm.tsx, designsafe/apps/api/projects_v2/operations/datacite_operations.py, designsafe/apps/api/projects_v2/schema_models/experimental.py, designsafe/apps/api/projects_v2/schema_models/field_recon.py, designsafe/apps/api/projects_v2/schema_models/hybrid_sim.py, designsafe/apps/api/projects_v2/schema_models/simulation.py
Adding keywords to entities and updating values for datacite
* [WC-74](https://tacc-main.atlassian.net/browse/WC-74)
* [WC-278](https://tacc-main.atlassian.net/browse/WC-278)
Keywords on each entity type
Datacite value updates
* license
* updated author affiliation info
* keywords appended from entity metadata
* modifying subtitle to just be a separate title (I don't know if this is what they're wanting, so this was first take on this request)
Basic testing steps, should do per project type
1. Create a project, not type other
2. Curate it, and you should find keywords required on the publishable entity
3. Make sure the keywords are showing on all the places where entity metadata is showing
4. Publish the entity, making sure keywords are showing up in the display
5. Make sure the entity …
=> WC-74 and WC-278: Entity Keywords and Datacite Updates

designsafe/apps/api/users/views.py
Prevent users with `is_active=False` from being added to projects. This attribute is set manually in Django-admin and we can use it to resolve issues for users who have multiple TACC accounts.
* [WC-284](https://tacc-main.atlassian.net/browse/WC-284)
1. Try adding an inactive user to a project and make sure that their username doesn't give any results. If you have a recent db dump then `fpanzera` can be used to test.
=> task/WC-284: Filter out inactive accounts when adding users to projects

designsafe/apps/api/projects_v2/operations/project_publish_operations.py
The file layout changes introduced a database call as part of the file copying step during the publication pipeline, resulting in the following order of operations:
1. Close database connections
2. Lookup original project UUID
3. Copy publication files
The lookup step (2) opens a new db connection that can result in a timeout when the db is accessed again after copying files. The fix is to perform the lookup BEFORE closing the connection, so that there aren't any connections left open before we start the final part of the pipeline.
=> Hotfix: Fix database order of operations during publication pipeline

client/modules/workspace/src/SelectModal/SelectModal.tsx
Updating the Select File/Folder modal in the applications area to handle long filenames
* [WP-987](https://tacc-main.atlassian.net/browse/WP-987)
Added middle truncating to long filenames
Added tooltips to filenames
Increased width of filename column
Minor increase to modal size
1. Pick an app that selects a file/folder
2. Open the modal, and make sure that any long file/folder names are middle truncated and tooltips show up with the full name.
=> bug/WP-987: Application Select File/Folder Modal updates

client/modules/datafiles/src/DatafilesModal/DownloadModal/DownloadModal.tsx
Adding section to download modal for specifically large publications with the path to the published data folder
* [WC-289](https://tacc-main.atlassian.net/browse/WC-289)
1. Pull up a publication with large dataset (PRJ-4040 is one) and make sure the download dataset modal with the large size warning shows the path for downloading.
2. Pull up another location in the portal with a large folder to try to download, and make sure the modal pops up but doesn't have a download path.
=> WC-289: Path for published on data download modal

client/modules/reconportal/src/ReconSidePanel/ReconSidePanel.module.css, client/modules/reconportal/src/ReconSidePanel/ReconSidePanel.tsx
This changes the side panel scrolling so that the filters stay stickied to the top and only the event list scrolls
* [WG-534](https://tacc-main.atlassian.net/browse/WG-534)
- Added CSS sticky filters and restructured HTML element hierarchy to separate scrollable event list from fixed filter controls
1. Open recon portal and scroll in the side panel
=> task/WG-534 - Recon Portal Event Scroll Changes

client/modules/datafiles/src/projects/ProjectPreview/ProjectPreview.tsx, client/src/datafiles/layouts/published/PublishedEntityListingLayout.tsx
Added flags to disable file listings and entity trees on tombstoned publications
* [WC-290](https://tacc-main.atlassian.net/browse/WC-290)
Added flags to disable file listings and entity trees on tombstoned publications
1. Open a type other tombstoned publication (eg  2227) and make sure there are no file listings.
2. Open a non-other type tombstoned publication (eg 4151) and make sure the tree isn't showing
3. Open a not tombstoned publication and make sure the file listings and trees show up correctly.
=> bug/WC-290: Tombstone disables file listings and entity trees
